typedef struct _SYSTEM_PROCESSOR_CYCLE_STATS_INFORMATION
{
  /* 0x0000 */ unsigned __int64 Cycles[2][4];
} SYSTEM_PROCESSOR_CYCLE_STATS_INFORMATION, *PSYSTEM_PROCESSOR_CYCLE_STATS_INFORMATION; /* size: 0x0040 */

