typedef struct _SYSTEM_CODEINTEGRITYVERIFICATION_INFORMATION
{
  /* 0x0000 */ void* FileHandle;
  /* 0x0008 */ unsigned long ImageSize;
  /* 0x0010 */ void* Image;
} SYSTEM_CODEINTEGRITYVERIFICATION_INFORMATION, *PSYSTEM_CODEINTEGRITYVERIFICATION_INFORMATION; /* size: 0x0018 */

