typedef enum _NDIS_LWFDRV_REFTAG
{
  LWFDRV_CHECKMINI = 0,
  LWFDRV_ATTACHING = 1,
  LWFDRV_ATTACHONE = 2,
  LWFDRV_CHECKALL = 3,
  LWFDRV_NOTIFYPNP = 4,
  LWFDRV_IOWORKITEM = 5,
  LWFDRV_IOWORKITEMC = 6,
  LWFDRV_SQM = 7,
  LWFDRV_FILTERMODULE = 8,
  LWFDRV_NUMBER_OF_TAGS = 9,
} NDIS_LWFDRV_REFTAG, *PNDIS_LWFDRV_REFTAG;

