typedef struct _REFS_VOLUME_COUNTER_INFO_INPUT_BUFFER
{
  /* 0x0000 */ unsigned char ResetCounters;
} REFS_VOLUME_COUNTER_INFO_INPUT_BUFFER, *PREFS_VOLUME_COUNTER_INFO_INPUT_BUFFER; /* size: 0x0001 */

