enum SLR_FLAGS
{
  SLR_NONE = 0,
  SLR_NO_UI = 1,
  SLR_ANY_MATCH = 2,
  SLR_UPDATE = 4,
  SLR_NOUPDATE = 8,
  SLR_NOSEARCH = 16,
  SLR_NOTRACK = 32,
  SLR_NOLINKINFO = 64,
  SLR_INVOKE_MSI = 128,
  SLR_NO_UI_WITH_MSG_PUMP = 257,
  SLR_OFFER_DELETE_WITHOUT_FILE = 512,
  SLR_KNOWNFOLDER = 1024,
  SLR_MACHINE_IN_LOCAL_TARGET = 2048,
  SLR_UPDATE_MACHINE_AND_SID = 4096,
  SLR_NO_OBJECT_ID = 8192,
};

