enum wrapEncodedKERNEL32Functions
{
  eFlsAlloc = 0,
  eFlsFree = 1,
  eFlsGetValue = 2,
  eFlsSetValue = 3,
  eInitializeCriticalSectionEx = 4,
  eInitOnceExecuteOnce = 5,
  eCreateEventExW = 6,
  eCreateSemaphoreW = 7,
  eCreateSemaphoreExW = 8,
  eCreateThreadpoolTimer = 9,
  eSetThreadpoolTimer = 10,
  eWaitForThreadpoolTimerCallbacks = 11,
  eCloseThreadpoolTimer = 12,
  eCreateThreadpoolWait = 13,
  eSetThreadpoolWait = 14,
  eCloseThreadpoolWait = 15,
  eFlushProcessWriteBuffers = 16,
  eFreeLibraryWhenCallbackReturns = 17,
  eGetCurrentProcessorNumber = 18,
  eCreateSymbolicLinkW = 19,
  eSetDefaultDllDirectories = 20,
  eCompareStringEx = 21,
  eEnumSystemLocalesEx = 22,
  eGetLocaleInfoEx = 23,
  eGetUserDefaultLocaleName = 24,
  eIsValidLocaleName = 25,
  eLCMapStringEx = 26,
  eGetTickCount64 = 27,
  eGetFileInformationByHandleEx = 28,
  eSetFileInformationByHandle = 29,
  eGetSystemTimePreciseAsFileTime = 30,
  eInitializeConditionVariable = 31,
  eWakeConditionVariable = 32,
  eWakeAllConditionVariable = 33,
  eSleepConditionVariableCS = 34,
  eInitializeSRWLock = 35,
  eAcquireSRWLockExclusive = 36,
  eTryAcquireSRWLockExclusive = 37,
  eReleaseSRWLockExclusive = 38,
  eSleepConditionVariableSRW = 39,
  eCreateThreadpoolWork = 40,
  eSubmitThreadpoolWork = 41,
  eCloseThreadpoolWork = 42,
  eMaxKernel32Function = 43,
};

