enum tagMSIPATCHSTATE
{
  MSIPATCHSTATE_INVALID = 0,
  MSIPATCHSTATE_APPLIED = 1,
  MSIPATCHSTATE_SUPERSEDED = 2,
  MSIPATCHSTATE_OBSOLETED = 4,
  MSIPATCHSTATE_REGISTERED = 8,
  MSIPATCHSTATE_ALL = 15,
};

