enum tagSCRIPTFLAGS
{
  SCRIPTFLAGS_CACHEINFO = 1,
  SCRIPTFLAGS_SHORTCUTS = 4,
  SCRIPTFLAGS_MACHINEASSIGN = 8,
  SCRIPTFLAGS_REGDATA_CNFGINFO = 32,
  SCRIPTFLAGS_VALIDATE_TRANSFORMS_LIST = 64,
  SCRIPTFLAGS_REGDATA_CLASSINFO = 128,
  SCRIPTFLAGS_REGDATA_EXTENSIONINFO = 256,
  SCRIPTFLAGS_REGDATA_APPINFO = 384,
  SCRIPTFLAGS_REGDATA = 416,
};

