enum VIEW_SETTING_ID
{
  VSIDF_VIEWMODE = 1,
  VSIDF_IMAGESIZE = 2,
  VSIDF_SORTCOLUMNS = 4,
  VSIDF_GROUPBY = 8,
  VSIDF_FOLDERFLAGS = 16,
  VSIDF_SUBSETCOUNT = 32,
  VSIDF_FOLDERTYPE = 64,
  VSIDF_VISIBLECOLUMNSWIDTH = 128,
  VSIDF_VISIBLECOLUMNSSET = 256,
  VSIDF_VISIBLECOLUMNSORDER = 512,
  VSIDF_VISIBLECOLUMNSALL = 896,
};

