typedef enum _JOBOBJECT_PAGE_PRIORITY_LIMIT_FLAGS
{
  JOBOBJECT_PAGE_PRIORITY_LIMIT_ENABLE = 1,
  JOBOBJECT_PAGE_PRIORITY_LIMIT_VALID_FLAGS = 1,
} JOBOBJECT_PAGE_PRIORITY_LIMIT_FLAGS, *PJOBOBJECT_PAGE_PRIORITY_LIMIT_FLAGS;

