typedef enum _AGGREGATION_MODE
{
  AGGREGATION_MODE_NONE = 112,
  AGGREGATION_MODE_SUM = 113,
  AGGREGATION_MODE_MIN = 114,
  AGGREGATION_MODE_MAX = 115,
  AGGREGATION_MODE_INVALID = 116,
} AGGREGATION_MODE, *PAGGREGATION_MODE;

