typedef enum _MM_ROUND_MODE_ENUM
{
  _MM_ROUND_MODE_NEAREST = 0,
  _MM_ROUND_MODE_DOWN = 1,
  _MM_ROUND_MODE_UP = 2,
  _MM_ROUND_MODE_TOWARD_ZERO = 3,
  _MM_ROUND_MODE_DEFAULT = 4,
  _MM_ROUND_MODE_NO_EXC = 8,
} MM_ROUND_MODE_ENUM, *PMM_ROUND_MODE_ENUM;

