enum GLOBALOPT_SERVICE_REFCOUNT_ENFORCEMENT
{
  GLOBALOPT_SERVICE_REFCOUNT_ENFORCEMENT_DEFAULT = 0,
  GLOBALOPT_SERVICE_REFCOUNT_ENFORCEMENT_DISALLOWGLOBALREFCOUNT = 1,
  GLOBALOPT_SERVICE_REFCOUNT_ENFORCEMENT_VALUECOUNT = 2,
};

