enum ISA_AVAILABILITY
{
  __ISA_AVAILABLE_X86 = 0,
  __ISA_AVAILABLE_SSE2 = 1,
  __ISA_AVAILABLE_SSE42 = 2,
  __ISA_AVAILABLE_AVX = 3,
  __ISA_AVAILABLE_ENFSTRG = 4,
  __ISA_AVAILABLE_AVX2 = 5,
  __ISA_AVAILABLE_ARMNT = 0,
  __ISA_AVAILABLE_NEON = 1,
  __ISA_AVAILABLE_NEON_ARM64 = 2,
};

