typedef enum _NDIS_NSI_INTERFACE_PURPOSE
{
  NDIS_NSI_INTERFACE_PURPOSE_DEFAULT = 0,
  NDIS_NSI_INTERFACE_PURPOSE_INTERNAL_VSWITCH_NIC = 1,
  NDIS_NSI_INTERFACE_PURPOSE_MAX = 2,
} NDIS_NSI_INTERFACE_PURPOSE, *PNDIS_NSI_INTERFACE_PURPOSE;

