typedef enum _REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS
{
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_START_COMPRESSION = 1,
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_STOP_COMPRESSION = 2,
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_GC_ONLY = 4,
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_MAX = 2,
} REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS, *PREFS_SET_VOLUME_COMPRESSION_INFO_FLAGS;

