typedef enum _NET_IF_RCV_ADDRESS_TYPE
{
  NET_IF_RCV_ADDRESS_TYPE_OTHER = 1,
  NET_IF_RCV_ADDRESS_TYPE_VOLATILE = 2,
  NET_IF_RCV_ADDRESS_TYPE_NON_VOLATILE = 3,
} NET_IF_RCV_ADDRESS_TYPE, *PNET_IF_RCV_ADDRESS_TYPE;

