typedef enum _NDIS_NSI_COMPARTMENT_TYPE
{
  NDIS_NSI_COMPARTMENT_TYPE_UNSPECIFIED = 0,
  NDIS_NSI_COMPARTMENT_TYPE_NATIVE = 1,
  NDIS_NSI_COMPARTMENT_TYPE_ROUTING_DOMAIN = 2,
  NDIS_NSI_COMPARTMENT_TYPE_CONTAINER = 3,
} NDIS_NSI_COMPARTMENT_TYPE, *PNDIS_NSI_COMPARTMENT_TYPE;

