typedef struct _SYSTEM_CODEINTEGRITY_CERTIFICATE_INFORMATION
{
  /* 0x0000 */ void* ImageFile;
  /* 0x0008 */ unsigned long Type;
  /* 0x000c */ long __PADDING__[1];
} SYSTEM_CODEINTEGRITY_CERTIFICATE_INFORMATION, *PSYSTEM_CODEINTEGRITY_CERTIFICATE_INFORMATION; /* size: 0x0010 */

