enum DIT_HITTESTATTRIBUTES
{
  DIT_HITTESTATTRIBUTES_NONE = 0,
  DIT_HITTESTATTRIBUTES_MOUSEWHEEL = 1,
  DIT_HITTESTATTRIBUTES_MOUSEBUTTONDOWN = 2,
  DIT_HITTESTATTRIBUTES_TOUCHTARGETING = 4,
  DIT_HITTESTATTRIBUTES_NOHOVERPOINTER = 8,
  DIT_HITTESTATTRIBUTES_VALID = 15,
  DIT_HITTESTATTRIBUTES_EDGEGESTUREINTERACTIVE = 1024,
};

