typedef struct _PROCESS_DYNAMIC_EH_CONTINUATION_TARGET
{
  /* 0x0000 */ unsigned long TargetAddress;
  /* 0x0004 */ unsigned long Flags;
} PROCESS_DYNAMIC_EH_CONTINUATION_TARGET, *PPROCESS_DYNAMIC_EH_CONTINUATION_TARGET; /* size: 0x0008 */

