typedef struct _SYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION_ENTRY
{
  /* 0x0000 */ unsigned __int64 ChangeStamp;
  /* 0x0008 */ void* Section;
  /* 0x000c */ unsigned long Size;
} SYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION_ENTRY, *PSYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION_ENTRY; /* size: 0x0010 */

typedef struct _SYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION
{
  /* 0x0000 */ unsigned __int64 OverallChangeStamp;
  /* 0x0008 */ struct _SYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION_ENTRY Descriptors[3];
} SYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION, *PSYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION; /* size: 0x0038 */

