typedef enum _NET_IF_RCV_ADDRESS_TYPE
{
  NET_IF_RCV_ADDRESS_TYPE_OTHER = 1,
  NET_IF_RCV_ADDRESS_TYPE_VOLATILE = 2,
  NET_IF_RCV_ADDRESS_TYPE_NON_VOLATILE = 3,
} NET_IF_RCV_ADDRESS_TYPE, *PNET_IF_RCV_ADDRESS_TYPE;

typedef struct _NDIS_NSI_IF_RCV_ADDRESS_ROD
{
  /* 0x0000 */ enum _NET_IF_RCV_ADDRESS_TYPE ifRcvAddressType;
  /* 0x0004 */ unsigned short ifRcvAddressLength;
  /* 0x0006 */ char __PADDING__[2];
} NDIS_NSI_IF_RCV_ADDRESS_ROD, *PNDIS_NSI_IF_RCV_ADDRESS_ROD; /* size: 0x0008 */

