typedef struct _ENCRYPTION_CERTIFICATE_HASH_LIST
{
  /* 0x0000 */ unsigned long nCert_Hash;
  /* 0x0008 */ struct _ENCRYPTION_CERTIFICATE_HASH** pUsers;
} ENCRYPTION_CERTIFICATE_HASH_LIST, *PENCRYPTION_CERTIFICATE_HASH_LIST; /* size: 0x0010 */

