enum APPCRUSHER_SOURCE
{
  ACS_BACKSTACK = 0,
  ACS_VISIBLE = 1,
  ACS_LIST = 2,
  ACS_APPTIP = 3,
  ACS_PLACEMODE = 4,
  ACS_TASKBAR = 5,
  ACS_TITLEBAR = 6,
  ACS_CAPTIONCONTROLS = 7,
  ACS_MULTITASKINGVIEW = 8,
  ACS_API = 9,
  ACS_HANGDETECTION = 10,
  ACS_INVALID = 11,
};

