enum SETTING_IDENTIFIER
{
  SI_STORE_APPS_ON_TASKBAR = 0,
  SI_GO_TO_DESKTOP_ON_SIGNIN = 1,
  SI_USE_STARTMENU = 2,
  SI_SNAPASSIST_ENABLE = 3,
  SI_SNAPFILL_ENABLE = 4,
  SI_VIRTUALDESKTOP_TASKBAR_FILTER = 5,
  SI_VIRTUALDESKTOP_ALTTAB_FILTER = 6,
  SI_SHELL_MODE_PREFERENCE = 7,
  SI_PRECISIONTOUCHPAD_THREEFINGERTAP = 8,
  SI_PRECISIONTOUCHPAD_FOURFINGERTAP = 9,
  SI_PRECISIONTOUCHPAD_THREEFINGERSLIDE = 10,
  SI_PRECISIONTOUCHPAD_FOURFINGERSLIDE = 11,
};

