enum TASK_FLOW_ID
{
  TFID_ADD_USER = 0,
  TFID_CONNECT_LOCAL_USER = 1,
  TFID_CONNECT_DOMAIN_USER = 2,
  TFID_DISCONNECT_USER = 3,
  TFID_DISCONNECT_DOMAIN_USER = 4,
  TFID_CHANGE_LOCAL_PASSWORD = 5,
  TFID_CHANGE_ONLINE_PASSWORD = 6,
  TFID_COMPLETEACCOUNT = 7,
  TFID_TASKFLOW_MAX = 8,
};

