enum EDP_CONTEXT_STATES
{
  EDP_CONTEXT_NONE = 0,
  EDP_CONTEXT_IS_EXEMPT = 1,
  EDP_CONTEXT_IS_ENLIGHTENED = 2,
  EDP_CONTEXT_IS_UNENLIGHTENED_ALLOWED = 4,
  EDP_CONTEXT_IS_PERMISSIVE = 8,
  EDP_CONTEXT_IS_COPY_EXEMPT = 16,
};

