typedef struct _SYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION_ENTRY
{
  /* 0x0000 */ unsigned __int64 ChangeStamp;
  /* 0x0008 */ void* Section;
  /* 0x0010 */ unsigned __int64 Size;
} SYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION_ENTRY, *PSYSTEM_FEATURE_CONFIGURATION_SECTIONS_INFORMATION_ENTRY; /* size: 0x0018 */

