enum GRID_HOW_SELECTED_FLAGS
{
  GHSF_UNKNOWN = 0,
  GHSF_SPACEBAR = 1,
  GHSF_ENTER = 2,
  GHSF_OTHERKEY = 4,
  GHSF_LEFTCLICK = 8,
  GHSF_CTRLLEFTCLICK = 16,
  GHSF_RIGHTCLICK = 32,
  GHSF_CTRLRIGHTCLICK = 64,
  GHSF_CONTEXT_KEY = 128,
  GHSF_KEYBOARD = 135,
};

