enum TEMPORARY_APP_VISUAL_TYPE
{
  TAVT_INVALID = 0,
  TAVT_DROPFEEDBACK = 1,
  TAVT_DRAGVISUAL = 2,
  TAVT_DRAGBACKGROUND = 3,
  TAVT_CLOSE = 4,
  TAVT_GUTTER = 5,
  TAVT_UNDERPAN = 6,
  TAVT_BACKGROUND = 7,
  TAVT_PLACE = 8,
};

