typedef struct _IOMMU_DMA_LOGICAL_ADDRESS_TOKEN_MAPPED_SEGMENT
{
  /* 0x0000 */ struct _IOMMU_DMA_LOGICAL_ADDRESS_TOKEN* OwningToken;
  /* 0x0004 */ unsigned long Offset;
  /* 0x0008 */ unsigned long Size;
} IOMMU_DMA_LOGICAL_ADDRESS_TOKEN_MAPPED_SEGMENT, *PIOMMU_DMA_LOGICAL_ADDRESS_TOKEN_MAPPED_SEGMENT; /* size: 0x000c */

