typedef enum _NT_IORING_CREATE_REQUIRED_FLAGS
{
  NT_IORING_CREATE_REQUIRED_FLAG_NONE = 0,
} NT_IORING_CREATE_REQUIRED_FLAGS, *PNT_IORING_CREATE_REQUIRED_FLAGS;

typedef enum _NT_IORING_CREATE_ADVISORY_FLAGS
{
  NT_IORING_CREATE_ADVISORY_FLAG_NONE = 0,
} NT_IORING_CREATE_ADVISORY_FLAGS, *PNT_IORING_CREATE_ADVISORY_FLAGS;

typedef struct _NT_IORING_CREATE_FLAGS
{
  /* 0x0000 */ enum _NT_IORING_CREATE_REQUIRED_FLAGS Required;
  /* 0x0004 */ enum _NT_IORING_CREATE_ADVISORY_FLAGS Advisory;
} NT_IORING_CREATE_FLAGS, *PNT_IORING_CREATE_FLAGS; /* size: 0x0008 */

