typedef enum _NDIS_PT_REFTAG
{
  PTREF_BIND_ITER = 0,
  PTREF_CHECKADAPTER = 1,
  PTREF_READREGISTRY = 2,
  PTREF_BINDNOTIFY = 3,
  PTREF_UNBINDNOTIFY = 4,
  PTREF_RECONFIG = 5,
  PTREF_UNLOADNOTIFY = 6,
  PTREF_UNBINDING = 7,
  PTREF_BINDING = 8,
  PTREF_BINDINGX = 9,
  PTREF_SQM = 10,
  PTREF_OPEN = 11,
  PTREF_REENUMERATE = 12,
  PTREF_CHECKPROT = 13,
  PTREF_QUNBIND = 14,
  PTREF_NUMBER_OF_TAGS = 15,
} NDIS_PT_REFTAG, *PNDIS_PT_REFTAG;

