typedef enum _NDIS_MDRV_REFTAG
{
  MDRVREF_IMDEINIT = 0,
  MDRVREF_REMOVINGMP = 1,
  MDRVREF_CHECKLWF = 2,
  MDRVREF_MINIPORT = 3,
  MDRVREF_REGISTERED = 4,
  MDRVREF_IOWORKITEM = 5,
  MDRVREF_IOWORKITEMC = 6,
  MDRVREF_NOTIFYMINI = 7,
  MDRVREF_MPREFH = 8,
  MDRVREF_MPREFN = 9,
  MDRVREF_MPREFT = 10,
  MDRVREF_CHECKPT = 11,
  MDRVREF_TIMEROBJDPC = 12,
  MDRVREF_TIMERDPCX = 13,
  MDRVREF_NUMBER_OF_TAGS = 14,
} NDIS_MDRV_REFTAG, *PNDIS_MDRV_REFTAG;

