typedef enum _NDIS_MPIF_REFTAG
{
  MPIFREF_IMDEINIT = 0,
  MPIFREF_AOAC = 1,
  MPIFREF_QUERYOBJ = 2,
  MPIFREF_GETTOP = 3,
  MPIFREF_GETRCVADDR = 4,
  MPIFREF_GETALLRCVADDR = 5,
  MPIFREF_CHIIB = 6,
  MPIFREF_CHIIUF = 7,
  MPIFREF_ENUMRCVADDR = 8,
  MPIFREF_SETISTATE = 9,
  MPIFREF_PMINIT = 10,
  MPIFREF_DEVPOWERUPFAIL = 11,
  MPIFREF_DEVPOWERUP = 12,
  MPIFREF_POWERDOWN = 13,
  MPIFREF_POWERDOWNFAIL = 14,
  MPIFREF_SQM = 15,
  MPIFREF_WMI = 16,
  MPIFREF_INITIALSTATE = 17,
  MPIFREF_REFMPGUID = 18,
  MPIFREF_NUMBER_OF_TAGS = 19,
} NDIS_MPIF_REFTAG, *PNDIS_MPIF_REFTAG;

