enum IMMERSIVELAUNCHERCONTROL
{
  ILC_SORTDROPDOWN = 0,
  ILC_USERTILE = 1,
  ILC_SEARCHBOX = 2,
  ILC_GRID = 3,
  ILC_STARTSEARCHBUTTON = 4,
  ILC_STARTPOWERBUTTON = 5,
  ILC_APPSSEARCHBUTTON = 6,
  ILC_MAX = 7,
};

