typedef enum _BACKGROUND_TASK_CAPABILITY
{
  BTC_AUDIO = 1,
  BTC_REALTIME_COMMUNICATION = 2,
  BTC_SYSTEM_EVENT = 4,
  BTC_TIMER = 8,
  BTC_PUSH_NOTIFICATION = 16,
  BTC_VPN_CLIENT = 32,
  BTC_DEVICE_SERVICING = 64,
  BTC_DEVICE_USE = 128,
  BTC_LOCATION = 256,
  BTC_IMPLICIT = 4096,
  BTC_ANY_CAPABILITY = 0xffffffff,
} BACKGROUND_TASK_CAPABILITY, *PBACKGROUND_TASK_CAPABILITY;

