typedef enum _PERSIST_SPROPSTORE_FLAGS_PRIV
{
  FPSPSP_DEFAULT = 0,
  FPSPSP_ASSUME_NO_DUPLICATES = 1,
  FPSPSP_ENABLE_ISDIRTY_DIFFING = 2,
} PERSIST_SPROPSTORE_FLAGS_PRIV, *PPERSIST_SPROPSTORE_FLAGS_PRIV;

