typedef struct _VOLUME_GET_GPT_ATTRIBUTES_INFORMATION
{
  /* 0x0000 */ unsigned __int64 GptAttributes;
} VOLUME_GET_GPT_ATTRIBUTES_INFORMATION, *PVOLUME_GET_GPT_ATTRIBUTES_INFORMATION; /* size: 0x0008 */

