enum APP_LAYOUT_ANIMATION_TYPE
{
  ALAT_NONE = 0,
  ALAT_EVICT_REPLACE = 1,
  ALAT_EVICT_CLOSE = 2,
  ALAT_EVICT_CLOSE_SCREEN = 3,
  ALAT_EVICT_LEFT = 4,
  ALAT_EVICT_RIGHT = 5,
  ALAT_EVICT_GENERIC = 6,
  ALAT_EVICT_SCREEN = 7,
  ALAT_INCOMING_SCREEN = 8,
  ALAT_INCOMING_MAXIMIZE = 9,
};

