enum IMM_APP_CHANGED
{
  IAC_UNKNOWN = 0,
  IAC_STARTED = 1,
  IAC_FOREGROUND = 2,
  IAC_BACKGROUND = 3,
  IAC_SHOWN = 4,
  IAC_HIDDEN = 5,
  IAC_CLOSED = 6,
  IAC_WINDOWPRESENTATIONDECLINED = 7,
  IAC_PRESENTEDWINDOWCHANGED = 8,
  IAC_MOBODYENTERED = 9,
  IAC_MOBODYEXIT = 10,
  IAC_HASPACKAGEID = 11,
  IAC_FORGOTTEN = 12,
  IAC_INTERACTIVE = 13,
  IAC_NON_INTERACTIVE = 14,
  IAC_PENDINGPRESENTEDWINDOWCANCELED = 15,
  IAC_FORGOTTEN_FOR_TERMINATION = 16,
};

