enum IMMERSIVELAUNCHERSCENARIO
{
  ILS_NONE = -1,
  ILS_LOGIN = 0,
  ILS_SHOW = 1,
  ILS_ORIENTATIONCHANGE = 2,
  ILS_DISMISS = 3,
  ILS_HIDE = 4,
  ILS_HIDE_DWM_TRANSITION = 5,
  ILS_HIDE_BY_APP_LAUNCH = 6,
  ILS_HIDE_BY_DESKTOP_TILE_LAUNCH = 7,
  ILS_RESET = 8,
  ILS_APPS_FIRST = 9,
  ILS_APPS_SHOW = 9,
  ILS_APPS_HIDE = 10,
  ILS_APPS_VIEW_CHANGE = 11,
  ILS_APPS_USER_SEES_START_VIEW_ENTER = 12,
  ILS_APPS_USER_SEES_START_VIEW_EXIT = 13,
  ILS_APPS_MAX = 14,
  ILS_MAX = 14,
};

