enum IMM_APP_ARRANGEMENT_TYPE
{
  IAAT_NONE = 0,
  IAAT_SLIDE_LEFT = 1,
  IAAT_SLIDE_RIGHT = 2,
  IAAT_EVICT_REPLACE = 3,
  IAAT_EVICT_CLOSE = 4,
  IAAT_EVICT_LEFT = 5,
  IAAT_EVICT_RIGHT = 6,
  IAAT_EVICT_GENERIC = 7,
};

