enum IMMERSIVELAUNCHERSCENARIO
{
  ILS_NONE = -1,
  ILS_LOGIN = 0,
  ILS_SHOW = 1,
  ILS_SHOW_DWM_TRANSITION = 2,
  ILS_ORIENTATIONCHANGE = 3,
  ILS_DISMISS = 4,
  ILS_HIDE = 5,
  ILS_HIDE_DWM_TRANSITION = 6,
  ILS_HIDE_BY_APP_LAUNCH = 7,
  ILS_HIDE_BY_DESKTOP_TILE_LAUNCH = 8,
  ILS_RESET = 9,
  ILS_APPS_FIRST = 10,
  ILS_APPS_SHOW = 10,
  ILS_APPS_HIDE = 11,
  ILS_APPS_VIEW_CHANGE = 12,
  ILS_APPS_USER_SEES_START_VIEW_ENTER = 13,
  ILS_APPS_USER_SEES_START_VIEW_EXIT = 14,
  ILS_APPS_MAX = 15,
  ILS_MAX = 15,
};

