enum SELECTIONMANAGERVALUE
{
  SMV_ITEMSELECTIONSTATES_REALIZED = 0,
  SMV_ITEMSELECTIONSTATES_UNREALIZED = 1,
  SMV_COLLECTIONSELECTIONSTATES_REALIZED = 2,
  SMV_COLLECTIONSELECTIONSTATES_UNREALIZED = 3,
  SMV_SELECTION = 4,
};

