enum TRYHARDERSCOPES
{
  THS_SPECIFIC_LIBRARY = 0,
  THS_ALL_LIBRARIES = 1,
  THS_ALL_USER_LIBRARIES = 2,
  THS_COMPUTER = 3,
  THS_CUSTOM_CANCEL = 4,
  THS_CUSTOM_NAVIGATE = 5,
  THS_INTERNET = 6,
  THS_GP_LIBRARY = 7,
  THS_GP_URL = 8,
  THS_SUBFOLDER = 9,
  THS_FILE_CONTENTS = 10,
  THS_UNUSED = 11,
  THS_OTHER = 12,
  THS_HISTORYVAULT = 13,
};

