enum RO_ERROR_REPORTING_FLAGS
{
  RO_ERROR_REPORTING_NONE = 0,
  RO_ERROR_REPORTING_SUPPRESSEXCEPTIONS = 1,
  RO_ERROR_REPORTING_FORCEEXCEPTIONS = 2,
  RO_ERROR_REPORTING_USESETERRORINFO = 4,
  RO_ERROR_REPORTING_SUPPRESSSETERRORINFO = 8,
};

