typedef enum _VRF_TRIAGE_CONTEXT
{
  VRF_TRIAGE_CONTEXT_DEFAULT = 0,
  VRF_TRIAGE_CONTEXT_DEVELOPMENT = 0,
  VRF_TRIAGE_CONTEXT_CERTIFICATION = 1,
  VRF_TRIAGE_CONTEXT_FLIGHT_TARGETED = 2,
  VRF_TRIAGE_CONTEXT_FLIGHT_DIAGNOSTICS = 3,
  VRF_TRIAGE_CONTEXT_FLIGHT_MONITORING = 4,
  NUM_VRF_TRIAGE_CONTEXTS = 5,
} VRF_TRIAGE_CONTEXT, *PVRF_TRIAGE_CONTEXT;

