typedef enum _COPYFILE2_MESSAGE_ACTION
{
  COPYFILE2_PROGRESS_CONTINUE = 0,
  COPYFILE2_PROGRESS_CANCEL = 1,
  COPYFILE2_PROGRESS_STOP = 2,
  COPYFILE2_PROGRESS_QUIET = 3,
  COPYFILE2_PROGRESS_PAUSE = 4,
} COPYFILE2_MESSAGE_ACTION, *PCOPYFILE2_MESSAGE_ACTION;

