enum MODE_CHANGE_REASON
{
  MCR_NONE = 0,
  MCR_ACTIVATION = 1,
  MCR_MONITORCHANGE = 2,
  MCR_OWNEDWINDOWCREATED = 3,
  MCR_SHOWDESKTOP = 4,
  MCR_PRESENTEDWINDOWCHANGED = 5,
  MCR_SIMULATED_ACTIVATION = 6,
  MCR_CROSS_MONITOR_ACTIVATION = 7,
};

