typedef enum _NDIS_NSI_INTERFACE_PURPOSE
{
  NDIS_NSI_INTERFACE_PURPOSE_DEFAULT = 0,
  NDIS_NSI_INTERFACE_PURPOSE_INTERNAL_VSWITCH_NIC = 1,
  NDIS_NSI_INTERFACE_PURPOSE_SECONDARY_OR_ONDEMAND = 2,
  NDIS_NSI_INTERFACE_PURPOSE_IN_DISCONNECTED_STANDBY = 3,
  NDIS_NSI_INTERFACE_PURPOSE_IN_FAILOVER = 4,
  NDIS_NSI_INTERFACE_PURPOSE_MAX = 5,
} NDIS_NSI_INTERFACE_PURPOSE, *PNDIS_NSI_INTERFACE_PURPOSE;

