enum tagMSIINSTALLCONTEXT
{
  MSIINSTALLCONTEXT_FIRSTVISIBLE = 0,
  MSIINSTALLCONTEXT_NONE = 0,
  MSIINSTALLCONTEXT_USERMANAGED = 1,
  MSIINSTALLCONTEXT_USERUNMANAGED = 2,
  MSIINSTALLCONTEXT_MACHINE = 4,
  MSIINSTALLCONTEXT_ALL = 7,
  MSIINSTALLCONTEXT_ALLUSERMANAGED = 8,
};

