enum UDTAlignmentWorkaroundAction
{
  UDT_ACTION_INVALID = 0,
  UDT_ACTION_NOOP = 1,
  UDT_ACTION_USEOLDDCOM56 = 2,
  UDT_ACTION_USE_NEWDCOM56_SIMPLESTRUCT = 3,
  UDT_ACTION_USE_NEWDCOM56_NORMAL = 4,
};

