typedef enum _CI_WINDOWS_LOCKDOWN_MODE
{
  CI_WINDOWS_LOCKDOWN_MODE_UNLOCKED = 0,
  CI_WINDOWS_LOCKDOWN_MODE_TRIAL = 1,
  CI_WINDOWS_LOCKDOWN_MODE_LOCKED = 2,
  CI_WINDOWS_LOCKDOWN_MODE_MAX = 3,
} CI_WINDOWS_LOCKDOWN_MODE, *PCI_WINDOWS_LOCKDOWN_MODE;

