typedef enum _FS_BPIO_OUTFLAGS
{
  FSBPIO_OUTFL_None = 0,
  FSBPIO_OUTFL_VOLUME_STACK_BYPASS_PAUSED = 1,
  FSBPIO_OUTFL_STREAM_BYPASS_PAUSED = 2,
  FSBPIO_OUTFL_FILTER_ATTACH_BLOCKED = 4,
  FSBPIO_OUTFL_COMPATIBLE_STORAGE_DRIVER = 8,
} FS_BPIO_OUTFLAGS, *PFS_BPIO_OUTFLAGS;

