typedef struct _LCN_WEAK_REFERENCE_VCN_MAPPING
{
  /* 0x0000 */ __int64 Vcn;
  /* 0x0008 */ __int64 Lcn;
  /* 0x0010 */ __int64 CountOfRange;
} LCN_WEAK_REFERENCE_VCN_MAPPING, *PLCN_WEAK_REFERENCE_VCN_MAPPING; /* size: 0x0018 */

typedef struct _LCN_WEAK_REFERENCE_CREATE_OUTPUT_BUFFER
{
  /* 0x0000 */ unsigned long MappingCount;
  /* 0x0008 */ struct _LCN_WEAK_REFERENCE_VCN_MAPPING VcnLcnMappings[1];
} LCN_WEAK_REFERENCE_CREATE_OUTPUT_BUFFER, *PLCN_WEAK_REFERENCE_CREATE_OUTPUT_BUFFER; /* size: 0x0020 */

