typedef struct _PROCESS_DYNAMIC_FUNCTION_TABLE_INFORMATION
{
  /* 0x0000 */ struct _DYNAMIC_FUNCTION_TABLE* DynamicFunctionTable;
  /* 0x0008 */ unsigned char Remove;
  /* 0x0009 */ char __PADDING__[7];
} PROCESS_DYNAMIC_FUNCTION_TABLE_INFORMATION, *PPROCESS_DYNAMIC_FUNCTION_TABLE_INFORMATION; /* size: 0x0010 */

