typedef enum _REFS_DEALLOCATE_RANGES_ALLOCATOR
{
  REFS_DEALLOCATE_RANGES_ALLOCATOR_NONE = 0,
  REFS_DEALLOCATE_RANGES_ALLOCATOR_SAA = 1,
  REFS_DEALLOCATE_RANGES_ALLOCATOR_CAA = 2,
  REFS_DEALLOCATE_RANGES_ALLOCATOR_MAA = 3,
} REFS_DEALLOCATE_RANGES_ALLOCATOR, *PREFS_DEALLOCATE_RANGES_ALLOCATOR;

typedef struct _REFS_DEALLOCATE_RANGES_INPUT_BUFFER_EX
{
  /* 0x0000 */ unsigned long RangeCount;
  /* 0x0004 */ enum _REFS_DEALLOCATE_RANGES_ALLOCATOR Allocator;
  /* 0x0008 */ __int64 StreamReserveUpdateCount;
  /* 0x0010 */ unsigned long OffsetToRanges;
  /* 0x0014 */ unsigned long OffsetToLeakCounts;
  /* 0x0018 */ unsigned __int64 Reserved[2];
} REFS_DEALLOCATE_RANGES_INPUT_BUFFER_EX, *PREFS_DEALLOCATE_RANGES_INPUT_BUFFER_EX; /* size: 0x0028 */

