typedef enum _REFS_COMPRESSION_FORMATS
{
  REFS_COMPRESSION_FORMAT_UNCHANGED = 0,
  REFS_COMPRESSION_FORMAT_UNKNOWN = 1,
  REFS_COMPRESSION_FORMAT_UNCOMPRESSED = 2,
  REFS_COMPRESSION_FORMAT_LZ4 = 3,
  REFS_COMPRESSION_FORMAT_ZSTD = 4,
} REFS_COMPRESSION_FORMATS, *PREFS_COMPRESSION_FORMATS;

