typedef enum _REFS_QUERY_VOLUME_COMPRESSION_INFO_FLAGS
{
  REFS_QUERY_VOLUME_COMPRESSION_INFO_FLAGS_RUNNING = 1,
  REFS_QUERY_VOLUME_COMPRESSION_INFO_FLAGS_STOPPED = 2,
} REFS_QUERY_VOLUME_COMPRESSION_INFO_FLAGS, *PREFS_QUERY_VOLUME_COMPRESSION_INFO_FLAGS;

