enum IMMERSIVELAUNCHERDISMISSMETHOD
{
  ILDM_INVALID = 0,
  ILDM_HSHELLTASKMAN = 1,
  ILDM_STARTCHARM = 2,
  ILDM_BACKGESTURE = 3,
  ILDM_ESCAPEKEY = 4,
  ILDM_SHOWDESKTOP = 5,
  ILDM_STARTTIP = 6,
  ILDM_GENERIC_NONANIMATING = 7,
  ILDM_SEARCH_OPENING = 8,
  ILDM_DRAG = 9,
};

