enum POWER_SETTING_ALTITUDE
{
  ALTITUDE_GROUP_POLICY = 0,
  ALTITUDE_USER = 1,
  ALTITUDE_RUNTIME_OVERRIDE = 2,
  ALTITUDE_PROVISIONING = 3,
  ALTITUDE_OEM_CUSTOMIZATION = 4,
  ALTITUDE_INTERNAL_OVERRIDE = 5,
  ALTITUDE_OS_DEFAULT = 6,
};

