/*
??$AddBindingToSet@UNDIS_BIND_FILTER_LINK@@@BindRegistry@Ndis@@YA_NPEAU_NDIS_MINIPORT_BLOCK@@AEAV?$KArray@V?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Rtl@@_KAEAV?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Z
??$AddBindingToSet@UNDIS_BIND_PROTOCOL_LINK@@@BindRegistry@Ndis@@YA_NPEAU_NDIS_MINIPORT_BLOCK@@AEAV?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@_KAEAV?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Z
??$QueryValueBlob@V<lambda_999d7960ce7bd727c937eec9f53d3cb3>@@@KRegKey@@QEAAJPEBU_UNICODE_STRING@@V<lambda_999d7960ce7bd727c937eec9f53d3cb3>@@@Z
??$QueryValueMultisz@V<lambda_7b34f67d2fe748a9991e85b83cffda76>@@V<lambda_7db8344f8beb56adaa003951e6a1fc8c>@@@KRegKey@@QEAAJPEBU_UNICODE_STRING@@V<lambda_7b34f67d2fe748a9991e85b83cffda76>@@V<lambda_7db8344f8beb56adaa003951e6a1fc8c>@@@Z
??$QueryValueMultisz@V<lambda_fa4c34603c51c7c89984ed578d5a8406>@@V<lambda_03b7dc101703010b5abc3b1143cfebff>@@@KRegKey@@QEAAJPEBU_UNICODE_STRING@@V<lambda_fa4c34603c51c7c89984ed578d5a8406>@@V<lambda_03b7dc101703010b5abc3b1143cfebff>@@@Z
??0BindEngine@Ndis@@QEAA@XZ
??0BindStack@Ndis@@QEAA@XZ
??0BindState@Ndis@@QEAA@XZ
??0KLockThisExclusive@@QEAA@AEAVKPushLockBase@@@Z
??0KPushLock@@QEAA@XZ
??0KWaitEvent@@QEAA@XZ
??0NDIS_BIND_LINK_BASE@@QEAA@XZ
??0_NDIS_MINIPORT_BLOCK@@QEAA@XZ
??1BindEngine@Ndis@@QEAA@XZ
??1BindStack@Ndis@@QEAA@XZ
??1KLockHolder@@QEAA@XZ
??1NDIS_BIND_LINK_BASE@@QEAA@XZ
??2@YAPEAX_KPEAX@Z
??4?$KRef@UNDIS_BIND_FILTER_DRIVER@@@@QEAAAEAV0@$$QEAV0@@Z
??4?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@QEAAAEAV0@$$QEAV0@@Z
??_G?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@QEAAPEAXI@Z
??_G?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@QEAAPEAXI@Z
??_G?$KRef@UNDIS_BIND_FILTER_DRIVER@@@@QEAAPEAXI@Z
??_G?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@QEAAPEAXI@Z
??_GKRefHolder@?$KRef@UNDIS_BIND_FILTER_DRIVER@@@@QEAAPEAXI@Z
??_GKRefHolder@?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@QEAAPEAXI@Z
??_G_NDIS_FILTER_DRIVER_BLOCK@@QEAAPEAXI@Z
??_G_NDIS_PROTOCOL_BLOCK@@QEAAPEAXI@Z
??_U@YAPEAX_KK@Z
?Acquire@?$KNeutralLock@W4NDIS_MINIPORT_POLICY_OWNER@@@Rtl@@QEAAXW4NDIS_MINIPORT_POLICY_OWNER@@@Z
?AcquireExclusive@KLockHolder@@QEAAXXZ
?AcquireShared@KLockHolder@@QEAAXXZ
?AddBindContext@BindState@Ndis@@QEAA_NPEAX@Z
?AdjustOffloadContext@@YAXPEAU_NDIS_OPEN_BLOCK@@PEAU_NDIS_PROTOCOL_OFFLOAD_BLOCK_LIST@@H@Z
?Apply@BindRules@Ndis@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ApplyBindChanges@BindEngine@Ndis@@QEAAXW4CallRunMode@@@Z
?ApplyRules@BindEngine@Ndis@@AEAAXXZ
?BeginPolicyUpdates@BindEngine@Ndis@@QEAAXXZ
?BuildFilterLink@BindStack@Ndis@@AEAA?AV?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@PEBU_GUID@@K@Z
?BuildProtocolLink@BindStack@Ndis@@AEAA?AV?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@AEAV?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@@Z
?BuildProtocolLink@BindStack@Ndis@@AEAA?AV?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@PEAU_UNICODE_STRING@@@Z
?CallbackThunk@?$KWorkItemBase@UBindEngine@Ndis@@V?$KWorkItem@UBindEngine@Ndis@@@@@@CAXPEAX@Z
?CallbackThunk@?$KWorkItemBase@U_NDIS_PROTOCOL_BLOCK@@V?$KCoalescingWorkItem@U_NDIS_PROTOCOL_BLOCK@@@@@@CAXPEAX@Z
?CheckAllDriversRunning@Initmode@Ndis@@YA_NPEAU_NDIS_MINIPORT_BLOCK@@@Z
?CheckForDriverLoaded@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?CheckMissingMandatoryFilter@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?CheckMissingModifyingFilter@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?CoalesceFilterAttachDuringBoot@BindRules@Ndis@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUBindStack@2@@Z
?ComputeDelta@BindRegistry@Ndis@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUBindStack@2@1W4Flags@ReadBindingsOptions@2@@Z
?CreateDynamicBinding@BindStack@Ndis@@QEAAPEAUNDIS_BIND_PROTOCOL_LINK@@AEAV?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@PEAU_NDIS_MINIPORT_BLOCK@@W4Flags@BindSource@2@@Z
?DisableIfNeeded@Initmode@Ndis@@YAXPEAU_NDIS_MINIPORT_BLOCK@@W4CallRunMode@@@Z
?DispatchPendingWork@BindEngine@Ndis@@AEAAXW4CallRunMode@@AEAVKLockThisExclusive@@@Z
?EndBindOperation@BindEngine@Ndis@@SAXXZ
?EndPolicyUpdates@BindEngine@Ndis@@QEAAXXZ
?EtwEx_tidActivityInfoTransfer@@YAK_KPEBU_EVENT_DESCRIPTOR@@PEBU_GUID@@2E2K@Z
?ForEachLink@NDIS_BIND_DRIVER_BASE@@QEAAXP6AXPEAUNDIS_BIND_LINK_BASE@@@Z@Z
?GetActualBindingState@BindState@Ndis@@QEAA?AW4BINDING_ENABLED_OR_DISABLED@@XZ
?GetBindContext@BindState@Ndis@@QEAAPEAXXZ
?GetCurrentLink@BindEngine@Ndis@@QEBAPEAUNDIS_BIND_LINK_BASE@@XZ
?GetMsgDpc@@YAPEAU_KDPC@@PEAU_NDIS_INTERRUPT_BLOCK@@KK@Z
?GroupCompletionContext@@YAPEAU_NDIS_OPEN_BLOCK@@PEAU_NET_BUFFER_LIST@@PEAPEAU2@@Z
?IFBLOCK_DEREFERENCE_MINIPORT_LINK@@YAXPEAU_NDIS_IF_BLOCK@@W4_NDIS_MPIF_REFTAG@@@Z
?Initialize@BindEngine@Ndis@@QEAAXPEAU_NDIS_MINIPORT_BLOCK@@@Z
?Initialize@KPushLockManualConstruct@@QEAAXXZ
?Initialize@KString@Rtl@@SAPEAU12@PEBG@Z
?Initialize@KString@Rtl@@SAPEAU12@PEBU_UNICODE_STRING@@@Z
?IsAlive@BindState@Ndis@@QEBA_NXZ
?IsReadLockAlreadyHeldByCurrentThread@@YAHPEAU_NDIS_RW_LOCK@@@Z
?Iterate@BindEngine@Ndis@@AEAA_NXZ
?LinkToDriver@NDIS_BIND_LINK_BASE@@QEAAXPEAUNDIS_BIND_DRIVER_BASE@@@Z
?LockBindings@BindEngine@Ndis@@QEAAXXZ
?MakeOptionalFiltersMandatoryDuringBoot@BindRules@Ndis@@YAXPEAUBindStack@2@_N@Z
?MiniportSupportsReceiveThrottle@@YAEPEAU_NDIS_MINIPORT_BLOCK@@@Z
?NDISM_SEND_PACKET_STATS@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_PACKET@@@Z
?NDIS_COUNT_POWER_TRANSITION@@YAXPEAU_NDIS_MINIPORT_BLOCK@@W4_NDIS_DEVICE_POWER_STATE@@@Z
?NDIS_FREE_XFER_DATA_PACKET@@YAXPEAU_NDIS_PACKET@@@Z
?NDIS_STACK_RESERVED_FROM_PACKET@@YAXPEAU_NDIS_PACKET@@PEAPEAU_NDIS_STACK_RESERVED@@@Z
?NdisMTcpOffloadDisconnectComplete@@YAXPEAXPEAU_NET_BUFFER_LIST@@@Z
?NdisMTcpOffloadEventIndicate@@YAXPEAXKK@Z
?NdisMTcpOffloadForwardComplete@@YAXPEAXPEAU_NET_BUFFER_LIST@@@Z
?NdisMTcpOffloadReceiveComplete@@YAXPEAXPEAU_NET_BUFFER_LIST@@@Z
?NdisMTcpOffloadReceiveIndicate@@YAHPEAXPEAU_NET_BUFFER_LIST@@HPEAK@Z
?NdisMTcpOffloadSendComplete@@YAXPEAXPEAU_NET_BUFFER_LIST@@@Z
?NdisQueryPacket@@YAXPEAU_NDIS_PACKET@@PEAI1PEAPEAU_MDL@@1@Z
?NetDmaDeregisterProvider@@YAXPEAX@Z
?NetDmaGetVersion@@YAIXZ
?NetDmaInterruptDpc@@YAXPEAXT_LARGE_INTEGER@@@Z
?NetDmaIsr@@YAXPEAXT_LARGE_INTEGER@@PEAK@Z
?NetDmaPnPEventNotify@@YAXPEAXPEAU_NET_DMA_PNP_NOTIFICATION@@@Z
?NetDmaProviderStart@@YAXPEAXPEAU_NET_DMA_PROVIDER_ATTRIBUTES@@@Z
?NetDmaProviderStop@@YAXPEAX@Z
?NetDmaRegisterProvider@@YAJPEAXPEAPEAXPEAU_NET_DMA_PROVIDER_CHARACTERISTICS@@@Z
?NetTrcIsNetBufferListCorrelationIdValid@@YAEPEAU_NET_BUFFER_LIST@@@Z
?NotifyBindComplete@_NDIS_PROTOCOL_BLOCK@@QEAAXXZ
?Open@KRegKey@@QEAAJKPEBGPEAX@Z
?Open@KRegKey@@QEAAJKPEBU_UNICODE_STRING@@PEAX@Z
?ParseV1FilterString@BindStack@Ndis@@AEAA_NPEBGPEAU_NDIS_FILTERLIST_ITEM@@@Z
?PauseNeededForBind@BindRules@Ndis@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUBindStack@2@@Z
?QueryValueBoolean@KRegKey@@QEAAJPEBGPEAEW4BooleanDisposition@1@@Z
?QueryValueString@KRegKey@@QEAAJPEBGAEAV?$KPtr@UKString@Rtl@@U?$KDeletePtr@UKString@Rtl@@@@@@@Z
?QueryValueString@KRegKey@@QEAAJPEBU_UNICODE_STRING@@AEAV?$KPtr@UKString@Rtl@@U?$KDeletePtr@UKString@Rtl@@@@@@@Z
?QueryValueUlong@KRegKey@@QEAAJPEBGPEAK@Z
?QueryValueUlong@KRegKey@@QEAAJPEBU_UNICODE_STRING@@PEAK@Z
?ReEnableTemporaryUnbind@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?ReStartTemporaryPause@BindRules@Ndis@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ReadV1FilterList@BindStack@Ndis@@AEAAJAEAVKRegKey@@@Z
?ReadV1InterfaceBindings@BindStack@Ndis@@AEAA_NPEAU_DEVICE_OBJECT@@@Z
?ReadV1OrV2ProtocolList@BindStack@Ndis@@AEAAJAEAVKRegKey@@PEBU_UNICODE_STRING@@@Z
?ReadV2InterfaceBindings@BindStack@Ndis@@AEAA_NPEBU_GUID@@@Z
?Release@?$KNeutralLock@W4NDIS_MINIPORT_POLICY_OWNER@@@Rtl@@QEAAXW4NDIS_MINIPORT_POLICY_OWNER@@@Z
?ReleaseExclusive@KLockHolder@@QEAAXXZ
?ReleaseShared@KLockHolder@@QEAAXXZ
?Reload@BindRegistry@Ndis@@YAJPEAU_NDIS_MINIPORT_BLOCK@@W4Flags@ReadBindingsOptions@2@@Z
?RemoveBindContext@BindState@Ndis@@QEAAXPEAX@Z
?RetryProtocolBindingsAfterMiniportChange@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?RtlCopyBufferToMdl@@YAJPEAXPEAU_MDL@@_K2PEA_K@Z
?RtlCopyMdlToBuffer@@YAJPEAU_MDL@@_KPEAX1PEA_K@Z
?RtlCopyMdlToMdl@@YAJPEAU_MDL@@_K011PEA_K@Z
?RtlStringCbPrintfW@@YAJPEAG_KPEBGZZ
?RtlStringCchPrintfW@@YAJPEAG_KPEBGZZ
?RtlULongLongMult@@YAJ_K0PEA_K@Z
?RtlUnicodeStringCat@@YAJPEAU_UNICODE_STRING@@PEBU1@@Z
?RtlUnicodeStringCopy@@YAJPEAU_UNICODE_STRING@@PEBU1@@Z
?RtlUnicodeStringCopyString@@YAJPEAU_UNICODE_STRING@@PEBG@Z
?RtlUnicodeStringPrintf@@YAJPEAU_UNICODE_STRING@@PEBGZZ
?SetBinding@BindState@Ndis@@QEAA_NW4BINDING_ENABLED_OR_DISABLED@@W4NDIS_DO_NOT_BIND_REASON@@@Z
?SetDirty@BindEngine@Ndis@@QEAAXXZ
?SetPause@BindState@Ndis@@QEAA_NW4PAUSE_OR_RESTART@@W4NDIS_PAUSE_REASON@@@Z
?SetRunningDriver@NDIS_BIND_FILTER_DRIVER@@QEAAXPEAU_NDIS_FILTER_DRIVER_BLOCK@@W4CallRunMode@@@Z
?SetRunningDriver@NDIS_BIND_PROTOCOL_DRIVER@@QEAAXPEAU_NDIS_PROTOCOL_BLOCK@@W4CallRunMode@@@Z
?SetRunningDriverIsReady@NDIS_BIND_DRIVER_BASE@@IEAAX_NW4CallRunMode@@@Z
?StoreCompletionContext@@YAXPEAU_NDIS_OPEN_BLOCK@@PEAU_NET_BUFFER_LIST@@@Z
?TryAcquire@?$KNeutralLock@W4NDIS_MINIPORT_POLICY_OWNER@@@Rtl@@QEAA_NW4NDIS_MINIPORT_POLICY_OWNER@@@Z
?UnbindMiniportStack@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?UnbindOnAttach@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?UnbindOnDetach@BindRules@Ndis@@YAXPEAUBindStack@2@@Z
?UnlockBindings@BindEngine@Ndis@@QEAAXXZ
?UpdateBindings@BindEngine@Ndis@@AEAAXXZ
?UpdateBindingsWorkItem@BindEngine@Ndis@@AEAAXXZ
?UpdateFilters@BindRegistry@Ndis@@YA_NPEAU_NDIS_MINIPORT_BLOCK@@AEAV?$KArray@V?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Rtl@@1W4Flags@ReadBindingsOptions@2@@Z
?UpdateProtocols@BindRegistry@Ndis@@YA_NPEAU_NDIS_MINIPORT_BLOCK@@AEAV?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@1W4Flags@ReadBindingsOptions@2@@Z
?Wait@KWaitEvent@@QEAAXXZ
?append@?$KArray@V?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Rtl@@QEAA_N$$QEAV?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Z
?append@?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@QEAA_N$$QEAV?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Z
?grow@?$KArray@V?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Rtl@@AEAA_N_K@Z
?grow@?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@AEAA_N_K@Z
?grow@?$KArray@V?$KRef@UNDIS_BIND_FILTER_DRIVER@@@@@Rtl@@AEAA_N_K@Z
?grow@?$KArray@V?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@@Rtl@@AEAA_N_K@Z
?insertAt@?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@QEAA_N_K$$QEAV?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Z
?insertSortedUnique@?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@QEAA_N$$QEAV?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@P6A_NAEBV3@1@Z@Z
?moveElements@?$KArray@V?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Rtl@@AEAAXKKK@Z
?moveElements@?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@AEAAXKKK@Z
?ndisAcquireReadLockPerCpuRefCnt@@YAXPEAU_NDIS_RW_LOCK@@PEAK@Z
?ndisAcquireReadLockSharedRefCnt@@YAHPEAU_NDIS_RW_LOCK@@@Z
?ndisAcquireWriteLockPerCpuRefCnt@@YAXPEAU_NDIS_RW_LOCK@@PEAK_K@Z
?ndisAcquireWriteLockSharedRefCnt@@YAHPEAU_NDIS_RW_LOCK@@@Z
?ndisAllocateFromNPagedPool@@YAPEAXW4_POOL_TYPE@@_KKPEAU_LOOKASIDE_LIST_EX@@@Z
?ndisAllocateIterativeDataPathTracker@@YAHPEAU_NDIS_FILTER_BLOCK@@@Z
?ndisAllocateMdl@@YAPEAU_MDL@@PEAK@Z
?ndisAoAcIsD0Required@@YAEPEAU_NDIS_MINIPORT_AOAC@@@Z
?ndisAoAcIsTempRefNeededAfterDeref@@YAEPEAU_NDIS_MINIPORT_AOAC@@@Z
?ndisAoAcStartRefTimeStats@@YAXPEAU_NDIS_MINIPORT_AOAC@@@Z
?ndisAoAcTraceRundown@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisAoAcWriteRefcountRundown@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_MINIPORT_AOAC@@@Z
?ndisAttachFilter@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_FILTER_LINK@@@Z
?ndisAttachFilterInner@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_FILTER_DRIVER_BLOCK@@KPEAUNDIS_BIND_FILTER_LINK@@@Z
?ndisBindEnumerateProtocolDrivers@@YAXP6AXPEAXV?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@@Z0@Z
?ndisBindGetFilterDriver@@YA?AV?$KRef@UNDIS_BIND_FILTER_DRIVER@@@@PEBU_GUID@@@Z
?ndisBindGetProtocolDriver@@YA?AV?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@PEAU_UNICODE_STRING@@@Z
?ndisBindLegacyProtocol@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_PROTOCOL_BLOCK@@PEAUNDIS_BIND_PROTOCOL_LINK@@@Z
?ndisBindNdis6Protocol@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_PROTOCOL_BLOCK@@@Z
?ndisBindProtocol@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_PROTOCOL_LINK@@@Z
?ndisBindReadFilterDriverFromV1Registry@@YA_NPEAUNDIS_BIND_FILTER_DRIVER@@@Z
?ndisBindReadFilterDriverFromV2Registry@@YA_NPEAUNDIS_BIND_FILTER_DRIVER@@@Z
?ndisBindReadFilterDriverSettingsFromV1Registry@@YA_NPEAUNDIS_BIND_FILTER_DRIVER@@AEAVKRegKey@@@Z
?ndisBindReadFilterDriverSettingsFromV2Registry@@YA_NPEAUNDIS_BIND_FILTER_DRIVER@@AEAVKRegKey@@@Z
?ndisBindReadProtocolDriverConfiguration@@YA_NPEAUNDIS_BIND_PROTOCOL_DRIVER@@@Z
?ndisCallReceiveCompleteHandler@@YAXP6AXXZPEAXPEAU_NET_BUFFER_LIST@@KKK@Z
?ndisCallReceiveHandler@@YAXP6AXXZPEAXPEAU_NET_BUFFER_LIST@@KKK@Z
?ndisCallSendCompleteHandler@@YAXP6AXXZPEAXPEAU_NET_BUFFER_LIST@@KKK@Z
?ndisCallSendHandler@@YAXP6AXXZPEAXPEAU_NET_BUFFER_LIST@@KKK@Z
?ndisCheckForNdisTestBindingsOnAllMiniports@@YAXXZ
?ndisCheckOidBufferIntegrity@@YAXPEAU_NDIS_OID_REQUEST@@PEAU_NDIS_OBJECT_HEADER@@@Z
?ndisCheckWatchdogTimer@@YAEXZ
?ndisClearTransientBindFailuresAboveThisFilter@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_FILTER_LINK@@@Z
?ndisCmCleanupSessionState@@YAXXZ
?ndisCmCleanupThreadState@@YAXXZ
?ndisCmFindCompartment@@YAPEAXI@Z
?ndisCmGetThreadSessionId@@YAKPEAU_ETHREAD@@@Z
?ndisCmLazyInitializeCleanup@@YAXXZ
?ndisCoIndicatePromiscNetBuffer@@YAXPEAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@PEAU_NET_BUFFER_LIST@@KKE@Z
?ndisCoIndicatePromiscPacket@@YAXPEAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@PEAU_NDIS_PACKET@@EE@Z
?ndisCoSendNetBufferListsToNdisPacket@@YAXPEAXPEAU_NET_BUFFER_LIST@@K@Z
?ndisCoSendNetBufferListsToNetBufferLists@@YAXPEAXPEAU_NET_BUFFER_LIST@@K@Z
?ndisCoSendPacketsToNdisPackets@@YAXPEAXPEAPEAU_NDIS_PACKET@@I@Z
?ndisCoSendPacketsToNetBufferLists@@YAXPEAXPEAPEAU_NDIS_PACKET@@I@Z
?ndisCompareProcNum@@YAHU_PROCESSOR_NUMBER@@0@Z
?ndisCompareStatusCodes@@YAHPEBX0@Z
?ndisCompleteUnsolicitedUnbind@@YAXPEAX@Z
?ndisCopyPeriodicReceiveNbl@@YAPEAU_NET_BUFFER_LIST@@PEAU_NDIS_MINIPORT_BLOCK@@KPEAU1@@Z
?ndisCounterSetProviderCallback@@YAJW4_PCW_CALLBACK_TYPE@@PEAT_PCW_CALLBACK_INFORMATION@@PEAX@Z
?ndisDeliverBindCompleteEvent@@YAXPEAUNDIS_BIND_PROTOCOL_DRIVER@@@Z
?ndisDetachFilter@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_FILTER_LINK@@@Z
?ndisDetachFilterInner@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_FILTER_BLOCK@@@Z
?ndisDoPeriodicReceivesIndication@@YAKPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NET_BUFFER_LIST@@@Z
?ndisEventLogFromHandle@@YAPEAU_NDIS_EVENT_LOG@@PEAUNDIS_EVENT_LOG_HANDLE__@@@Z
?ndisEventLogHandleFromLog@@YAPEAUNDIS_EVENT_LOG_HANDLE__@@PEAU_NDIS_EVENT_LOG@@@Z
?ndisExpandDataPathStack@@YAJPEAU_NET_BUFFER_LIST@@KKKPEAXP6AXXZW4_NDIS_DATA_PATH_TYPE@@@Z
?ndisExpandStack@@YAJP6AXPEAX@Z0@Z
?ndisExpandStackTrace@@YAEPEAPEAU_NDIS_STACK_TRACE@@PEAU_RTL_DYNAMIC_HASH_TABLE_CONTEXT@@PEA_K@Z
?ndisFillEventLogEntry@@YAXPEAU_NDIS_EVENT_LOG@@KGPEAX@Z
?ndisFindAdjacentFilters@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_FILTER_LINK@@PEAPEAU_NDIS_FILTER_BLOCK@@2@Z
?ndisFindFirstReceiveFilterByOpen@@YAPEAU_NDIS_RECEIVE_FILTER_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@@Z
?ndisFindMinimumVersionDrivers@@YAXPEAU_NDIS_MINIPORT_BLOCK@@KK@Z
?ndisFindMiniportByPdo@@YAPEAU_NDIS_MINIPORT_BLOCK@@PEAU_DEVICE_OBJECT@@@Z
?ndisFreeMdl@@YAXPEAU_MDL@@@Z
?ndisFreePacketPoolHdr@@YAXPEAU_NDIS_PKT_POOL_HDR@@PEAU_NDIS_PKT_POOL@@@Z
?ndisFreeRefCountAuxiliaryMemory@@YAXPEAU_NDIS_REFCOUNT_BLOCK@@@Z
?ndisFreeRefCountStackChain@@YAXPEAU_NDIS_REFCOUNT_STACK_BLOCK@@@Z
?ndisFreeRefCountStacksInBlock@@YAXPEAU_NDIS_REFCOUNT_STACK_BLOCK@@@Z
?ndisGetBindLinkNameForTracing@@YAXPEAUNDIS_BIND_FILTER_LINK@@PEAUNDIS_PNPTRACE_LOCALS@@@Z
?ndisGetBindLinkNameForTracing@@YAXPEAUNDIS_BIND_PROTOCOL_LINK@@PEAUNDIS_PNPTRACE_LOCALS@@@Z
?ndisGetBindLinkNameForTracing@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_PNPTRACE_LOCALS@@@Z
?ndisGetMiniportIndicateList@@YAPEAU_NET_BUFFER_LIST@@PEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisGetNDKBlock@@YAPEAU_NDIS_NDK_BLOCK@@PEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisGetNthEntry@@YAPEAU_NDIS_EVENT_LOG_ENTRY@@PEAU_NDIS_EVENT_LOG@@K@Z
?ndisHandleLegacyBindIoctl@@YAXPEAU_UNICODE_STRING@@KPEBU1@@Z
?ndisIMVBusIsValidInput@@YAEPEAXPEAU_NDIS_VBUS_DEVICE_CHARACTERISTICS@@@Z
?ndisIPsecPktInfoToNBLInfo@@YAXPEAU_NDIS_IPSEC_PACKET_INFO@@W4_NDIS_XLATE_TYPE@@PEAU_NDIS_IPSEC_OFFLOAD_V1_NET_BUFFER_LIST_INFO@@@Z
?ndisIfStackTablePathExist@@YAEKKG@Z
?ndisIfUpdateLoopbackInterfaceOnNetwork@@YAXPEAU_NDIS_IF_NETWORK_BLOCK@@T_NET_LUID_LH@@@Z
?ndisInsertInWorkQueue@@YAXPEAU_NDIS_WORK_QUEUE@@PEAU_WORK_QUEUE_ITEM@@E@Z
?ndisInvokeMiniportSysPowerNotify@@YAXPEAU_NDIS_MINIPORT_BLOCK@@W4_SYSTEM_POWER_STATE@@1@Z
?ndisInvokeNextSendHandler@@YAXPEAU_NET_BUFFER_LIST@@KKPEAU_NDIS_OBJECT_HEADER@@PEAXP6AX20KK@Z@Z
?ndisIsCurrentNblContextBlockPreallocated@@YAEPEAU_NET_BUFFER_LIST@@@Z
?ndisIsMiniportVerified@@YAEPEAU_NDIS_M_DRIVER_BLOCK@@@Z
?ndisIsPossibleSmuggling@@YAET_NDIS_NBL_TRACKER_OWNER@@0PEAX@Z
?ndisIsSystemBooting@@YAEXZ
?ndisMAcquireStInLockWithSpinLock@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAE@Z
?ndisMCoIndicateReceiveNdisPacketToNdisPacket@@YAXPEAXPEAPEAU_NDIS_PACKET@@I@Z
?ndisMCoIndicateReceiveNdisPacketToNetBufferLists@@YAXPEAXPEAPEAU_NDIS_PACKET@@I@Z
?ndisMCoIndicateReceiveNetBufferListsToNdisPacket@@YAXPEAXPEAU_NET_BUFFER_LIST@@KK@Z
?ndisMCoIndicateReceiveNetBufferListsToNetBufferLists@@YAXPEAXPEAU_NET_BUFFER_LIST@@KK@Z
?ndisMCoSendCompleteToNdisPacket@@YAXHPEAXPEAU_NDIS_PACKET@@@Z
?ndisMCoSendCompleteToNetBufferLists@@YAXHPEAXPEAU_NDIS_PACKET@@@Z
?ndisMCoSendNetBufferListsCompleteToNdisPackets@@YAXPEAXPEAU_NET_BUFFER_LIST@@K@Z
?ndisMCoSendNetBufferListsCompleteToNetBufferLists@@YAXPEAXPEAU_NET_BUFFER_LIST@@K@Z
?ndisMDereferenceOpenLocked@@YAXPEAU_NDIS_OPEN_BLOCK@@W4_NDIS_OPEN_REFTAG@@@Z
?ndisMDereferenceOpenUnlocked@@YAXPEAU_NDIS_OPEN_BLOCK@@W4_NDIS_OPEN_REFTAG@@@Z
?ndisMDoesMiniportNeedCoNdisNdProxy@@YA_NPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisMEmitTraceRundown@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisMExitInitMode@@YAXPEAU_NDIS_MINIPORT_BLOCK@@W4CallRunMode@@@Z
?ndisMPauseMiniportInner@@YAXPEAU_NDIS_MINIPORT_BLOCK@@K@Z
?ndisMPeriodicPendingReceives@@YAEPEAXPEAU_NET_BUFFER_LIST@@KKKPEAPEAU1@@Z
?ndisMPeriodicReceivesResources@@YAEPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NET_BUFFER_LIST@@KKK@Z
?ndisMQueuedFinishClose@@YAXPEAX@Z
?ndisMQueuedPromoteMiniport@@YAXPEAX@Z
?ndisMRecalculateMiniportStackAfterBinding@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisMReferenceOpen@@YAXPEAU_NDIS_OPEN_BLOCK@@W4_NDIS_OPEN_REFTAG@@@Z
?ndisMReleaseStInLockAndSpinLock@@YAXPEAU_NDIS_MINIPORT_BLOCK@@E@Z
?ndisMRestartMiniport@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_RESTART_INFORMATION@@@Z
?ndisMRestartMiniportInner@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_RESTART_ATTRIBUTES@@@Z
?ndisMSendCompleteNetBufferListsToOpen@@YAXPEAU_NDIS_OPEN_BLOCK@@PEAU_NET_BUFFER_LIST@@KPEAUNDIS_PCW_CONTEXT@@@Z
?ndisMiniportDeviceReadyNotification@@YAJPEAX0@Z
?ndisNblTrackerDebugBreak@@YAXPEAU_NDIS_NBL_TRACKER@@@Z
?ndisNblTrackerDeleteTracker@@YAXPEAU_NDIS_NBL_TRACKER@@@Z
?ndisNblTrackerHandleFromNdisObjectHandle@@YAPEAUNDIS_NBL_TRACKER_HANDLE__@@PEAU1@@Z
?ndisNblTrackerPrintComponentNameToDebugger@@YAXPEAU_NDIS_NBL_TRACKER@@@Z
?ndisNblTrackerSetSqmFlag@@YAXPEAU_NDIS_NBL_TRACKER@@@Z
?ndisNblTrackerTransferOneNbl@@YAXPEAU_NET_BUFFER_LIST@@T_NDIS_NBL_TRACKER_OWNER@@PEAUNDIS_NBL_TRACKER_HANDLE__@@1PEAXPEA_J4@Z
?ndisNblTrackerUpdateOwnershipCount@@YAXT_NDIS_NBL_TRACKER_OWNER@@_JPEAE2@Z
?ndisNumDataBytesInNblChain@@YA_KPEAU_NET_BUFFER_LIST@@@Z
?ndisNumNblsInNblChain@@YAKPEAU_NET_BUFFER_LIST@@@Z
?ndisOidPostMiniportSetEncapsulation@@YAXPEAU_NDIS_REQ_TRACKER@@@Z
?ndisOidPostOpenSetEncapsulation@@YAXPEAU_NDIS_REQ_TRACKER@@@Z
?ndisOidPreMiniportSetEncapsulation@@YAEPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OID_REQUEST@@PEAH@Z
?ndisPauseFilter@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_FILTER_LINK@@@Z
?ndisPauseFilterInner@@YAXPEAU_NDIS_FILTER_BLOCK@@K@Z
?ndisPauseProtocol@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_PROTOCOL_LINK@@@Z
?ndisPauseProtocolInner@@YAXPEAU_NDIS_OPEN_BLOCK@@K@Z
?ndisPcwAddCounter@@YAJW4_NDIS_COUNTER_SET_ID@@PEAU_PCW_COUNTER_INFORMATION@@@Z
?ndisPcwAddEvent@@YAXPEAUNDIS_PCW_CONTEXT@@_K1@Z
?ndisPcwAddSinglePhysicalInstance@@YAJPEAU_PCW_BUFFER@@PEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisPcwCollectData@@YAJPEAU_PCW_BUFFER@@@Z
?ndisPcwCollectPhysicalData@@YAJPEAU_PCW_BUFFER@@@Z
?ndisPcwCollectSingleInstance@@YAJPEAU_PCW_BUFFER@@KPEBU_UNICODE_STRING@@PEA_K@Z
?ndisPcwEndCycleCounter@@YAXPEAUNDIS_PCW_CONTEXT@@K_K@Z
?ndisPcwEnumerateInstances@@YAJPEAU_PCW_BUFFER@@@Z
?ndisPcwEnumerateSingleInstance@@YAJPEAU_PCW_BUFFER@@PEAU_NDIS_MINIPORT_BLOCK@@K@Z
?ndisPcwGetCpu@@YAKPEAUNDIS_PCW_CONTEXT@@@Z
?ndisPcwGetInstanceName@@YAJPEAU_NDIS_MINIPORT_BLOCK@@KPEAU_UNICODE_STRING@@@Z
?ndisPcwGetMiniportDataBlock@@YAPEAU_NDIS_PCW_DATA_BLOCK@@PEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisPcwGetMiniportDataBlockInternal@@YAPEAU_NDIS_PCW_DATA_BLOCK@@PEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisPcwGetMiniportInstanceId@@YAKPEAU_NDIS_MINIPORT_BLOCK@@K@Z
?ndisPcwGetMiniportName@@YAPEBU_UNICODE_STRING@@PEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisPcwGetPerCpuDataForProcessor@@YAPEAU_NDIS_PCW_PER_CPU_DATA_BLOCK@@PEAU_NDIS_PCW_DATA_BLOCK@@K@Z
?ndisPcwGetReferencesForConsumer@@YAJW4_NDIS_COUNTER_SET_ID@@PEAU_PCW_COUNTER_INFORMATION@@PEAU_NDIS_PCW_CONSUMER_BLOCK@@@Z
?ndisPcwMatchInstance@@YAEPEAU_NDIS_MINIPORT_BLOCK@@KPEBU_UNICODE_STRING@@@Z
?ndisPcwMaybeDeleteDataBlock@@YAXPEAU_NDIS_PCW_DATA_BLOCK@@@Z
?ndisPcwNotifyIfBlockRemoval@@YAXPEAU_NDIS_IF_BLOCK@@@Z
?ndisPcwNotifyMiniportCreation@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisPcwQueryPcfMatchCount@@YA_KPEAU_NDIS_MINIPORT_BLOCK@@@Z
?ndisPcwReferenceMiniportDataBlock@@YAXPEAU_NDIS_PCW_DATA_BLOCK@@W4_NDIS_COUNTER_SET_ID@@_K@Z
?ndisPcwRemoveCounter@@YAJW4_NDIS_COUNTER_SET_ID@@PEAU_PCW_COUNTER_INFORMATION@@@Z
?ndisPcwStartCycleCounter@@YAXPEAUNDIS_PCW_CONTEXT@@K@Z
?ndisPcwUpdateMiniportDataBlock@@YAXPEAU_NDIS_PCW_DATA_BLOCK@@W4_NDIS_COUNTER_SET_ID@@_KJ@Z
?ndisPcwUpdatePhysicalMiniportCounters@@YAXPEAU_NDIS_MINIPORT_BLOCK@@_K@Z
?ndisPhysicalNicPcwProviderCallback@@YAJW4_PCW_CALLBACK_TYPE@@PEAT_PCW_CALLBACK_INFORMATION@@PEAX@Z
?ndisPnpInvokeTdi@@YAJW4_NDIS_TDI_VERB@@PEBU_UNICODE_STRING@@1PEAXK@Z
?ndisPnpRefresh@@YAXPEBU_NDIS_PNP_REFRESH_IN@@@Z
?ndisPostProcessRestartParametersAfterFilters@@YA_NPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_RESTART_INFORMATION@@@Z
?ndisPostProcessRestartParametersAfterMiniport@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_RESTART_INFORMATION@@@Z
?ndisPostProcessRestartParametersAfterProtocols@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_RESTART_INFORMATION@@@Z
?ndisPplLazyInitializeLookaside@@YAXPEAU_NDIS_NPAGED_LOOKASIDE_LIST@@0@Z
?ndisPrepForLowPower@@YAJPEAU_NDIS_MINIPORT_BLOCK@@W4_NDIS_DEVICE_POWER_STATE@@@Z
?ndisPublishSleepStudyCustomData@@YAXEPEBU_GUID@@PEBG_K@Z
?ndisPublishSleepStudyCustomDataCsTraffic@@YAXEPEBU_GUID@@PEAU_NDIS_MINIPORT_CS_TRAFFIC_STATS@@1@Z
?ndisQueueDpcWorkItem@@YAXPEAU_KDPC@@PEAX11E@Z
?ndisQueueFilterRestart@@YAXPEAU_NDIS_FILTER_BLOCK@@@Z
?ndisQueuePeriodicReceivesTimer@@YAXXZ
?ndisQueuePeriodicReceivesWorkItem@@YAXPEAU_NDIS_MINIPORT_BLOCK@@E@Z
?ndisQueueStackExpansionFallbackNbls@@YAXPEAU_NDIS_FILTER_BLOCK@@PEAU_NET_BUFFER_LIST@@E@Z
?ndisQueuedRestartFilter@@YAXPEAX@Z
?ndisRefCountHandleFromRefCountBlock@@YAPEAUNDIS_REFCOUNT_HANDLE__@@PEAU_NDIS_REFCOUNT_BLOCK@@@Z
?ndisReferenceWithTagStackTrace@@YAXPEAU_NDIS_REFCOUNT_WITH_STACK@@E@Z
?ndisRegisterProtocolDriverCommon@@YAXPEAU_NDIS_PROTOCOL_BLOCK@@@Z
?ndisReleaseReadLockSharedRefCnt@@YAXPEAU_NDIS_RW_LOCK@@@Z
?ndisRemoveFromNblQueueByCancelId@@YAPEAU_NET_BUFFER_LIST@@PEAU_NBL_QUEUE@@PEAX@Z
?ndisReportRefcountImbalance@@YAXPEAU_NDIS_REFCOUNT_BLOCK@@E@Z
?ndisResizeRefCountBlockTagged@@YAXPEAU_NDIS_REFCOUNT_BLOCK@@E@Z
?ndisRestartFilter@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_FILTER_LINK@@PEAUNDIS_RESTART_INFORMATION@@@Z
?ndisRestartFilterInner@@YAHPEAU_NDIS_FILTER_BLOCK@@PEAUNDIS_RESTART_INFORMATION@@@Z
?ndisRestartProtocol@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_PROTOCOL_LINK@@PEAUNDIS_RESTART_INFORMATION@@@Z
?ndisSetDevicePowerDownComplete@@YAJPEAU_DEVICE_OBJECT@@PEAU_IRP@@PEAX@Z
?ndisSetSystemPowerOnComplete@@YAJPEAU_DEVICE_OBJECT@@PEAU_IRP@@PEAX@Z
?ndisSourceHandleFromOwner@@YAPEAXT_NDIS_NBL_TRACKER_OWNER@@@Z
?ndisSqmSetRareFeatureFlag@@YAXW4NDIS_SQM_RARE_FEATURE_FLAG@@@Z
?ndisSumDataBlock@@YAXPEA_K0@Z
?ndisUnbindEachProtocolOpenOnMiniport@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAUNDIS_BIND_PROTOCOL_LINK@@@Z
?ndisUnbindProtocolOpen@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@@Z
?ndisUpdateMiniportCsTrafficStatistics@@YAXPEAU_NDIS_MINIPORT_BLOCK@@W4_NDIS_CS_TRAFFIC_STATS@@@Z
?ndisValidComponentId@@YAEW4_NDIS_PM_COMPONENT_ID@@@Z
?ndisValidateOffsetAndLength@@YA_NPEAU_IRP@@PEBU_NDIS_OFFSET_AND_LENGTH@@PEAPEAX@Z
?ndisValidateUnicodeStringFromOffsetAndLength@@YA_NPEAU_IRP@@PEBU_NDIS_OFFSET_AND_LENGTH@@PEAU_UNICODE_STRING@@@Z
?ndisWaitForDpcCompletion@@YAXPECJPECEPEAU_KEVENT@@@Z
?ndisWildCardStringMatch@@YAEPEBU_UNICODE_STRING@@0E@Z
?ndisWppExtendedCallback@@YAXEKE@Z
?ndisWppFastTraceMessage@@YAXPEBU_GUID@@GZZ
?ndisXlateSSResume@@YA?AW4_NDIS_USER_RESUME_REASON@@T_NDIS_SS_RESUME_REASON@@@Z
?reserve@?$KArray@E@Rtl@@QEAA_N_K@Z
?reserve@?$KArray@PEAX@Rtl@@QEAA_N_K@Z
?reserve@?$KArray@V?$KPtr@UNDIS_BIND_FILTER_LINK@@U?$KDeletePtr@UNDIS_BIND_FILTER_LINK@@@@@@@Rtl@@QEAA_N_K@Z
?reserve@?$KArray@V?$KPtr@UNDIS_BIND_PROTOCOL_LINK@@U?$KDeletePtr@UNDIS_BIND_PROTOCOL_LINK@@@@@@@Rtl@@QEAA_N_K@Z
?reserve@?$KArray@V?$KRef@UNDIS_BIND_FILTER_DRIVER@@@@@Rtl@@QEAA_N_K@Z
?reserve@?$KArray@V?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@@Rtl@@QEAA_N_K@Z
?reset@?$KPtr@EU?$KDeleteArray@E@@@@QEAAXPEAE@Z
?reset@?$KPtr@UKString@Rtl@@U?$KDeletePtr@UKString@Rtl@@@@@@QEAAXPEAUKString@Rtl@@@Z
?reset@?$KRef@UNDIS_BIND_FILTER_DRIVER@@@@AEAAXPEAVKRefHolder@1@@Z
?reset@?$KRef@UNDIS_BIND_PROTOCOL_DRIVER@@@@AEAAXPEAVKRefHolder@1@@Z
?resize@?$KArray@PEAX@Rtl@@QEAA_N_K@Z
AddAces
COMPARTMENTBLOCK_DECREMENT_REF
CmRegUtilCreateUcKey
CmRegUtilCreateWstrKey
CmRegUtilOpenExistingUcKey
CmRegUtilOpenExistingWstrKey
CmRegUtilUcValueGetDword
CmRegUtilUcValueGetFullBuffer
CmRegUtilUcValueSetUcString
CmRegUtilWstrValueGetDword
CmRegUtilWstrValueSetWstrString
CreateDeviceDriverSecurityDescriptor
DisableMagicPacketKeyword
DriverEntry
Duplicate802_11AttachAttributes
Duplicate802_11AttachAttributesCommon
EthCreateFilter
EthDeleteFilter
EthDeleteFilterOpenAdapter
EthFilterDprIndicateReceive
EthFilterDprIndicateReceiveComplete
EthIndicateReceive
EthInitializeFilter
EthQueryGlobalFilterAddresses
EthQueryOpenFilterAddresses
ExAllocateFromNPagedLookasideList
ExFreeToNPagedLookasideList
FindExportedRoutineByName
GetMiniportFromReqTracker
GsDriverEntry
IFBLOCK_DECREMENT_REF
IFBLOCK_INCREMENT_REF
IoDevObjCreateDeviceSecure
IopDevObjApplyPostCreationSettings
IsOidRequestDirectOid
McGenControlCallbackV2
McGenEventRegister
Microsoft_Windows_Networking_Correlation_EtwEnableCallback
NDIS_BUFFER_TO_SPAN_PAGES
NDIS_NDK_PCW_NUM_COUNTERS_SET_IN_MASK
NETWORKBLOCK_DECREMENT_REF
NdisAcquireRWLockRead
NdisAcquireRWLockWrite
NdisAcquireReadWriteLock
NdisAcquireSpinLock
NdisActiveGroupCount
NdisAdjustBufferLength
NdisAdjustNetBufferCurrentMdl
NdisAdvanceNetBufferDataStart
NdisAdvanceNetBufferListDataStart
NdisAllocateBuffer
NdisAllocateBufferPool
NdisAllocateCloneNetBufferList
NdisAllocateCloneOidRequest
NdisAllocateFragmentNetBufferList
NdisAllocateGenericObject
NdisAllocateIoWorkItem
NdisAllocateMdl
NdisAllocateMemory
NdisAllocateMemoryWithTag
NdisAllocateMemoryWithTagPriority
NdisAllocateNetBuffer
NdisAllocateNetBufferAndNetBufferList
NdisAllocateNetBufferList
NdisAllocateNetBufferListContext
NdisAllocateNetBufferListPool
NdisAllocateNetBufferMdlAndData
NdisAllocateNetBufferPool
NdisAllocatePacket
NdisAllocatePacketPool
NdisAllocatePacketPoolEx
NdisAllocateRWLock
NdisAllocateReassembledNetBufferList
NdisAllocateSharedMemory
NdisAllocateSpinLockExported
NdisAllocateTimerObject
NdisAnsiStringToUnicodeString
NdisBufferLength
NdisBufferVirtualAddress
NdisBuildScatterGatherList
NdisCancelDirectOidRequest
NdisCancelOidRequest
NdisCancelSendNetBufferLists
NdisCancelSendPackets
NdisCancelTimer
NdisCancelTimerObject
NdisClAddParty
NdisClCloseAddressFamily
NdisClCloseCall
NdisClDeregisterSap
NdisClDropParty
NdisClGetProtocolVcContextFromTapiCallId
NdisClIncomingCallComplete
NdisClMakeCall
NdisClModifyCallQoS
NdisClNotifyCloseAddressFamilyComplete
NdisClOpenAddressFamily
NdisClOpenAddressFamilyEx
NdisClRegisterSap
NdisCloseAdapter
NdisCloseAdapterEx
NdisCloseConfiguration
NdisCloseFile
NdisCloseNDKAdapter
NdisCmActivateVc
NdisCmAddPartyComplete
NdisCmCloseAddressFamilyComplete
NdisCmCloseCallComplete
NdisCmDeactivateVc
NdisCmDeregisterSapComplete
NdisCmDispatchCallConnected
NdisCmDispatchIncomingCall
NdisCmDispatchIncomingCallQoSChange
NdisCmDispatchIncomingCloseCall
NdisCmDispatchIncomingDropParty
NdisCmDropPartyComplete
NdisCmMakeCallComplete
NdisCmModifyCallQoSComplete
NdisCmNotifyCloseAddressFamily
NdisCmOpenAddressFamilyComplete
NdisCmRegisterAddressFamily
NdisCmRegisterAddressFamilyEx
NdisCmRegisterSapComplete
NdisCoAssignInstanceName
NdisCoCreateVc
NdisCoDeleteVc
NdisCoGetTapiCallId
NdisCoOidRequest
NdisCoOidRequestComplete
NdisCoRequest
NdisCoRequestComplete
NdisCoSendNetBufferLists
NdisCoSendPackets
NdisCompleteBindAdapter
NdisCompleteBindAdapterEx
NdisCompleteDmaTransfer
NdisCompleteNetPnPEvent
NdisCompletePnPEvent
NdisCompleteUnbindAdapter
NdisCompleteUnbindAdapterEx
NdisConvertNdisStatusToNtStatus
NdisConvertNtStatusToNdisStatus
NdisCopyBuffer
NdisCopyFromNetBufferToNetBuffer
NdisCopyFromPacketToPacket
NdisCopyFromPacketToPacketSafe
NdisCopyReceiveNetBufferListInfo
NdisCopySendNetBufferListInfo
NdisCurrentGroupAndProcessor
NdisCurrentProcessorIndexExported
NdisDeregisterDeviceEx
NdisDeregisterProtocol
NdisDeregisterProtocolDriver
NdisDeregisterTdiCallBack
NdisDirectOidRequest
NdisDllInitialize
NdisDprAcquireReadWriteLock
NdisDprAcquireSpinLock
NdisDprReleaseReadWriteLock
NdisDprReleaseSpinLock
NdisEnumerateFilterModules
NdisFCancelDirectOidRequest
NdisFCancelOidRequest
NdisFCancelSendNetBufferLists
NdisFDeregisterFilterDriver
NdisFDevicePnPEventNotify
NdisFDirectOidRequest
NdisFDirectOidRequestComplete
NdisFGetOptionalSwitchHandlers
NdisFIndicateReceiveNetBufferLists
NdisFIndicateStatus
NdisFNetPnPEvent
NdisFOidRequest
NdisFOidRequestComplete
NdisFPauseComplete
NdisFRegisterFilterDriver
NdisFRestartComplete
NdisFRestartFilter
NdisFReturnNetBufferLists
NdisFSendNetBufferLists
NdisFSendNetBufferListsComplete
NdisFSetAttributes
NdisFreeBuffer
NdisFreeBufferPool
NdisFreeCloneNetBufferList
NdisFreeCloneOidRequest
NdisFreeFragmentNetBufferList
NdisFreeGenericObject
NdisFreeIoWorkItem
NdisFreeMdl
NdisFreeMemory
NdisFreeMemoryWithTag
NdisFreeMemoryWithTagPriority
NdisFreeNetBuffer
NdisFreeNetBufferList
NdisFreeNetBufferListContext
NdisFreeNetBufferListPool
NdisFreeNetBufferPool
NdisFreePacket
NdisFreePacketPool
NdisFreeRWLock
NdisFreeReassembledNetBufferList
NdisFreeScatterGatherList
NdisFreeSharedMemory
NdisFreeSpinLockExported
NdisFreeTimerObject
NdisGeneratePartialCancelId
NdisGetBufferPhysicalArraySize
NdisGetCurrentProcessorCounts
NdisGetCurrentProcessorCpuUsage
NdisGetCurrentSystemTime
NdisGetDataBuffer
NdisGetDeviceReservedExtension
NdisGetDriverHandle
NdisGetFirstBufferFromPacket
NdisGetFirstBufferFromPacketSafe
NdisGetHypervisorInfo
NdisGetNetBufferListProtocolId
NdisGetPacketCancelId
NdisGetPacketFromNetBufferList
NdisGetPoolFromNetBuffer
NdisGetPoolFromNetBufferList
NdisGetPoolFromPacket
NdisGetProcessorInformation
NdisGetProcessorInformationEx
NdisGetReceivedPacket
NdisGetRoutineAddress
NdisGetRssProcessorInformation
NdisGetSessionCompartmentId
NdisGetSessionToCompartmentMappingEpochAndZero
NdisGetSharedDataAlignment
NdisGetSystemUpTime
NdisGetSystemUpTimeEx
NdisGetThreadObjectCompartmentId
NdisGetVersion
NdisGroupActiveProcessorCount
NdisGroupActiveProcessorMask
NdisGroupMaxProcessorCount
NdisIMAssociateMiniport
NdisIMCancelInitializeDeviceInstance
NdisIMCopySendCompletePerPacketInfo
NdisIMCopySendPerPacketInfo
NdisIMDeInitializeDeviceInstance
NdisIMDeregisterLayeredMiniport
NdisIMGetBindingContext
NdisIMGetCurrentPacketStack
NdisIMGetDeviceContext
NdisIMInitializeDeviceInstance
NdisIMInitializeDeviceInstanceEx
NdisIMNotifyPnPEvent
NdisIMQueueMiniportCallback
NdisIMRegisterLayeredMiniport
NdisIMRevertBack
NdisIMSwitchToMiniport
NdisIMVBusDeviceAdd
NdisIMVBusDeviceRemove
NdisIMVBusDeviceUpdate
NdisIfAddIfStackEntry
NdisIfAllocateNetLuidIndex
NdisIfAllocateNetLuidIndexEx
NdisIfDeleteIfStackEntry
NdisIfDeregisterInterface
NdisIfDeregisterProvider
NdisIfFreeNetLuidIndex
NdisIfGetInterfaceIndexFromNetLuid
NdisIfGetNetLuidFromInterfaceIndex
NdisIfQueryBindingIfIndex
NdisIfRegisterInterface
NdisIfRegisterProvider
NdisImmediateReadPciSlotInformation
NdisImmediateReadPortUchar
NdisImmediateReadPortUlong
NdisImmediateReadPortUshort
NdisImmediateReadSharedMemory
NdisImmediateWritePciSlotInformation
NdisImmediateWritePortUchar
NdisImmediateWritePortUlong
NdisImmediateWritePortUshort
NdisImmediateWriteSharedMemory
NdisInitializeEvent
NdisInitializeReadWriteLock
NdisInitializeString
NdisInitializeTimer
NdisInitializeWrapper
NdisInitiateOffload
NdisInterlockedAddUlong
NdisInterlockedDecrement
NdisInterlockedIncrement
NdisInterlockedInsertHeadList
NdisInterlockedInsertTailList
NdisInterlockedPopEntryList
NdisInterlockedPushEntryList
NdisInterlockedRemoveHeadList
NdisInvalidateOffload
NdisIsStatusIndicationCloneable
NdisMAllocateMapRegisters
NdisMAllocateNetBufferSGList
NdisMAllocatePort
NdisMAllocateSharedMemory
NdisMAllocateSharedMemoryAsync
NdisMCancelTimer
NdisMCloseLog
NdisMCmActivateVc
NdisMCmCreateVc
NdisMCmDeactivateVc
NdisMCmDeleteVc
NdisMCmOidRequest
NdisMCmRegisterAddressFamily
NdisMCmRegisterAddressFamilyEx
NdisMCmRequest
NdisMCoActivateVcComplete
NdisMCoDeactivateVcComplete
NdisMCoIndicateReceiveNetBufferLists
NdisMCoIndicateReceivePacket
NdisMCoIndicateStatus
NdisMCoIndicateStatusEx
NdisMCoOidRequestComplete
NdisMCoReceiveComplete
NdisMCoRequestComplete
NdisMCoSendComplete
NdisMCoSendNetBufferListsComplete
NdisMCompleteBufferPhysicalMapping
NdisMConfigMSIXTableEntry
NdisMCreateLog
NdisMDeregisterAdapterShutdownHandler
NdisMDeregisterDevice
NdisMDeregisterDmaChannel
NdisMDeregisterInterrupt
NdisMDeregisterInterruptEx
NdisMDeregisterIoPortRange
NdisMDeregisterMiniportDriver
NdisMDeregisterScatterGatherDma
NdisMDirectOidRequestComplete
NdisMEnableVirtualization
NdisMFlushLog
NdisMFreeMapRegisters
NdisMFreeNetBufferSGList
NdisMFreePort
NdisMFreeSharedMemory
NdisMGetBusData
NdisMGetDeviceProperty
NdisMGetDmaAlignment
NdisMGetMiniportInitAttributes
NdisMGetOffloadHandlers
NdisMGetVirtualDeviceLocation
NdisMGetVirtualFunctionBusData
NdisMGetVirtualFunctionLocation
NdisMIdleNotificationComplete
NdisMIdleNotificationCompleteEx
NdisMIdleNotificationConfirm
NdisMIndicateReceiveNetBufferLists
NdisMIndicateStatus
NdisMIndicateStatusComplete
NdisMIndicateStatusEx
NdisMInitializeScatterGatherDma
NdisMInitializeTimer
NdisMInitiateOffloadComplete
NdisMInvalidateConfigBlock
NdisMInvalidateOffloadComplete
NdisMMapIoSpace
NdisMNetPnPEvent
NdisMOffloadEventIndicate
NdisMOidRequestComplete
NdisMPauseComplete
NdisMPciAssignResources
NdisMPromoteMiniport
NdisMQueryAdapterInstanceName
NdisMQueryAdapterResources
NdisMQueryInformationComplete
NdisMQueryOffloadStateComplete
NdisMQueryProbedBars
NdisMQueueDpc
NdisMQueueDpcEx
NdisMReadConfigBlock
NdisMReadDmaCounter
NdisMReenumerateFailedAdapter
NdisMRegisterAdapterShutdownHandler
NdisMRegisterDevice
NdisMRegisterDmaChannel
NdisMRegisterInterrupt
NdisMRegisterInterruptEx
NdisMRegisterIoPortRange
NdisMRegisterMiniport
NdisMRegisterMiniportDriver
NdisMRegisterScatterGatherDma
NdisMRegisterUnloadHandler
NdisMRemoveMiniport
NdisMRemoveMiniportInternal
NdisMRequestDpc
NdisMResetComplete
NdisMResetMiniport
NdisMRestartComplete
NdisMSendComplete
NdisMSendNetBufferListsComplete
NdisMSendResourcesAvailable
NdisMSetAttributes
NdisMSetAttributesEx
NdisMSetBusData
NdisMSetInformationComplete
NdisMSetMiniportAttributes
NdisMSetMiniportSecondary
NdisMSetPeriodicTimer
NdisMSetTimer
NdisMSetVirtualFunctionBusData
NdisMSleep
NdisMStartBufferPhysicalMapping
NdisMSynchronizeWithInterrupt
NdisMSynchronizeWithInterruptEx
NdisMTerminateOffloadComplete
NdisMTransferDataComplete
NdisMUnmapIoSpace
NdisMUpdateOffloadComplete
NdisMWanIndicateReceive
NdisMWanIndicateReceiveComplete
NdisMWanSendComplete
NdisMWriteConfigBlock
NdisMWriteLogData
NdisMapFile
NdisMatchPdoWithPacket
NdisMaxGroupCount
NdisNblTrackerDeregisterComponent
NdisNblTrackerRecordEvent
NdisNblTrackerRegisterComponent
NdisNblTrackerTransferOwnership
NdisOffloadTcpDisconnect
NdisOffloadTcpForward
NdisOffloadTcpReceive
NdisOffloadTcpReceiveReturn
NdisOffloadTcpSend
NdisOidRequest
NdisOpenAdapter
NdisOpenAdapterEx
NdisOpenConfiguration
NdisOpenConfigurationEx
NdisOpenConfigurationKeyByIndex
NdisOpenConfigurationKeyByName
NdisOpenFile
NdisOpenNDKAdapter
NdisOpenProtocolConfiguration
NdisOverrideBusNumber
NdisPacketPoolUsage
NdisPacketSize
NdisProcessorIndexToNumber
NdisProcessorNumberToIndex
NdisQueryAdapterInstanceName
NdisQueryBindInstanceName
NdisQueryBuffer
NdisQueryBufferOffset
NdisQueryBufferSafe
NdisQueryMapRegisterCount
NdisQueryNetBufferPhysicalCount
NdisQueryOffloadState
NdisQueryPendingIOCount
NdisQueueIoWorkItem
NdisReEnumerateProtocolBindings
NdisReadConfiguration
NdisReadEisaSlotInformation
NdisReadEisaSlotInformationEx
NdisReadMcaPosInformation
NdisReadNetworkAddress
NdisReadPciSlotInformation
NdisReadPcmciaAttributeMemory
NdisRegisterDeviceEx
NdisRegisterProtocol
NdisRegisterProtocolDriver
NdisRegisterTdiCallBack
NdisReleaseNicActive
NdisReleaseRWLock
NdisReleaseReadWriteLock
NdisReleaseSpinLock
NdisRequest
NdisReset
NdisResetEvent
NdisRetreatNetBufferDataStart
NdisRetreatNetBufferListDataStart
NdisReturnNetBufferLists
NdisReturnPackets
NdisScheduleWorkItem
NdisSend
NdisSendNetBufferLists
NdisSendPackets
NdisSetAoAcOptions
NdisSetCoalescableTimerObject
NdisSetEvent
NdisSetOptionalHandlers
NdisSetPacketCancelId
NdisSetPacketPoolProtocolId
NdisSetPacketStatus
NdisSetPeriodicTimer
NdisSetProtocolFilter
NdisSetSessionCompartmentId
NdisSetThreadObjectCompartmentId
NdisSetTimer
NdisSetTimerEx
NdisSetTimerObject
NdisSetupDmaTransfer
NdisSystemActiveProcessorCount
NdisSystemProcessorCount
NdisTerminateOffload
NdisTerminateWrapper
NdisTransferData
NdisTryAcquireNicActive
NdisUnbindAdapter
NdisUnchainBufferAtBack
NdisUnchainBufferAtFront
NdisUnicodeStringToAnsiString
NdisUnmapFile
NdisUpcaseUnicodeString
NdisUpdateOffload
NdisUpdateSharedMemory
NdisWaitEvent
NdisWriteConfiguration
NdisWriteErrorLogEntry
NdisWriteEventLogEntry
NdisWritePciSlotInformation
NdisWritePcmciaAttributeMemory
PiRegStateOpenClassKey
PiRegStateReadStackCreationSettingsFromKey
PpRegStateReadCreateClassCreationSettings
PpRegStateUpdateStackCreationSettings
PplCreateLookasideList
PplDestroyLookasideList
PplGenericAllocateFunction
PplGenericFreeFunction
PplHotAddProcCompleteNotify
PplHotAddProcStartNotify
PplpCreateOneLookasideList
PplpFreeOneLookasideList
PplpLazyInitializeLookasideList
PrivateULongMult
SeSddlSecurityDescriptorFromSDDL
SeUtilSecurityInfoFromSecurityDescriptor
SepSddlAddAceToAcl
SepSddlDaclFromSDDLString
SepSddlGetAclForString
SepSddlGetSidForString
SepSddlLookupAccessMaskInTable
SepSddlParseWideStringUlong
SepSddlSecurityDescriptorFromSDDLString
TemplateEventDescriptor
Template_cjqzr2jx
Template_j
Template_jcqjzzz
Template_jqx
Template_jqxb
Template_jqxjqxqq
Template_jqxptq
Template_jqxq
Template_jqxqq
Template_jqxqqq
Template_jqxqqt
Template_jqxtpp
Template_jqxz
Template_jqxzq
Template_jqxzqq
Template_jqxzqqQR5
Template_pp
Template_q
Template_qq
Template_qqq
Template_qqqqqqqq
Template_qqx
Template_qx
Template_qxq
Template_qxqqq
Template_qxxq
Template_qxzzxxxxxx
Template_qzz
Template_x
Template_xq
Template_xqq
Template_xqqq
Template_xqx
Template_z
Template_zq
WPP_SF_
WPP_SF_D
WPP_SF_DD
WPP_SF_DDD
WPP_SF_DDDDD
WPP_SF_DDDDDDDDDDD
WPP_SF_DDL
WPP_SF_DDLc
WPP_SF_DDLcD
WPP_SF_DDLqdL
WPP_SF_DL
WPP_SF_DZq
WPP_SF_Ddd
WPP_SF_DqL
WPP_SF_DqLL
WPP_SF_DqZ
WPP_SF_Dql
WPP_SF_DqlD
WPP_SF_DqqZZ
WPP_SF_L
WPP_SF_LDD
WPP_SF_LL
WPP_SF_LZq
WPP_SF_Ld
WPP_SF_Ll
WPP_SF_Llq
WPP_SF_Lq
WPP_SF_LqDLqD
WPP_SF_LqL
WPP_SF_LqZ
WPP_SF_Lqq
WPP_SF_LqqZZ
WPP_SF_S
WPP_SF_Sd
WPP_SF_SqZ
WPP_SF_Sx
WPP_SF_Z
WPP_SF_ZL
WPP_SF_ZLqL
WPP_SF_ZZ
WPP_SF_ZZL
WPP_SF_Zd
WPP_SF_Zq
WPP_SF_ZqD
WPP_SF_Zqq
WPP_SF__guid_D
WPP_SF__guid_Dq
WPP_SF__guid_DqD
WPP_SF_d
WPP_SF_dD
WPP_SF_dL
WPP_SF_dd
WPP_SF_ddLLL
WPP_SF_dl
WPP_SF_dlL
WPP_SF_dllL
WPP_SF_dq
WPP_SF_dqZ
WPP_SF_l
WPP_SF_ll
WPP_SF_llL
WPP_SF_q
WPP_SF_qD
WPP_SF_qDD
WPP_SF_qDDDDDD
WPP_SF_qDDLq
WPP_SF_qDL
WPP_SF_qDLLq
WPP_SF_qDdZ
WPP_SF_qDq
WPP_SF_qDqD
WPP_SF_qDqL
WPP_SF_qL
WPP_SF_qLDDDDDDDDDD
WPP_SF_qLDDDDDDDDDDD
WPP_SF_qLL
WPP_SF_qLLDDDDDDDDDD
WPP_SF_qLLL
WPP_SF_qLLLL
WPP_SF_qLLq
WPP_SF_qLLqD
WPP_SF_qLLqL
WPP_SF_qLd
WPP_SF_qLl
WPP_SF_qLq
WPP_SF_qLqL
WPP_SF_qSD
WPP_SF_qZ
WPP_SF_qZD
WPP_SF_qZL
WPP_SF_qZLLL
WPP_SF_qZZ
WPP_SF_qZddD
WPP_SF_qZl
WPP_SF_qZq
WPP_SF_qd
WPP_SF_qdD
WPP_SF_qdDd
WPP_SF_qdL
WPP_SF_ql
WPP_SF_qlL
WPP_SF_qllq
WPP_SF_qq
WPP_SF_qqD
WPP_SF_qqDD
WPP_SF_qqDDD
WPP_SF_qqDL
WPP_SF_qqDd
WPP_SF_qqDq
WPP_SF_qqL
WPP_SF_qqLD
WPP_SF_qqZ
WPP_SF_qqZZ
WPP_SF_qqZddZ
WPP_SF_qqZddZD
WPP_SF_qqd
WPP_SF_qqil
WPP_SF_qqill
WPP_SF_qql
WPP_SF_qqq
WPP_SF_qqqD
WPP_SF_qqqDD
WPP_SF_qqqL
WPP_SF_qqqd
WPP_SF_qqqq
WPP_SF_qqqqD
WPP_SF_qqqqDL
WPP_SF_qqqqq
WPP_SF_qqqqqL
WPP_SF_qs
WPP_SF_qsD
WPP_SF_sL
WPP_SF_sZZ
WdmlibInit
WdmlibIoCreateDeviceSecure
WdmlibRtlInitUnicodeStringEx
WppClassicProviderCallback
WppInitKm
WppLoadTracingSupport
WppTraceCallback
XFilterAdjust
XNoteFilterOpenAdapter
XRemoveBindingFromLists
XSetupFrameTypeInFilter
XlateReceivePacketStats
__C_specific_handler
__GSHandlerCheck
__GSHandlerCheckCommon
__report_gsfailure
__report_rangecheckfailure
__security_check_cookie
__security_init_cookie
_guard_check_icall_nop
ethAddOneOpenMulticastAddress
ethAllocateOpenMulticastBuffer
ethDeleteOneOpenMulticastAddress
ethFilterDprIndicateReceivePacket
ethFilterReceivePacketStats
ethFindMulticast
memcmp
memcpy
memmove
memset
ndis5InterruptDpc
ndis5QueuedMiniportDpcWorkItem
ndis6DummyReceiveComplete
ndisAcquireMiniportPnPEventLock
ndisAcquireReadWriteLockX
ndisAddDevice
ndisAddMediaTypeToArray
ndisAddReceiveQueueToList
ndisAddWoLMagicPacket
ndisAllocOrFreeIterativeDataPathTrackerIfNeeded
ndisAllocateConfigurationString
ndisAllocateDefaultQueue
ndisAllocateEventLog
ndisAllocateOpenBlock
ndisAllocateOpenOffload
ndisAllocatePerProcessorSlot
ndisAllocateReceiveQueue
ndisAllocateRefCount
ndisAllocationExecutionRoutine
ndisAoAcActiveRefIncrement
ndisAoAcActiveRefSubtract
ndisAoAcCleanup
ndisAoAcClearStop
ndisAoAcCompleteQueuedIrps
ndisAoAcEnableRemoteWake
ndisAoAcIdleRequestConfirm
ndisAoAcInitialize
ndisAoAcPmInitTempRef
ndisAoAcRefMiniportForIoctl
ndisAoAcScheduleWakeWorkItem
ndisAoAcStart
ndisAoAcStop
ndisAoAcTempRefWorkItem
ndisAoAcWakeWorkItem
ndisBindUnbindPeriodicReceives
ndisBootDriverReinit
ndisBugCheckEx
ndisBugcheckHandler
ndisBuildDeviceAcl
ndisCalculateIdealNblTrackerHistoryBufferSize
ndisCalculateRssProcessorCount
ndisCancelDequeuedDirectOidRequests
ndisCancelIdleRequest
ndisCancelIdleRequestSync
ndisCancelInitModeTimeoutTimer
ndisCancelLogIrp
ndisCancelMediaDisconnectTimer
ndisCancelOidRequestInternal
ndisCancelOidRequestOnFilter
ndisCancelOidRequestOnMiniport
ndisCancelWaitWake
ndisCancelWakeUpDpcTimer
ndisCaptureStackTrace
ndisCheckAccess
ndisCheckForHangSupported
ndisCheckIfTypeMismatch
ndisCheckMiniportWakeUpCapable
ndisCleanUpForProtocol
ndisClearBusy
ndisClearReceiveFilter
ndisClearReceiveFiltersForProtocol
ndisClonePMPatternList
ndisCloseIrpHandler
ndisCloseRef
ndisCloseTimeInterval
ndisCloseULongRef
ndisCmCleanupDpcRoutine
ndisCmCleanupWorkRoutine
ndisCmInitialize
ndisCoCompleteOidRequestToRequest
ndisCoIndicateStatusInternal
ndisCoOidRequestToRequest
ndisCompareGuid
ndisComparePMCapabilities
ndisComparePMProtocolOffloads
ndisCompareProcNumInit
ndisCompareWoLPatterns
ndisCompleteLegacyRequest
ndisCompleteOidRequestToRequest
ndisCompletionRoutine
ndisConfigurePeriodicReceives
ndisConvertOffloadValueToString
ndisConvertPMCapabilitiesToPnp
ndisConvertPnpCapabilitiesToPM
ndisConvertWakeUpEnableToPMConfig
ndisCopyNBLInfoToPacket
ndisCopyNdisOffload
ndisCopyPacketInfoToNBL
ndisCpuHotAddHandler
ndisCreateAcl
ndisCreateAdapterInstanceName
ndisCreateDWORDStreamEntry
ndisCreateFilterAdapterRegistry
ndisCreateFilterDriverRegistry
ndisCreateFilterInstanceRegistry
ndisCreateGenericSD
ndisCreateIrpHandler
ndisCreateNdisSupportedOidList
ndisCreateNotifyQueue
ndisCreatePMAddRemoveWorkItem
ndisCreatePMPacketPattern
ndisCreatePMProtocolOffloadEntry
ndisCreatePMRejectWorkItem
ndisCreateReceiveWorkerThreadPool
ndisCreateSecurityDescriptor
ndisCreateSecurityDescriptorEx
ndisCreateStringStreamEntry
ndisCreateThread
ndisCreateWakeUpPatternEntry
ndisCreateWoLPatternEntry
ndisCsStateChange
ndisDataPathExpandStackCallback
ndisDeQueueMiniportOnDriver
ndisDeQueueOpenOnMiniport
ndisDeQueueOpenOnProtocol
ndisDeinitializeZeroBasedRef
ndisDeletePatternEntry
ndisDeliverNetPnPEventSynchronously
ndisDequeueDirectOidsByRequestId
ndisDereferenceAf
ndisDereferenceAfNotification
ndisDereferenceDmaAdapter
ndisDereferenceDriver
ndisDereferenceFilter
ndisDereferenceFilterDriver
ndisDereferenceMiniport
ndisDereferenceMiniportForNsi
ndisDereferenceMiniportRef
ndisDereferencePackage
ndisDereferenceProtocol
ndisDereferenceReceiveFilter
ndisDereferenceReceiveQueue
ndisDereferenceRef
ndisDereferenceSap
ndisDereferenceVcPtr
ndisDereferenceWithTag
ndisDeviceControlIrpHandler
ndisDeviceInternalIrpDispatch
ndisDevicePnPEventNotifyFiltersAndAllTransports
ndisDevicePnPEventNotifyMiniport
ndisDevicePowerDown
ndisDevicePowerOn
ndisDisableRsc
ndisDispatchIoWorkItem
ndisDispatchRequest
ndisDmaAddCpuNotify
ndisDmaExecutionRoutine
ndisDoCancelDirectOidRequest
ndisDoDirectOidRequest
ndisDoLoopbackNetBufferList
ndisDoOidRequests
ndisDoesSystemSupportSriov
ndisDriverReinit
ndisDriverSystemDispatch
ndisDummyIrpHandler
ndisEmptyPeriodicReceivesQueue
ndisEnablePMParamForPattern
ndisEnablePMParamForProtocolOffload
ndisEnableWppTracingCallback
ndisEndMapping
ndisEnumerateFilterInstances
ndisEnumerateInterfaces
ndisEnumerateInterfaces32
ndisEnumeratePorts
ndisEtwRegisterGuids
ndisEventEntryCount
ndisFAllocateFilterOffload
ndisFCancelDirectOidRequestInternal
ndisFCancelOidRequestInternal
ndisFDevicePnPEventNotifyInternal
ndisFDirectOidRequestCompleteInternal
ndisFDoDirectOidRequestInternal
ndisFDoLoopbackNetBufferList
ndisFDoOidRequest
ndisFDoOidRequestInternal
ndisFForwardNetDevicePnPEvent
ndisFForwardNetPnPEventToFilter
ndisFIndicateOffloadChange
ndisFIndicateStatusInternal
ndisFIndicateStatusToFilter
ndisFIndicateStatusWrapper
ndisFInvokeAttach
ndisFInvokeCancelOidRequest
ndisFInvokeDetach
ndisFInvokeDevicePnPEventNotify
ndisFInvokeDirectOidRequest
ndisFInvokeDirectOidRequestComplete
ndisFInvokeNetPnPEvent
ndisFInvokePause
ndisFInvokeRestart
ndisFInvokeSetFilterModuleOptions
ndisFInvokeSetOptions
ndisFInvokeStatus
ndisFIsLoopbackNetBuffer
ndisFLoopbackNetBufferLists
ndisFNetPnPEventInternal
ndisFNotifyDetach
ndisFOidRequestCompleteInternal
ndisFQueueOidRequest
ndisFSetRestartAttributes
ndisFailedAdapterLiveDumpCallback
ndisFakeFilterReceiveHandler
ndisFakeFilterSendHandler
ndisFakeMiniportCancelSendPackets
ndisFillOffloadCapsInTasks
ndisFilterAttachCleanUp
ndisFilterCancelSendNetBufferLists
ndisFilterCancelSendNetBufferListsInternal
ndisFilterFakeCancelSendNetBufferLists
ndisFilterIndicatePMCapabilities
ndisFilterIndicatePMOffloadReject
ndisFilterIndicateReceiveNetBufferLists
ndisFilterIndicateWoLPatternReject
ndisFilterSendNetBufferLists
ndisFilterXStateSetFlag
ndisFindMiniportOnGlobalList
ndisFindPatternEntry
ndisFindPortByPortNumber
ndisFindReceiveFilterByFilterId
ndisFindReceiveQueueByQueueId
ndisFindRootDevice
ndisFreeConvertedPacket
ndisFreeNblToNPagedPool
ndisFreeOpenBlock
ndisFreePacketPool
ndisFreePaddedMdl
ndisFreePerProcessorSlot
ndisFreePeriodicReceives
ndisFreeReceiveQueue
ndisFreeRefCount
ndisFreeSharedMemory
ndisFreeToNPagedPool
ndisGenerateCorrelationIds
ndisGenerateNetBufferListCorrelationIds
ndisGetAdapterHardwareInfo
ndisGetAdapterRssInfo
ndisGetAnyProcInsideNode
ndisGetCombinedPMConfig
ndisGetDpcWatchdogInfo
ndisGetFiltersCount
ndisGetHardwareInfo
ndisGetHigherFilterWithPnpRef
ndisGetListEntriesCount
ndisGetLogicalProcessorInformation
ndisGetLowerFilterWithPnpRef
ndisGetMiniportIfBlock
ndisGetMiniportInfo
ndisGetMiniportOffloadCapability
ndisGetNewPatternEntryId
ndisGetOidSourceHandle
ndisGetOrCreateFilterInstanceKey
ndisGetPMProtocolOffloadSize
ndisGetPatternEffectivePriority
ndisGetPciDeviceCustomProperties
ndisGetPerformanceCounters
ndisGetPortList
ndisGetPowerInfo
ndisGetProcessorInfo
ndisGetRdmaCapabilities
ndisGetServiceNameFromRegPath
ndisGetSetBusConfigSpace
ndisGetTaskBytes
ndisGetTimeInterval
ndisGetWakeUpPatternSize
ndisGetWoLPatternSize
ndisGrabOidCancellationList
ndisHandleBindNotification
ndisHandleFilterHandlersChange
ndisHandleLegacyTransport
ndisHandleOrphanDevice
ndisHandlePnPRequest
ndisHandleProtocolReconfigNotification
ndisHandleProtocolUnloadNotification
ndisHandleUModePnPOp
ndisIMCheckDeviceInstance
ndisIMDeleteIfStackEntry
ndisIMInitializeDeviceInstance
ndisIMQueueDeviceInstance
ndisIdleCancelWorkItem
ndisIdleWaitWakeComplete
ndisIfAliasChange
ndisIfAllocateAndVerifyNetLuidIndex
ndisIfCreateCompartment
ndisIfCreateCompartmentBlock
ndisIfCreateFilterInterface
ndisIfCreateInterface
ndisIfCreateInterfaceForiScsi
ndisIfCreateInterfaceFromPersistentStore
ndisIfCreateNetwork
ndisIfCreateNetworkBlock
ndisIfCreatePersistedInterface
ndisIfDeleteCompartment
ndisIfDeletePersistedInterface
ndisIfDeletePersistedInterfaceIsolationInfo
ndisIfDeleteStackEntries
ndisIfDereferenceCompartmentForUser
ndisIfDereferenceMiniport
ndisIfDetachMiniportBlock
ndisIfEnumerateNsiObjects
ndisIfFindAvailableCompartmentId
ndisIfFindCompartmentBlock
ndisIfFindCompartmentBlockByGuid
ndisIfFindInterface
ndisIfFindInterfaceByNetLuid
ndisIfFindNetworkBlock
ndisIfFindNextInterfaceByNetLuid
ndisIfFindNextRcvAddress
ndisIfFindRcvAddress
ndisIfFindStackEntry
ndisIfGetFilterIfInfoFromRegistry
ndisIfGetMiniportStatistics
ndisIfGetRcvAddressFromMiniport
ndisIfInitGetCompartmentList
ndisIfInitGetInterfaceList
ndisIfInitGetNetworkList
ndisIfInitialize
ndisIfQueryBindingMiniportIfIndex
ndisIfQueryFilterObject
ndisIfQueryLoopbackObject
ndisIfQueryMiniportObject
ndisIfQueryMiniportObjectNotPresent
ndisIfQueryObject
ndisIfQueryProvider
ndisIfQuerySetMiniport
ndisIfReferenceCompartmentForUser
ndisIfReferenceMiniport
ndisIfReleaseSiteId
ndisIfRemoveIfBlockMiniportAssociation
ndisIfSetFilterIfInfoInRegistry
ndisIfSetIfDescr
ndisIfSetInterfaceState
ndisIfSetLoopbackObject
ndisIfSetObject
ndisIfUpdateFilterIfStack
ndisIfUpdateInterfaceOnAddDevice
ndisIfUpdateInterfaceOnInitialize
ndisIfUpdatePersistedInterfaceInfo
ndisIfWriteRegistry
ndisImmediateReadWritePort
ndisImmediateReadWriteSharedMemory
ndisIndicateAllNetBufferLists
ndisIndicateInitialStateToBinding
ndisIndicateInitialStateToFilter
ndisIndicateOffloadChangeInternal
ndisIndicatePMCapabilities
ndisIndicateStatusInternal
ndisIndicateToPmodeOpens
ndisIndicateXlatedPacketsToNdis5Protocols
ndisInitModeTimeoutDpc
ndisInitModeTimeoutWorkItem
ndisInitialBindCompleted
ndisInitializeAdapter
ndisInitializeConfiguration
ndisInitializeMiniportRestartAttributes
ndisInitializeNetPnPEvent
ndisInitializeNsi
ndisInitializePerProcessorSlotAllocator
ndisInitializePeriodicReceives
ndisInitializeRef
ndisInitializeStackTraces
ndisInitializeThreadPool
ndisInitializeULongRef
ndisInitializeZeroBasedRef
ndisInsertPatternListEntry
ndisInterruptDpc
ndisInvokeDirectOidRequestComplete
ndisInvokeNextReceiveCompleteHandler
ndisInvokeNextReceiveHandler
ndisInvokeNextSendCompleteHandler
ndisInvokeOidRequestComplete
ndisInvokeOpenAdapterComplete
ndisInvokeStatus
ndisInvokeUnbindAdapter
ndisInvokeUninstall
ndisIovAddSwitchToList
ndisIovAddVPortToPFList
ndisIovAddVPortToVFList
ndisIovAllocateVF
ndisIovCancelIoctlInvalidate
ndisIovCancelIoctlNotification
ndisIovCreateDefaultNicSwitch
ndisIovCreateVPort
ndisIovDeleteDefaultNicSwitch
ndisIovDeleteVPort
ndisIovFindSwitchBySwitchId
ndisIovFindVFByVFId
ndisIovFindVPortByVPortId
ndisIovFreeVF
ndisIovGetNicSwitchList
ndisIovInitVf
ndisIovInvalidateBlockCompletion
ndisIovIoctlAttach
ndisIovIoctlDetach
ndisIovIoctlEventComplete
ndisIovIoctlInvalidate
ndisIovIoctlNotification
ndisIovReadSwitchConfiguration
ndisIovTeardownVf
ndisIsCompartmentEnumerable
ndisIsDefaultPortStateOperational
ndisIsMiniportReady
ndisIsMiniportStarted
ndisIsPMProtocolOffloadSupported
ndisIsSatisfiedByOidGenStatistics
ndisIsValidIfString
ndisIsValidIfStringParts
ndisIsValidMulticastFilter
ndisIsValidPMAdminConfigState
ndisIsValidPmCountedString
ndisIsValidWoLPattern
ndisIsWoLPacketTypeSupported
ndisIssueNetEventSetPowerEvent
ndisKillReceiveWorkerThreadPool
ndisLWM5IndicateReceive
ndisLWM5PauseMiniport
ndisLWM5RestartMinport
ndisLegacyProtocolPauseRestartHandler
ndisLegacyRequest
ndisLiveDumpAddSecondaryData
ndisLogMiniportEvent
ndisMAbortPackets
ndisMAbortRequests
ndisMAllocSGList
ndisMAllocSGListS
ndisMAllocateMiniportOffload
ndisMAllocateRequest
ndisMBeginNormalMode
ndisMCancelSendNetBufferListsOnMiniport
ndisMCheckPacketAndPad
ndisMCheckReceiveFilterPacketCoalescingAttributes
ndisMCleanupMiniportBlockOnStop
ndisMCoFreeResources
ndisMCoOidRequestToRequest
ndisMCommonHaltMiniport
ndisMCopyFromPacketToBuffer
ndisMDeQueueWorkItem
ndisMDeferredDpc
ndisMDeferredReturnPackets
ndisMDeferredSend
ndisMDeferredSendPackets
ndisMDeferredSendPacketsSG
ndisMDeferredSendSG
ndisMDeleteMiniportBlockOnRemove
ndisMDereferenceIfBlock
ndisMDeregisterBugCheckHandler
ndisMDirectOidRequest
ndisMDispatchReceiveNetBufferLists
ndisMDispatchReceiveNetBufferListsWithLock
ndisMDoDirectOidRequest
ndisMDoMiniportOp
ndisMDoOidRequest
ndisMDoProtocolRequest
ndisMDpc
ndisMDpcX
ndisMDummyIndicatePacket
ndisMFakeDirectOidRequest
ndisMFakeOidRequest
ndisMFakeRequest
ndisMFakeReset
ndisMFakeSend
ndisMFakeSendNetBufferLists
ndisMFakeSendPackets
ndisMFakeWanSend
ndisMFindNumaDistances
ndisMFindNumaNode
ndisMFinishClose
ndisMFinishQueuedPendingOpen
ndisMFreeSGList
ndisMGetLogData
ndisMHaltMiniport
ndisMHandleNDKPnPEvents
ndisMIndicateHDSplitChange
ndisMIndicateNetBufferListsToOpen
ndisMIndicateNicSwitchCapsChange
ndisMIndicateOffloadChange
ndisMIndicatePMCapabilities
ndisMIndicatePMHardwareCapabilities
ndisMIndicatePMOffloadReject
ndisMIndicatePacket
ndisMIndicatePacketsToNetBufferLists
ndisMIndicateQosParametersChange
ndisMIndicateReceiveFilterCapsChange
ndisMIndicateReceiveNblsWithThrottling
ndisMIndicateSplitNblChain
ndisMIndicateTcpConnectionOffloadChange
ndisMIndicateWoLPatternReject
ndisMInitializeAdapter
ndisMInitializeInitMode
ndisMInitializeMiniportBlock
ndisMInitializeMiniportBlockFront
ndisMInvokeCancelOidRequest
ndisMInvokeCheckForHang
ndisMInvokeDevicePnPEventNotifyHandler
ndisMInvokeDirectOidRequest
ndisMInvokeDriverUnload
ndisMInvokeFilterResourceRequirements
ndisMInvokeHalt
ndisMInvokeInitialize
ndisMInvokeOidRequest
ndisMInvokePause
ndisMInvokeRemoveDevice
ndisMInvokeReset
ndisMInvokeRestart
ndisMInvokeSetOptions
ndisMInvokeShutdown
ndisMIsLoopbackNetBuffer
ndisMIsLoopbackPacket
ndisMIsr
ndisMKillOpen
ndisMLoopbackNetBufferLists
ndisMLoopbackPacketX
ndisMNotifyMachineName
ndisMOidRequest
ndisMOidRequestCompleteInternal
ndisMOidRequestToRequest
ndisMOpenAdapter
ndisMPowerPolicy
ndisMProcessDeferred
ndisMProcessResetRequested
ndisMProcessSGList
ndisMProcessSGListS
ndisMQueueNewWorkItem
ndisMQueueOidRequest
ndisMQueueReceiveNetBufferLists
ndisMQueueWorkItem
ndisMQueuedAllocateSharedHandler
ndisMQueuedFreeSharedHandler
ndisMReadPciPropertiesFromConfigSpace
ndisMReenumerateFailedAdapterInternal
ndisMReferenceIfBlock
ndisMRegisterBugCheckHandler
ndisMRejectSend
ndisMRejectSendPackets
ndisMReset
ndisMResetCompleteStage1
ndisMResetCompleteStage2
ndisMResetMiniportInternal
ndisMRestoreFilterSettings
ndisMRestoreOpenHandlers
ndisMSend
ndisMSendCompleteNetBufferListsInternal
ndisMSendCompletePacketToNetBufferLists
ndisMSendCompleteSG
ndisMSendCompleteX
ndisMSendNBLToMiniport
ndisMSendNetBufferListsCompleteInternal
ndisMSendNetBufferListsCompleteToNdisPackets
ndisMSendNetBufferListsToPackets
ndisMSendPacketCompleteToOpen
ndisMSendPackets
ndisMSendPacketsSGToMiniport
ndisMSendPacketsToMiniport
ndisMSendPacketsToNetBufferLists
ndisMSendPacketsXToMiniport
ndisMSetGeneralAttributes
ndisMSetHDSplitAttributes
ndisMSetIndicatePacketHandler
ndisMSetMiniportReadyForBinding
ndisMSetNDKAttributes
ndisMSetNative802_11Attributes
ndisMSetNicSwitchAttributes
ndisMSetOffloadAttributes
ndisMSetQosAttributes
ndisMSetReceiveFilterAttributes
ndisMSetRssCapabilities
ndisMSetSriovAttributes
ndisMShutdownMiniport
ndisMStartInitMode
ndisMStartWanSends
ndisMSwapOpenHandlers
ndisMTimerDpc
ndisMTimerDpcX
ndisMTimerObjectDpc
ndisMTopReceiveNetBufferLists
ndisMTransferData
ndisMUnload
ndisMUnloadEx
ndisMUpdateNameOnPMWakePacket
ndisMValidatePMWakePacket
ndisMValidatePMWakeReason
ndisMWakeUpDpc
ndisMWakeUpDpcX
ndisMWanSend
ndisMWanSendCompleteInternal
ndisMapOpenByName
ndisMarkNetBufferListCorrelationIdsAsUsed
ndisMediaDisconnectComplete
ndisMediaDisconnectTimeout
ndisMediaDisconnectWorker
ndisMergeEncapsulations
ndisMergeOffloadCapsAndRegistry
ndisMethodDeviceOid
ndisMiniportDpc
ndisMiniportFatalError
ndisMiniportIsr
ndisMiniportMessageIsr
ndisMiniportPostAddWOLPattern
ndisMiniportPostAddWakeUpPattern
ndisMiniportPostRemoveWoLPattern
ndisMiniportPreAddProtocolOffload
ndisMiniportPreAddWoLPattern
ndisMiniportPreRemoveWOLPattern
ndisMiniportXStateClearFlag
ndisMoveLinkedList
ndisNDKCleanup
ndisNDKGlobalDisabled
ndisNDKHandleWmiChangeRequest
ndisNDKWmiGetAdapterCapabilities
ndisNblTrackerInitialize
ndisNblTrackerReadConfiguration
ndisNblTrackerRecordEvent
ndisNblTrackerTransferOwnershipInternal
ndisNblTrackerTransferOwnershipSingleNbl
ndisNblTrackerWatchdogTimer
ndisNdkPcwAddCounter
ndisNdkPcwCollectData
ndisNdkPcwCollectMiniportStats
ndisNdkPcwEnumerateInstances
ndisNdkPcwMiniportCleanup
ndisNdkPcwProviderCallback
ndisNdkPcwRemoveCounter
ndisNetBufferToPacket
ndisNicActiveAcquire
ndisNicActiveHandleCleanup
ndisNicActiveRelease
ndisNicActiveRequestComplete
ndisNicQuietCheckRef
ndisNicQuietRequestComplete
ndisNicQuietWaitWakeComplete
ndisNotifyAfRegistration
ndisNotifyBindFailure
ndisNotifyBindFailureOnUnboundProtocols
ndisNotifyDevicePowerStateChange
ndisNotifyMiniports
ndisNotifyWmiBindUnbind
ndisNsiChangeInterfaceInfo
ndisNsiChangeNetworkInfo
ndisNsiClientParameterChangeHandler
ndisNsiDeregisterChangeNotification
ndisNsiEnumerateAllCompartments
ndisNsiEnumerateAllIfRcvAddresses
ndisNsiEnumerateAllIfRcvAddressesInOneInterface
ndisNsiEnumerateAllIfStackEntries
ndisNsiEnumerateAllIfStackEntriesFull
ndisNsiEnumerateAllInterfaceInformation
ndisNsiEnumerateAllInvertedIfStackEntries
ndisNsiEnumerateAllNetworks
ndisNsiEnumerateAllSessionInformation
ndisNsiGetAllIfRcvAddress
ndisNsiGetAllInterfaceInformation
ndisNsiGetAllSessionInformation
ndisNsiGetAllThreadInformation
ndisNsiGetCompartmentIdForGuid
ndisNsiGetCompartmentInfo
ndisNsiGetIfNameForIfIndex
ndisNsiGetIfRcvAddress
ndisNsiGetIfRcvAddressRodInformation
ndisNsiGetInterfaceInformation
ndisNsiGetInterfaceRodEnumObject
ndisNsiGetInterfaceRodInformation
ndisNsiGetInterfaceRosEnumObject
ndisNsiGetInterfaceRosInformation
ndisNsiGetInterfaceRwInformation
ndisNsiGetNetworkInfo
ndisNsiGetTopIfBlockFromMiniport
ndisNsiNotifyClientCompartmentChange
ndisNsiNotifyClientInterfaceChange
ndisNsiNotifyClientNetworkChange
ndisNsiProviderAttachNsiClient
ndisNsiProviderCleanupNsiClientContext
ndisNsiProviderDetachNsiClient
ndisNsiQueuedIfBlockRodChangeNotification
ndisNsiRegisterChangeNotification
ndisNsiScheduleIfBlockRodChangeNotification
ndisNsiSetAllCompartment
ndisNsiSetAllNetworkInfo
ndisNsiSetAllSessionInformation
ndisNsiSetAllThreadInformation
ndisNsiSetInterfaceInformation
ndisNsiSetNetworkInfo
ndisNsiSyncMiniportMediaConnectStateNotification
ndisNsiSyncMiniportOperStatusNotification
ndisOidGetStatisticAllProcessors
ndisOidPMAddRemove
ndisOidPMRemove
ndisOidPostAddPMProtocolOffload
ndisOidPostCurrentLookahead
ndisOidPostEnableWakeUp
ndisOidPostEthMulticastList
ndisOidPostEthMulticastOid
ndisOidPostIovAllocateVF
ndisOidPostIovCreateVPort
ndisOidPostIovDeleteVPort
ndisOidPostIovFreeVF
ndisOidPostIovNicSwitchParameters
ndisOidPostIovVPortParameters
ndisOidPostLinkSpeed
ndisOidPostMaxLookahead
ndisOidPostMediaState
ndisOidPostMiniportStats
ndisOidPostOffloadEncapsulation
ndisOidPostPMAddWOLPattern
ndisOidPostPMParameters
ndisOidPostPMRemoveWOLPattern
ndisOidPostPacketFilter
ndisOidPostRSSParameters
ndisOidPostRcvFilterAllocateQueue
ndisOidPostRcvFilterClearFilter
ndisOidPostRcvFilterFreeQueue
ndisOidPostRcvFilterMoveFilter
ndisOidPostRcvFilterQueueParameters
ndisOidPostRcvFilterSetFilter
ndisOidPostRemovePMProtocolOffload
ndisOidPostStatistics
ndisOidPostTaskOffload
ndisOidPostTcpConnectionOffloadParameters
ndisOidPostWakeUpPatternList
ndisOidPostWolPatternList
ndisOidPreAddPMProtocolOffload
ndisOidPreAddWakeUpPattern
ndisOidPreCurrentLookahead
ndisOidPreDriverVersion
ndisOidPreEnableWakeUp
ndisOidPreEnumeratePorts
ndisOidPreEthAddress
ndisOidPreEthMulticastList
ndisOidPreEthMulticastOid
ndisOidPreFriendlyName
ndisOidPreGenStats
ndisOidPreGetPMProtocolOffload
ndisOidPreGetPciDeviceCustomProperties
ndisOidPreHDSplitCurrentConfig
ndisOidPreIovAllocateVF
ndisOidPreIovBarResources
ndisOidPreIovCaps
ndisOidPreIovCreateNicSwitch
ndisOidPreIovCreateVPort
ndisOidPreIovDeleteNicSwitch
ndisOidPreIovDeleteVPort
ndisOidPreIovEnumNicSwitches
ndisOidPreIovEnumVFs
ndisOidPreIovEnumVPorts
ndisOidPreIovFreeVF
ndisOidPreIovGetVFVendorDeviceId
ndisOidPreIovInvalidateConfigBlock
ndisOidPreIovNicSwitchParameters
ndisOidPreIovPfLuid
ndisOidPreIovProbedBars
ndisOidPreIovReadVFConfigBlock
ndisOidPreIovReadVFConfigSpace
ndisOidPreIovResetVF
ndisOidPreIovSetVFPowerState
ndisOidPreIovVFParameters
ndisOidPreIovVPortParameters
ndisOidPreIovVfSerialNumber
ndisOidPreIovWriteVFConfigBlock
ndisOidPreIovWriteVFConfigSpace
ndisOidPreLinkSpeedAndMediaState
ndisOidPreLinkState
ndisOidPreMacAddress
ndisOidPreMacOptions
ndisOidPreMaxFrameOrTotalSize
ndisOidPreMaxLinkSpeed
ndisOidPreMaxListSize
ndisOidPreMaxLookahead
ndisOidPreMediaInUse
ndisOidPreMiniportStats
ndisOidPreNdisIfOidQuery
ndisOidPreNicSwitchCaps
ndisOidPreOffloadCaps
ndisOidPreOffloadEncapsulation
ndisOidPreOffloadHwCaps
ndisOidPreOpenSetEncapsulation
ndisOidPrePMAddWOLPattern
ndisOidPrePMCapabilities
ndisOidPrePMCurrentCapabilities
ndisOidPrePMHaltOnSuspend
ndisOidPrePMHardwareCapabilities
ndisOidPrePMParameters
ndisOidPrePMProtocolOffloadList
ndisOidPrePMRemoveWOLPattern
ndisOidPrePMWOLPatternList
ndisOidPrePacketFilter
ndisOidPrePhysicalMedium
ndisOidPrePnPCapabilities
ndisOidPrePortState
ndisOidPreProtocolOptions
ndisOidPreQosCapabilities
ndisOidPreQosGetParameters
ndisOidPreQosSetParameters
ndisOidPreQueryOffloadEncapsulation
ndisOidPreQueryTcpConnectionParameters
ndisOidPreRSSCaps
ndisOidPreRSSParameters
ndisOidPreRcvFilterAllocateQueue
ndisOidPreRcvFilterAllocationComplete
ndisOidPreRcvFilterClearFilter
ndisOidPreRcvFilterEnumFilters
ndisOidPreRcvFilterEnumQueues
ndisOidPreRcvFilterFreeQueue
ndisOidPreRcvFilterGlobalParameters
ndisOidPreRcvFilterMoveFilter
ndisOidPreRcvFilterParameters
ndisOidPreRcvFilterQueueParameters
ndisOidPreRcvFilterSetFilter
ndisOidPreReceiveFilterCaps
ndisOidPreRemovePMProtocolOffload
ndisOidPreRemoveWakeUpPattern
ndisOidPreSetHDSplitParameters
ndisOidPreSetPortAuthentication
ndisOidPreStatistics
ndisOidPreSupportedList
ndisOidPreTaskOffload
ndisOidPreTcpConnectionOffload
ndisOidPreTcpConnectionOffloadHwCaps
ndisOidPreTcpConnectionOffloadParameters
ndisOidPreWakeUpPatternList
ndisOidRequestComplete
ndisOidTranslateBetweenOids
ndisOpenAdapterLegacyProtocol
ndisOpenCancelSendNetBufferLists
ndisOpenIndicatePMCapabilities
ndisOpenProtocolSubkey
ndisOpenRef
ndisOpenULongRef
ndisPMAddProtocolOffload
ndisPMAddRemoveAsync
ndisPMAddWOLPattern
ndisPMPatternIdExist
ndisPMRejectAsync
ndisPacketToNetBuffer
ndisPadShortPacket
ndisPeriodicReceivesAddCpu
ndisPeriodicReceivesGetMaxNblCount
ndisPeriodicReceivesTimer
ndisPeriodicReceivesWorker
ndisPmHaltMiniport
ndisPmInitializeMiniport
ndisPnPAddDevice
ndisPnPCancelRemoveDevice
ndisPnPCancelStopDevice
ndisPnPDispatch
ndisPnPHandlePagingIrp
ndisPnPIrpCancelRemove
ndisPnPIrpCancelStop
ndisPnPIrpDeviceUsageNotification
ndisPnPIrpFilterResourceRequirements
ndisPnPIrpQueryCapabilities
ndisPnPIrpQueryInterface
ndisPnPIrpQueryPnPDeviceState
ndisPnPIrpQueryRemove
ndisPnPIrpQueryStop
ndisPnPIrpRemoveDevice
ndisPnPIrpStartDevice
ndisPnPIrpStopDevice
ndisPnPIrpSurpriseRemoval
ndisPnPIrpSurpriseRemovalInner
ndisPnPNotifyAllTransports
ndisPnPNotifyBinding
ndisPnPNotifyBindingUnlocked
ndisPnPPortActivation
ndisPnPPortDeactivation
ndisPnPQueryRemoveDevice
ndisPnPQuerySriovInterface
ndisPnPQueryStopDevice
ndisPnPRemoveDevice
ndisPnPRemoveDeviceEx
ndisPnPStartDevice
ndisPopulateRssProcessorSet
ndisPostOffloadAdminSettings
ndisPostOpenSetMulticastList
ndisPostRemoveMiniportWakeUpPattern
ndisPostSetAddWakeUpPattern
ndisPostSetMiniportRSSParameters
ndisPostSetOpenPacketFilter
ndisPostSetOpenRSSParameters
ndisPostSetRemoveWakeUpPattern
ndisPowerDispatch
ndisPowerIrpWorker
ndisPowerSaveClearStop
ndisPowerSaveStop
ndisPowerStateCallback
ndisPowerSuspendRequestComplete
ndisPplCreatePool
ndisPplDestroyPool
ndisPreOffloadAdminSettings
ndisPreQueryPMParameters
ndisPreRemoveMiniportWakeUpPattern
ndisPreRemoveOpenWakeUpPattern
ndisPreSetPMParameters
ndisPreTaskOffloadQuery
ndisPreTaskOffloadSet
ndisProcessRequestAsync
ndisQueryBusInterface
ndisQueryCustomGuids
ndisQueryDeviceFlags
ndisQueryDeviceOid
ndisQueryDriverImageName
ndisQueryDriverInterface
ndisQueryEnableWakeUp
ndisQueryFilterInstanceHandlers
ndisQueryFilterOffloadCaps
ndisQueryGuidData
ndisQueryGuidDataSize
ndisQueryMediaStatus
ndisQueryMiniportEthMulticastList
ndisQueryMiniportOffloadCaps
ndisQueryMiniportPacketFilter
ndisQueryMiniportRSSParameters
ndisQueryOidList
ndisQueryOpenEnableWakeUp
ndisQueryOpenEthMulticastList
ndisQueryOpenPacketFilter
ndisQueryOpenRSSParameters
ndisQueryPower
ndisQueryPowerCapabilities
ndisQueryPowerComplete
ndisQueryPowerCompleteSystemState
ndisQueryReenumerateSelfInterface
ndisQueryReferenceBusInterface
ndisQuerySetMiniport
ndisQuerySetMiniportDeviceState
ndisQuerySetMiniportEx
ndisQuerySetMiniportEx2
ndisQueryStatisticsOids
ndisQuerySupportedGuidToOidList
ndisQueryWakeUpPatternList
ndisQueryWolPatternList
ndisQueueFilterOnDriver
ndisQueueMiniportOnDriver
ndisQueueOidRequest
ndisQueuePowerIrp
ndisQueueReceiveNblsOnMiniport
ndisQueueRequestOnTopAsync
ndisQueueRequestWorkItem
ndisQueueRestoreRequestsOnTop
ndisQueueSendNblsOnMiniport
ndisQueueStackExpansionFallbackWorkItem
ndisQueueWorkItem
ndisQueuedCheckForHang
ndisQueuedMiniportDpcWorkItem
ndisQueuedPnPIrpSurpriseRemoval
ndisQueuedReenumerateFailedAdapter
ndisQueuedResetMiniport
ndisQueuedStatusUnbindAdapter
ndisQueuedUpdatePMCapabilities
ndisReadBindPaths
ndisReadMiniportDefaultPortAuthStates
ndisReadMiniportMediaSpecificPortAuthStates
ndisReadMiniportSpecificPortAuthStates
ndisReadNDKGlobalFlags
ndisReadOffloadRegistry
ndisReadPMAdminConfigState
ndisReadPMRegistry
ndisReadParameter
ndisReadRegParameters
ndisReadRegistry
ndisReadRssKeywords
ndisReadSSTimeoutKeywords
ndisReadUpperBindings
ndisReceiveQueueingOff
ndisReceiveQueueingOn
ndisReceiveQueueingPaused
ndisReceiveQueueingRestart
ndisReceiveWorkerThread
ndisRecordEvent
ndisRefNextFilterForOidCancellation
ndisReferenceAf
ndisReferenceDriver
ndisReferenceFilterByHandle
ndisReferenceFilterDriver
ndisReferenceMiniport
ndisReferenceMiniportByGuid
ndisReferenceMiniportByHandle
ndisReferenceMiniportByHandleForNsi
ndisReferenceMiniportByName
ndisReferenceMiniportByNetLuid
ndisReferenceMiniportNoCheck
ndisReferenceNextUnprocessedMiniport
ndisReferenceNextUnprocessedOpenEx
ndisReferenceOpenByHandle
ndisReferencePackage
ndisReferenceProtocol
ndisReferenceProtocolByName
ndisReferenceRef
ndisReferenceRefNoCheck
ndisReferenceTopMiniportByNameForNsi
ndisReferenceVcPtr
ndisReferenceWithTag
ndisRegisterMiniportDriver
ndisReinitializeMiniportBlock
ndisRejectUnsupportedPMOffloads
ndisRejectUnsupportedWoLPatterns
ndisReleaseMiniportPnPEventLock
ndisReleaseReadWriteLockX
ndisReleaseStackTrace
ndisRemoveOpenFromGlobalList
ndisRemoveOpenWakeUpPattern
ndisRemovePMLowestPriorityEntry
ndisReplayRecvNbls
ndisReplaySendNbls
ndisRequestDeviceLowPower
ndisRequestDevicePowerD0
ndisRequestNicActive
ndisRequestNicQuiet
ndisRequestPowerResume
ndisRequestWaitWake
ndisRequestedDevicePowerIrpComplete
ndisResetPMCapabilities
ndisRestoreFilterHandlersForMediaDisconnect
ndisReturnNblWithPowerQueue
ndisReturnNetBufferListsInternal
ndisReturnNetBufferListsToPackets
ndisReturnPacketToMiniport
ndisReturnPacketToNetBufferList
ndisReturnPeriodicReceives
ndisReturnQueuedLowPowerNbls
ndisRollbackPortActivation
ndisRollbackPortDeactivation
ndisSSGetCachedOidValue
ndisSSGetOidCacheEntry
ndisSSIdleTimerDpc
ndisSSIdleTimerWorkItem
ndisSSInvalidateOidCache
ndisSSUpdateCounters
ndisSSUpdateOidCacheValue
ndisSaveParameters
ndisScheduleD0CompleteSignalWorkItem
ndisScheduleStartDeviceWorkItem
ndisScheduleWorkItemInternal
ndisSelectiveSuspendClearStop
ndisSelectiveSuspendFree
ndisSelectiveSuspendInitialize
ndisSelectiveSuspendResumeOperations
ndisSelectiveSuspendStop
ndisSendCompleteWithPause
ndisSendNBLToFilter
ndisSendPacketsWithPause
ndisSendWithPause
ndisSetAddWakeUpPattern
ndisSetAllFilterDefaultParameters
ndisSetBusyAsync
ndisSetBusySync
ndisSetDeviceInterfaceState
ndisSetDeviceNames
ndisSetDevicePower
ndisSetDevicePowerOnComplete
ndisSetEnableWakeUp
ndisSetFilterDefaultParameter
ndisSetIdleTimer
ndisSetMediaDisconnectTimer
ndisSetMiniportEnableWakeUp
ndisSetMiniportEthMulticastList
ndisSetMiniportHandlers
ndisSetMiniportPacketFilter
ndisSetMiniportRSSParameters
ndisSetMiniportReenumerateHandlers
ndisSetOpenAddWakeUpPattern
ndisSetOpenEnableWakeUp
ndisSetOpenEthAddDeleteMulticast
ndisSetOpenEthMulticastList
ndisSetOpenPacketFilter
ndisSetOpenRSSParameters
ndisSetOpenToTranslationMode
ndisSetPerfTrackParameters
ndisSetPower
ndisSetPowerResume
ndisSetPowerResumeComplete
ndisSetPowerResumeCompleteWorkItem
ndisSetPowerSuspend
ndisSetReceiveFilter
ndisSetRemoveWakeUpPattern
ndisSetRestoreMulticastList
ndisSetRestorePacketFilter
ndisSetSSHandlers
ndisSetSystemPower
ndisSetSystemPowerNotificationHandlers
ndisSetTaskOffloadValidate
ndisSetTempRefTimer
ndisSetWakeUpTimer
ndisSetupDownwardHandlers
ndisSetupLwfMiniportHandlers
ndisSetupMiniportProtocolHandlers
ndisSetupNdis6OpenHandlers
ndisSetupNoFilterHandlers
ndisSetupUpwardHandlers
ndisSetupWmiNode
ndisShouldSuppressReceiveFilterCapabilities
ndisSignalD0CompleteWorkItem
ndisSignalD0RequestComplete
ndisSortNetBufferLists
ndisSourcePreAddProtocolOffload
ndisSourcePreAddWoLPattern
ndisSplitStatisticsOids
ndisSqmAddToStream
ndisSqmCallback
ndisSqmGetMiniportName
ndisSqmGetNicInfo
ndisSqmGetPhysicalMiniportInfo
ndisSqmLogDriverVersion
ndisSqmReadKeywords
ndisSqmSetDWord
ndisSqmTimerDPCRoutine
ndisSqmTimerInitialize
ndisSqmTimerWorkerRoutine
ndisSriovGetResourceForBar
ndisSriovInterfaceDereference
ndisSriovInterfaceGetDeviceLocation
ndisSriovInterfaceGetVendorAndDeviceIds
ndisSriovInterfaceQueryProbedBars
ndisSriovInterfaceReadVFConfig
ndisSriovInterfaceReadVfConfigBlock
ndisSriovInterfaceReference
ndisSriovInterfaceResetVF
ndisSriovInterfaceSetVfPowerState
ndisSriovInterfaceWriteVFConfig
ndisSriovInterfaceWriteVfConfigBlock
ndisSriovQueryLuid
ndisStackExpansionFallbackWorker
ndisStartDeviceSynchronous
ndisStartDeviceWorkItem
ndisStartMapping
ndisStartNsiClient
ndisStartNsiProvider
ndisStopNsiProvider
ndisSubmitIdleRequest
ndisSwapFilterHandlersForMediaDisconnect
ndisSwitchMiniportReceiveFunction
ndisSynchReturnPacketsForTranslation
ndisTempRefTimerDpc
ndisThreadPoolTimerHandler
ndisTopTcpConnectionOffloadStatus
ndisTraceDelayStopRoutine
ndisTraceDpcEnd
ndisTraceDpcStart
ndisTracePeriodicRcvOnOff
ndisTracePeriodicReceivesEnd
ndisTracePeriodicReceivesStart
ndisTraceQueueWorkItem
ndisTraceRcv
ndisTraceRundownDeviceControl
ndisTraceRundownStopTraceWorkItem
ndisTraceWorkItemExecEnd
ndisTraceWorkItemExecStart
ndisTranslateOffloadSetsToTasks
ndisTranslateResources
ndisUnexpectedAoAcError
ndisUnexpectedSsError
ndisUnicodeStringToPointer
ndisUnloadPeriodicReceives
ndisUnprocessAllMiniports
ndisUnprocessAllOpens
ndisUnsetNdis6OpenHandlers
ndisUpdateAndIndicatePMCapabilities
ndisUpdateCheckForLoopbackFlag
ndisUpdateFilterFakeStatus
ndisUpdateHDSplitKeyword
ndisUpdateLoopbackOpens
ndisUpdateMinimumStackVersion
ndisUpdateMiniportFakeStatus
ndisUpdateMiniportPortStates
ndisUpdateNoPauseOnSuspend
ndisUpdateOffloadKeywords
ndisUpdateOperationalStatus
ndisUpdatePMCurrentCapabilities
ndisUpdatePMCurrentParameters
ndisUpdateRcvFilterQueueParameters
ndisUpdateWmiPMParamsForPatterns
ndisUpdateWmiPMParamsForProtocolOffloads
ndisVBusNmrClientAttachProvider
ndisVBusNmrClientCleanupBindingContext
ndisVBusNmrClientDetachProvider
ndisVBusNmrInitializeClient
ndisVBusVirtMiniAdd
ndisVBusVirtMiniRemove
ndisValidOid
ndisValidate60Protocol
ndisValidateConnectionOffload
ndisValidateOffloadCapability
ndisValidateQosParameters
ndisVerifierAllocateMemory
ndisVerifierAllocateMemoryWithTag
ndisVerifierAllocatePacketPool
ndisVerifierAllocatePacketPoolEx
ndisVerifierFreeMemory
ndisVerifierFreePacketPool
ndisVerifierGetRoutineAddress
ndisVerifierInitialization
ndisVerifierInjectResourceFailure
ndisVerifierNdisMIndicateStatusEx
ndisVerifierNdisMOidRequestComplete
ndisVerifierNdisMSendNetBufferListsComplete
ndisVerifierQueryMapRegisterCount
ndisWMIDispatch
ndisWaitForResetCompletion
ndisWaitWakeComplete
ndisWakeUpDevice
ndisWmiChangeSingleInstance
ndisWmiDisableEvents
ndisWmiEnableEvents
ndisWmiExecuteMethod
ndisWmiFindInstanceName
ndisWmiGetGuid
ndisWmiGuidIsAdapterSpecific
ndisWmiMapOids
ndisWmiQueryAllData
ndisWmiQueryPMActiveCapabilities
ndisWmiQuerySingleInstance
ndisWmiRegister
ndisWmiSetPMAdminConfig
ndisWmiXlateEnumNdisRecvQueuesToWmiRecvQueues
ndisWnfPdcCallback
ndisWorkItemHandler
ndisWorkerThread
ndisWriteConfigurationIfPresent
ndisWriteDriverNDISVersionToServiceKey
ndisWritePMAdminConfigState
ndisWriteWmiStatusIndication
ndisXlateAddPacketPatternToWolPatternOid
ndisXlateAddWolPatternToPacketPatternOid
ndisXlateMiniportFlags
ndisXlatePMParametersToWakeUpEnableOid
ndisXlatePnPFlags
ndisXlateRecvNetBufferListsToPacketArray
ndisXlateRecvPacketArrayToNetBufferLists
ndisXlateRemovePacketPatternToWolPatternOid
ndisXlateRemoveWolPatternToPacketPatternOid
ndisXlateReturnNetBufferListToPacket
ndisXlateReturnPacketToNetBufferList
ndisXlateSendCompleteNetBufferListToPacket
ndisXlateSendCompletePacketToNetBufferList
ndisXlateSendNetBufferListsToPacketArray
ndisXlateSendPacketArrayToNetBufferLists
ndisXlateWakeUpEnableToPMParametersOid
ndisXlateWakeUpPatternListToWolPatternList
ndisXlateWolPatternListToWakeUpPatternList
ndispConvOffsetToPointer
ndispConvVar
nullCreateFilter
nullDeleteFilter
nullDeleteFilterOpenAdapter
*/
