enum APPCRUSHER_INPUT
{
  ACI_TOUCH = 0,
  ACI_MOUSE = 1,
  ACI_KEYBOARD = 2,
  ACI_CONTEXTMENU = 3,
  ACI_TASKBAR = 4,
  ACI_TITLEBAR = 5,
  ACI_CAPTIONCONTROLS = 6,
  ACI_MULTITASKINGVIEW = 7,
  ACI_API = 8,
  ACI_HANGDETECTION = 9,
  ACI_INVALID = 10,
};

