enum IEObjectType
{
  IE_EPM_OBJECT_EVENT = 0,
  IE_EPM_OBJECT_MUTEX = 1,
  IE_EPM_OBJECT_SEMAPHORE = 2,
  IE_EPM_OBJECT_SHARED_MEMORY = 3,
  IE_EPM_OBJECT_WAITABLE_TIMER = 4,
  IE_EPM_OBJECT_FILE = 5,
  IE_EPM_OBJECT_NAMED_PIPE = 6,
  IE_EPM_OBJECT_REGISTRY = 7,
};

