enum PRINT_EXECUTION_CONTEXT
{
  PRINT_EXECUTION_CONTEXT_APPLICATION = 0,
  PRINT_EXECUTION_CONTEXT_SPOOLER_SERVICE = 1,
  PRINT_EXECUTION_CONTEXT_SPOOLER_ISOLATION_HOST = 2,
  PRINT_EXECUTION_CONTEXT_FILTER_PIPELINE = 3,
  PRINT_EXECUTION_CONTEXT_WOW64 = 4,
};

struct PRINT_EXECUTION_DATA
{
  /* 0x0000 */ enum PRINT_EXECUTION_CONTEXT context;
  /* 0x0004 */ unsigned long clientAppPID;
}; /* size: 0x0008 */

