enum tagACTIVATIONTYPE
{
  ACTIVATIONTYPE_UNCATEGORIZED = 0,
  ACTIVATIONTYPE_FROM_MONIKER = 1,
  ACTIVATIONTYPE_FROM_DATA = 2,
  ACTIVATIONTYPE_FROM_STORAGE = 4,
  ACTIVATIONTYPE_FROM_STREAM = 8,
  ACTIVATIONTYPE_FROM_FILE = 16,
};

