typedef enum _NDIS_MDRV_REFTAG
{
  MDRVREF_IMDEINIT = 0,
  MDRVREF_REMOVINGMP = 1,
  MDRVREF_MINIPORT = 2,
  MDRVREF_IOWORKITEM = 3,
  MDRVREF_IOWORKITEMC = 4,
  MDRVREF_NOTIFYMINI = 5,
  MDRVREF_MPREFH = 6,
  MDRVREF_MPREFN = 7,
  MDRVREF_MPREFT = 8,
  MDRVREF_CHECKPT = 9,
  MDRVREF_TIMEROBJDPC = 10,
  MDRVREF_TIMERDPCX = 11,
  MDRVREF_NUMBER_OF_TAGS = 12,
} NDIS_MDRV_REFTAG, *PNDIS_MDRV_REFTAG;

