enum DIT_HITTESTATTRIBUTES
{
  DIT_HITTESTATTRIBUTES_NONE = 0,
  DIT_HITTESTATTRIBUTES_MOUSEWHEEL = 1,
  DIT_HITTESTATTRIBUTES_MOUSEWHEELISINCREASING = 2,
  DIT_HITTESTATTRIBUTES_MOUSEWHEELISHORIZONTAL = 4,
  DIT_HITTESTATTRIBUTES_MOUSEBUTTONDOWN = 8,
  DIT_HITTESTATTRIBUTES_TOUCHTARGETING = 16,
  DIT_HITTESTATTRIBUTES_NOHOVERPOINTER = 32,
  DIT_HITTESTATTRIBUTES_BARRELBUTTONDOWN = 64,
  DIT_HITTESTATTRIBUTES_ERASERDOWN = 128,
  DIT_HITTESTATTRIBUTES_CONTROLDOWN = 256,
  DIT_HITTESTATTRIBUTES_VALID = 255,
};

