typedef enum _COPYFILE2_MESSAGE_TYPE
{
  COPYFILE2_CALLBACK_NONE = 0,
  COPYFILE2_CALLBACK_CHUNK_STARTED = 1,
  COPYFILE2_CALLBACK_CHUNK_FINISHED = 2,
  COPYFILE2_CALLBACK_STREAM_STARTED = 3,
  COPYFILE2_CALLBACK_STREAM_FINISHED = 4,
  COPYFILE2_CALLBACK_POLL_CONTINUE = 5,
  COPYFILE2_CALLBACK_ERROR = 6,
  COPYFILE2_CALLBACK_MAX = 7,
} COPYFILE2_MESSAGE_TYPE, *PCOPYFILE2_MESSAGE_TYPE;

