typedef struct _PROCESS_COMBINE_SECURITY_DOMAINS_INFORMATION
{
  /* 0x0000 */ void* ProcessHandle;
} PROCESS_COMBINE_SECURITY_DOMAINS_INFORMATION, *PPROCESS_COMBINE_SECURITY_DOMAINS_INFORMATION; /* size: 0x0008 */

