enum OPERATION_INTERRUPT_RESPONSE_SINGLE
{
  OIRS_ELEVATE = 1,
  OIRS_DELETE = 2,
  OIRS_SKIP = 3,
  OIRS_CANCEL = 4,
  OIRS_RETRY = 5,
  OIRS_YES = 6,
  OIRS_OK = 7,
  OIRS_NO = 8,
  OIRS_KEEPSOURCE = 9,
  OIRS_KEEPDEST = 10,
  OIRS_KEEPBOTH = 11,
  OIRS_KEEPASWORK = 12,
  OIRS_KEEPASPERSONAL = 13,
};

