typedef struct _SYSTEM_FEATURE_CONFIGURATION_SECTIONS_REQUEST
{
  /* 0x0000 */ unsigned __int64 PreviousChangeStamps[3];
} SYSTEM_FEATURE_CONFIGURATION_SECTIONS_REQUEST, *PSYSTEM_FEATURE_CONFIGURATION_SECTIONS_REQUEST; /* size: 0x0018 */

