typedef enum _PERIODIC_FLUSH_FREQUENCY
{
  PERIODIC_FLUSH_FREQUENCY_NONE = 0,
  PERIODIC_FLUSH_FREQUENCY_NORMAL = 1,
  PERIODIC_FLUSH_FREQUENCY_HIGH = 2,
  PERIODIC_FLUSH_FREQUENCY_COUNT = 3,
} PERIODIC_FLUSH_FREQUENCY, *PPERIODIC_FLUSH_FREQUENCY;

