enum PULLSTATE
{
  PULLSTATE0_ENTRY = 0,
  PULLSTATE1_FIRST_CALL = 1,
  PULLSTATE2_NS_RQlsRA = 2,
  PULLSTATE3_NS_RQgeRA = 3,
  PULLSTATE4_S_RQlsBS = 4,
  PULLSTATE5_S_RQgeBS = 5,
  PULLSTATE6_DONE = 6,
};

