typedef struct _EAPOL_REQUEST_ID_MESSAGE_WOL_PACKET_PARAMETERS
{
  /* 0x0000 */ unsigned long Flags;
} EAPOL_REQUEST_ID_MESSAGE_WOL_PACKET_PARAMETERS, *PEAPOL_REQUEST_ID_MESSAGE_WOL_PACKET_PARAMETERS; /* size: 0x0004 */

