typedef struct _POWER_SESSION_ALLOW_EXTERNAL_DMA_DEVICES
{
  /* 0x0000 */ unsigned char IsAllowed;
} POWER_SESSION_ALLOW_EXTERNAL_DMA_DEVICES, *PPOWER_SESSION_ALLOW_EXTERNAL_DMA_DEVICES; /* size: 0x0001 */

