typedef struct _SYSTEM_ACTIVITY_MODERATION_USER_SETTINGS
{
  /* 0x0000 */ void* UserKeyHandle;
} SYSTEM_ACTIVITY_MODERATION_USER_SETTINGS, *PSYSTEM_ACTIVITY_MODERATION_USER_SETTINGS; /* size: 0x0008 */

