enum SAFE_SAVE_OPTIONS
{
  SSO_DEFAULT = 0,
  SSO_NO_READER_OPLOCK = 1,
  SSO_OPEN_REPARSE_POINT = 2,
  SSO_WRITE_SHARING_ON_READ_WRITE_ACCESS_MODE = 4,
  SSO_READONLY_OVERRIDE = 8,
  SSO_FREEZE_MODIFIED_DATE = 16,
  SSO_IMPERSONATE_CREATING_THREAD = 32,
  SSO_DISPOSITION_MASK = 0xffffff00,
};

