typedef enum _TASKDIALOG_FLAGS
{
  TDF_ENABLE_HYPERLINKS = 1,
  TDF_USE_HICON_MAIN = 2,
  TDF_USE_HICON_FOOTER = 4,
  TDF_ALLOW_DIALOG_CANCELLATION = 8,
  TDF_USE_COMMAND_LINKS = 16,
  TDF_USE_COMMAND_LINKS_NO_ICON = 32,
  TDF_EXPAND_FOOTER_AREA = 64,
  TDF_EXPANDED_BY_DEFAULT = 128,
  TDF_VERIFICATION_FLAG_CHECKED = 256,
  TDF_SHOW_PROGRESS_BAR = 512,
  TDF_SHOW_MARQUEE_PROGRESS_BAR = 1024,
  TDF_CALLBACK_TIMER = 2048,
  TDF_POSITION_RELATIVE_TO_WINDOW = 4096,
  TDF_RTL_LAYOUT = 8192,
  TDF_NO_DEFAULT_RADIO_BUTTON = 16384,
  TDF_CAN_BE_MINIMIZED = 0xffff8000,
  TDF_NO_SET_FOREGROUND = 0x10000,
  TDF_SIZE_TO_CONTENT = 0x1000000,
} TASKDIALOG_FLAGS, *PTASKDIALOG_FLAGS;

