enum IMMERSIVELAUNCHERSHOWMETHOD
{
  ILSM_INVALID = 0,
  ILSM_HSHELLTASKMAN = 1,
  ILSM_STARTCHARM = 2,
  ILSM_SEARCHPANE = 3,
  ILSM_IMMERSIVEBACKGROUND = 4,
  ILSM_MOUSECORNER = 5,
  ILSM_APPCLOSED = 6,
  ILSM_APPCRASHED = 7,
  ILSM_COMMANDBAR = 8,
};

