enum ITEMSVIEWSPYVALUE
{
  IVV_FOCUSEDITEM = 0,
  IVV_FIRSTPAGERESULTS_STATE = 1,
  IVV_SELECTIONMANAGER = 2,
  IVV_EVENTQUEUE_SIZE = 3,
  IVV_VIRTUALUIGROUPITEM_COLLECTION = 4,
  IVV_PROCESSID = 5,
  IVV_THREADID = 6,
  IVV_LINESCROLLER = 7,
};

