enum tagOXIDFLAGS
{
  OXIDF_REGISTERED = 1,
  OXIDF_MACHINE_LOCAL = 2,
  OXIDF_STOPPED = 4,
  OXIDF_PENDINGRELEASE = 8,
  OXIDF_REGISTERINGOIDS = 32,
  OXIDF_MTASERVER = 64,
  OXIDF_NTASERVER = 128,
  OXIDF_STASERVER = 256,
  OXIDF_REMOTEINITIALIZED = 512,
  OXIDF_APPLICATION_STA = 2048,
  OXIDF_MTASTOPPED = 68,
  OXIDF_NTASTOPPED = 132,
  OXIDF_APARTMENT_TYPE_FLAGS = 2496,
  OXIDF_ALL = 3055,
};

