typedef enum _FS_BPIO_OPERATIONS
{
  FS_BPIO_OP_ENABLE = 1,
  FS_BPIO_OP_DISABLE = 2,
  FS_BPIO_OP_QUERY = 3,
  FS_BPIO_OP_VOLUME_STACK_PAUSE = 4,
  FS_BPIO_OP_VOLUME_STACK_RESUME = 5,
  FS_BPIO_OP_STREAM_PAUSE = 6,
  FS_BPIO_OP_STREAM_RESUME = 7,
  FS_BPIO_OP_GET_INFO = 8,
  FS_BPIO_OP_MAX_OPERATION = 9,
} FS_BPIO_OPERATIONS, *PFS_BPIO_OPERATIONS;

