typedef enum _FS_BPIO_OPERATIONS
{
  FS_BPIO_OP_ENABLE = 1,
  FS_BPIO_OP_DISABLE = 2,
  FS_BPIO_OP_QUERY = 3,
  FS_BPIO_OP_VOLUME_STACK_PAUSE = 4,
  FS_BPIO_OP_VOLUME_STACK_RESUME = 5,
  FS_BPIO_OP_STREAM_PAUSE = 6,
  FS_BPIO_OP_STREAM_RESUME = 7,
  FS_BPIO_OP_GET_INFO = 8,
  FS_BPIO_OP_MAX_OPERATION = 9,
} FS_BPIO_OPERATIONS, *PFS_BPIO_OPERATIONS;

typedef enum _FS_BPIO_INFLAGS
{
  FSBPIO_INFL_None = 0,
  FSBPIO_INFL_SKIP_STORAGE_STACK_QUERY = 1,
} FS_BPIO_INFLAGS, *PFS_BPIO_INFLAGS;

typedef struct _FS_BPIO_INPUT
{
  /* 0x0000 */ enum _FS_BPIO_OPERATIONS Operation;
  /* 0x0004 */ enum _FS_BPIO_INFLAGS InFlags;
  /* 0x0008 */ unsigned __int64 Reserved1;
  /* 0x0010 */ unsigned __int64 Reserved2;
} FS_BPIO_INPUT, *PFS_BPIO_INPUT; /* size: 0x0018 */

