typedef enum _REFS_STREAM_SNAPSHOT_OPERATION
{
  REFS_STREAM_SNAPSHOT_OPERATION_INVALID = 0,
  REFS_STREAM_SNAPSHOT_OPERATION_CREATE = 1,
  REFS_STREAM_SNAPSHOT_OPERATION_LIST = 2,
  REFS_STREAM_SNAPSHOT_OPERATION_QUERY_DELTAS = 3,
  REFS_STREAM_SNAPSHOT_OPERATION_REVERT = 4,
  REFS_STREAM_SNAPSHOT_OPERATION_SET_SHADOW_BTREE = 5,
  REFS_STREAM_SNAPSHOT_OPERATION_CLEAR_SHADOW_BTREE = 6,
  REFS_STREAM_SNAPSHOT_OPERATION_MAX = 6,
} REFS_STREAM_SNAPSHOT_OPERATION, *PREFS_STREAM_SNAPSHOT_OPERATION;

typedef struct _REFS_STREAM_SNAPSHOT_MANAGEMENT_INPUT_BUFFER
{
  /* 0x0000 */ enum _REFS_STREAM_SNAPSHOT_OPERATION Operation;
  /* 0x0004 */ unsigned short SnapshotNameLength;
  /* 0x0006 */ unsigned short OperationInputBufferLength;
  /* 0x0008 */ unsigned __int64 Reserved[2];
  /* 0x0018 */ unsigned short NameAndInputBuffer[1];
  /* 0x001a */ char __PADDING__[6];
} REFS_STREAM_SNAPSHOT_MANAGEMENT_INPUT_BUFFER, *PREFS_STREAM_SNAPSHOT_MANAGEMENT_INPUT_BUFFER; /* size: 0x0020 */

