typedef enum _SHELLSETWINDOWPOS_OPTIONS
{
  SSWP_OPTION_DEFAULT = 0,
  SSWP_OPTION_NOACTIVATE = 1,
  SSWP_OPTION_NOZORDER = 2,
  SSWP_OPTION_MONITOR_FROM_POSITION = 4,
  SSWP_OPTION_EXPLICIT_RCNORMAL = 8,
  SSWP_OPTION_FOREGROUND = 16,
  SSWP_OPTION_NONOTIFY = 32,
} SHELLSETWINDOWPOS_OPTIONS, *PSHELLSETWINDOWPOS_OPTIONS;

