typedef struct _SYSTEM_ENCLAVE_LAUNCH_CONTROL_INFORMATION
{
  /* 0x0000 */ unsigned char EnclaveLaunchSigner[32];
} SYSTEM_ENCLAVE_LAUNCH_CONTROL_INFORMATION, *PSYSTEM_ENCLAVE_LAUNCH_CONTROL_INFORMATION; /* size: 0x0020 */

