typedef enum _tagSHARE_EVENT
{
  SHARE_EVT_ITEM_SHARED = 0,
  SHARE_EVT_ITEM_UNSHARED = 1,
  SHARE_EVT_ERR_ITEM_LOCATION = 2,
  SHARE_EVT_ERR_NO_WRITE_DAC = 3,
  SHARE_EVT_ERR_INHERITED_PERM = 4,
  SHARE_EVT_ERR_CORRUPTED_LIBRARY = 5,
  SHARE_EVT_ERR_EXCLUSION_FAILED = 6,
  SHARE_EVT_ERR_ROOTDRIVE = 7,
  SHARE_EVT_ERR_SYSTEM_LOCATION = 8,
  SHARE_EVT_ERR_FOLDER_UNAVAILABLE_SCOPE = 9,
  SHARE_EVT_WARN_PUBLISH_FAILED = 10,
  SHARE_EVT_WARN_UNPUBLISH_FAILED = 11,
  SHARE_EVT_WARN_UPDATE_FAILED = 12,
  SHARE_EVT_WARN_NOT_SUPPORTED_SCOPE = 13,
  SHARE_EVT_WARN_FILESYSTEM_ACLS_NOT_SUPPORTED = 14,
  SHARE_EVT_WARN_ITEM_FILTERED = 15,
} tagSHARE_EVENT, *PtagSHARE_EVENT;

