typedef struct _TOKEN_SECURITY_ATTRIBUTES_AND_OPERATION_INFORMATION
{
  /* 0x0000 */ struct _TOKEN_SECURITY_ATTRIBUTES_INFORMATION* Attributes;
  /* 0x0008 */ enum _TOKEN_SECURITY_ATTRIBUTE_OPERATION* Operations;
} TOKEN_SECURITY_ATTRIBUTES_AND_OPERATION_INFORMATION, *PTOKEN_SECURITY_ATTRIBUTES_AND_OPERATION_INFORMATION; /* size: 0x0010 */

