enum CI_WINDOWS_LOCKDOWN_RESTRICTION
{
  CI_WINDOWS_LOCKDOWN_RESTRICTION_NONE = 0,
  CI_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK = 1,
  CI_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK_PERMANENT = 2,
  CI_WINDOWS_LOCKDOWN_RESTRICTION_MAX = 3,
};

