enum COMMAND_SET
{
  CS_FIRST = 0,
  CS_SORTORDER = 0,
  CS_NAVPANE = 1,
  CS_PREVIEWPANE = 2,
  CS_SHOWHIDE = 3,
  CS_CLIPBOARD = 4,
  CS_VOLUMEADDREMOVE = 5,
  CS_LIBRARYADD = 6,
  CS_LEGACYBARSCHANGED = 7,
  CS_WORKOFFLINE = 8,
  CS_FILTER = 9,
  CS_LAST = 10,
};

