typedef enum __MIDL_ILocalObjectExporter_0005
{
  OR_OXID_CLIENT_DEPENDENCY_NONE = 0,
  OR_OXID_CLIENT_DEPENDENCY_UNIDIRECTIONAL = 1,
  OR_OXID_CLIENT_DEPENDENCY_BIDIRECTIONAL = 2,
} _MIDL_ILocalObjectExporter_0005, *P_MIDL_ILocalObjectExporter_0005;

