typedef struct _PROCESS_SECURITY_DOMAIN_INFORMATION
{
  /* 0x0000 */ unsigned __int64 SecurityDomain;
} PROCESS_SECURITY_DOMAIN_INFORMATION, *PPROCESS_SECURITY_DOMAIN_INFORMATION; /* size: 0x0008 */

