typedef struct _SYSTEM_ENERGY_ESTIMATION_CONFIG_INFORMATION
{
  /* 0x0000 */ unsigned char Enabled;
} SYSTEM_ENERGY_ESTIMATION_CONFIG_INFORMATION, *PSYSTEM_ENERGY_ESTIMATION_CONFIG_INFORMATION; /* size: 0x0001 */

