typedef struct _SYSTEM_HYPERVISOR_PROCESSOR_COUNT_INFORMATION
{
  /* 0x0000 */ unsigned long NumberOfLogicalProcessors;
  /* 0x0004 */ unsigned long NumberOfCores;
} SYSTEM_HYPERVISOR_PROCESSOR_COUNT_INFORMATION, *PSYSTEM_HYPERVISOR_PROCESSOR_COUNT_INFORMATION; /* size: 0x0008 */

