enum JOB_OBJECT_NET_RATE_CONTROL_FLAGS
{
  JOB_OBJECT_NET_RATE_CONTROL_ENABLE = 1,
  JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH = 2,
  JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG = 4,
  JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS = 7,
};

struct JOBOBJECT_NET_RATE_CONTROL_INFORMATION
{
  /* 0x0000 */ unsigned __int64 MaxBandwidth;
  /* 0x0008 */ enum JOB_OBJECT_NET_RATE_CONTROL_FLAGS ControlFlags;
  /* 0x000c */ unsigned char DscpTag;
  /* 0x000d */ char __PADDING__[3];
}; /* size: 0x0010 */

