enum SHARE_ACTIVATION_MODE
{
  ACTIVATION_MODE_PRIVATE = 0,
  ACTIVATION_MODE_HOMEGROUP_RO = 1,
  ACTIVATION_MODE_HOMEGROUP_RW = 2,
  ACTIVATION_MODE_HOMEGROUP_NONE = 3,
  ACTIVATION_MODE_USER_RO = 4,
  ACTIVATION_MODE_LIBRARY_ADD = 5,
  ACTIVATION_MODE_LIBRARY_REMOVAL = 6,
  ACTIVATION_MODE_OTHER = 7,
};

