enum tagPOINTER_DEVICE_CURSOR_TYPE
{
  POINTER_DEVICE_CURSOR_TYPE_UNKNOWN = 0,
  POINTER_DEVICE_CURSOR_TYPE_TIP = 1,
  POINTER_DEVICE_CURSOR_TYPE_ERASER = 2,
  POINTER_DEVICE_CURSOR_TYPE_MAX = -1,
};

struct tagPOINTER_DEVICE_CURSOR_INFO
{
  /* 0x0000 */ unsigned int cursorId;
  /* 0x0004 */ enum tagPOINTER_DEVICE_CURSOR_TYPE cursor;
}; /* size: 0x0008 */

