enum PRINT_EXECUTION_CONTEXT
{
  PRINT_EXECUTION_CONTEXT_APPLICATION = 0,
  PRINT_EXECUTION_CONTEXT_SPOOLER_SERVICE = 1,
  PRINT_EXECUTION_CONTEXT_SPOOLER_ISOLATION_HOST = 2,
  PRINT_EXECUTION_CONTEXT_FILTER_PIPELINE = 3,
  PRINT_EXECUTION_CONTEXT_WOW64 = 4,
};

