enum tagACTIVATION_FLAGS
{
  ACTVFLAGS_NONE = 0,
  ACTVFLAGS_DISABLE_AAA = 2,
  ACTVFLAGS_ACTIVATE_32_BIT_SERVER = 4,
  ACTVFLAGS_ACTIVATE_64_BIT_SERVER = 8,
  ACTVFLAGS_SERVERSIDE_ACTIVATION = 16,
  ACTVFLAGS_NO_FAILURE_LOG = 32,
  ACTVFLAGS_ENABLE_CLOAKING = 64,
  ACTVFLAGS_REG_CATALOG_ONLY = 256,
  ACTVFLAGS_SXS_CATALOG_ONLY = 512,
  ACTVFLAGS_WINRT_LOCAL_SERVER = 1024,
  ACTVFLAGS_WINRT_PER_USER_OK = 2048,
  ACTVFLAGS_ACTIVATE_PSCLSID_FROM_PACKAGE = 4096,
  ACTVFLAGS_APPCONTAINER = 8192,
  ACTVFLAGS_IS_SXS_CLASS = 16384,
  ACTVFLAGS_BACKGROUND_MIXED_ACTIVATION = 0xffff8000,
  ACTVFLAGS_BACKGROUND_PURE_ACTIVATION = 0x10000,
  ACTVFLAGS_BACKGROUND_SYSTEM_ACTIVATION = 0x20000,
  ACTVFLAGS_DESIGNMODE_ACTIVATION = 0x40000,
  ACTVFLAGS_ACTIVATE_AS_IU = 0x80000,
  ACTVFLAGS_ACTIVATE_SHARED_AAP_SERVER = 0x100000,
};

