enum tagHOSTDLLFLAGS
{
  HDLLF_SINGLETHREADED = 1,
  HDLLF_APARTMENTTHREADED = 2,
  HDLLF_MULTITHREADED = 4,
  HDLLF_NEUTRALTHREADED = 8,
  HDLLF_HOSTTYPEMASK = 31,
  HDLLF_COMAPARTMENT = 32,
  HDLLF_SHUTTINGDOWN = 256,
};

