typedef enum _MOUSEPROCESSOR_PROCESSING_OPTIONS
{
  MPPO_DEFAULT = 0,
  MPPO_DONT_SWAP_BUTTONS = 1,
  MPPO_SKIP_POWER_MANANGEMENT = 2,
  MPPO_DONT_MOVE_CURSOR = 4,
  MPPO_SURPRESS_INTERCEPT = 8,
  MPPO_USE_EXPLICIT_COORDINATES = 16,
  MPPO_SKIP_BOUND_MOUSE = 32,
  MPPO_DONT_ACTIVATE = 64,
} MOUSEPROCESSOR_PROCESSING_OPTIONS, *PMOUSEPROCESSOR_PROCESSING_OPTIONS;

