typedef enum _MSI_ACTION
{
  MSI_ACTION_INSTALL = 0,
  MSI_ACTION_UNINSTALL = 1,
  MSI_ACTION_UPDATE = 2,
  MSI_ACTION_UPDATE_HASH_MISMATCH = 3,
  MSI_ACTION_UPDATE_HASH_MISSING = 4,
  MSI_ACTION_MAX = 5,
} MSI_ACTION, *PMSI_ACTION;

