typedef struct _SYSTEM_CODEINTEGRITY_CERTIFICATE_INFORMATION
{
  /* 0x0000 */ void* ImageFile;
} SYSTEM_CODEINTEGRITY_CERTIFICATE_INFORMATION, *PSYSTEM_CODEINTEGRITY_CERTIFICATE_INFORMATION; /* size: 0x0004 */

