typedef struct _SYSTEM_HYPERVISOR_SHARED_PAGE_INFORMATION
{
  /* 0x0000 */ void* HypervisorSharedUserVa;
} SYSTEM_HYPERVISOR_SHARED_PAGE_INFORMATION, *PSYSTEM_HYPERVISOR_SHARED_PAGE_INFORMATION; /* size: 0x0008 */

