enum SPATIAL_INPUT_ACTIVATION_POLICY
{
  SPATIAL_INPUT_ACTIVATION_POLICY_ACTIVATE = 0,
  SPATIAL_INPUT_ACTIVATION_POLICY_ACTIVATEANDEAT = 1,
  SPATIAL_INPUT_ACTIVATION_POLICY_NOACTIVATE = 2,
  SPATIAL_INPUT_ACTIVATION_POLICY_NOACTIVATEANDEAT = 3,
  SPATIAL_INPUT_ACTIVATION_POLICY_DEFAULT = 0,
};

