typedef enum _SE_VALIDATE_MAPPING_TYPE
{
  SE_VALIDATE_MAPPING_HEADER_ONLY = 0,
  SE_VALIDATE_MAPPING_ENTIRE_IMAGE = 1,
  SE_VALIDATE_MAPPING_ENTIRE_IMAGE_CLEAN = 2,
} SE_VALIDATE_MAPPING_TYPE, *PSE_VALIDATE_MAPPING_TYPE;

