enum PATHCCH_OPTIONS
{
  PATHCCH_NONE = 0,
  PATHCCH_ALLOW_LONG_PATHS = 1,
  PATHCCH_FORCE_ENABLE_LONG_NAME_PROCESS = 2,
  PATHCCH_FORCE_DISABLE_LONG_NAME_PROCESS = 4,
  PATHCCH_DO_NOT_NORMALIZE_SEGMENTS = 8,
  PATHCCH_ENSURE_IS_EXTENDED_LENGTH_PATH = 16,
  PATHCCH_ENSURE_TRAILING_SLASH = 32,
};

