enum PLACEHOLDER_STATES
{
  PS_NONE = 0,
  PS_MARKED_FOR_OFFLINE_AVAILABILITY = 1,
  PS_FULL_PRIMARY_STREAM_AVAILABLE = 2,
  PS_CREATE_FILE_ACCESSIBLE = 4,
  PS_CLOUDFILE_PLACEHOLDER = 8,
  PS_DEFAULT = 7,
  PS_ALL = 15,
};

