typedef enum _BROWSERFRAMEOPTIONS
{
  BFO_NONE = 0,
  BFO_BROWSER_PERSIST_SETTINGS = 1,
  BFO_RENAME_FOLDER_OPTIONS_TOINTERNET = 2,
  BFO_BOTH_OPTIONS = 4,
  BIF_PREFER_INTERNET_SHORTCUT = 8,
  BFO_BROWSE_NO_IN_NEW_PROCESS = 16,
  BFO_ENABLE_HYPERLINK_TRACKING = 32,
  BFO_USE_IE_OFFLINE_SUPPORT = 64,
  BFO_SUBSTITUE_INTERNET_START_PAGE = 128,
  BFO_USE_IE_LOGOBANDING = 256,
  BFO_ADD_IE_TOCAPTIONBAR = 512,
  BFO_USE_DIALUP_REF = 1024,
  BFO_USE_IE_TOOLBAR = 2048,
  BFO_NO_PARENT_FOLDER_SUPPORT = 4096,
  BFO_NO_REOPEN_NEXT_RESTART = 8192,
  BFO_GO_HOME_PAGE = 16384,
  BFO_PREFER_IEPROCESS = 0xffff8000,
  BFO_SHOW_NAVIGATION_CANCELLED = 0x10000,
  BFO_USE_IE_STATUSBAR = 0x20000,
  BFO_QUERY_ALL = -1,
} BROWSERFRAMEOPTIONS, *PBROWSERFRAMEOPTIONS;

