typedef enum _KF_REDIRECTION_CAPABILITIES
{
  KF_REDIRECTION_CAPABILITIES_ALLOW_ALL = 255,
  KF_REDIRECTION_CAPABILITIES_REDIRECTABLE = 1,
  KF_REDIRECTION_CAPABILITIES_DENY_ALL = 0xfff00,
  KF_REDIRECTION_CAPABILITIES_DENY_POLICY_REDIRECTED = 256,
  KF_REDIRECTION_CAPABILITIES_DENY_POLICY = 512,
  KF_REDIRECTION_CAPABILITIES_DENY_PERMISSIONS = 1024,
} KF_REDIRECTION_CAPABILITIES, *PKF_REDIRECTION_CAPABILITIES;

