typedef enum _NSTCITEMSTATE
{
  NSTCIS_NONE = 0,
  NSTCIS_SELECTED = 1,
  NSTCIS_EXPANDED = 2,
  NSTCIS_BOLD = 4,
  NSTCIS_DISABLED = 8,
  NSTCIS_SELECTEDNOEXPAND = 16,
} NSTCITEMSTATE, *PNSTCITEMSTATE;

