typedef enum _OPPROGDLGF
{
  OPPROGDLG_DEFAULT = 0,
  OPPROGDLG_ENABLEPAUSE = 128,
  OPPROGDLG_ALLOWUNDO = 256,
  OPPROGDLG_DONTDISPLAYSOURCEPATH = 512,
  OPPROGDLG_DONTDISPLAYDESTPATH = 1024,
  OPPROGDLG_NOMULTIDAYESTIMATES = 2048,
  OPPROGDLG_DONTDISPLAYLOCATIONS = 4096,
} OPPROGDLGF, *POPPROGDLGF;

