typedef struct _REFS_QUERY_VOLUME_TOTAL_SHARED_LCNS_OUTPUT_BUFFER
{
  /* 0x0000 */ unsigned long Version;
  /* 0x0008 */ unsigned __int64 TotalSharedLcns;
} REFS_QUERY_VOLUME_TOTAL_SHARED_LCNS_OUTPUT_BUFFER, *PREFS_QUERY_VOLUME_TOTAL_SHARED_LCNS_OUTPUT_BUFFER; /* size: 0x0010 */

