typedef enum _SIIGBF
{
  SIIGBF_RESIZETOFIT = 0,
  SIIGBF_BIGGERSIZEOK = 1,
  SIIGBF_MEMORYONLY = 2,
  SIIGBF_ICONONLY = 4,
  SIIGBF_THUMBNAILONLY = 8,
  SIIGBF_INCACHEONLY = 16,
  SIIGBF_CROPTOSQUARE = 32,
  SIIGBF_WIDETHUMBNAILS = 64,
  SIIGBF_ICONBACKGROUND = 128,
  SIIGBF_SCALEUP = 256,
} SIIGBF, *PSIIGBF;

