typedef enum _TASKDIALOG_NOTIFICATIONS
{
  TDN_CREATED = 0,
  TDN_NAVIGATED = 1,
  TDN_BUTTON_CLICKED = 2,
  TDN_HYPERLINK_CLICKED = 3,
  TDN_TIMER = 4,
  TDN_DESTROYED = 5,
  TDN_RADIO_BUTTON_CLICKED = 6,
  TDN_DIALOG_CONSTRUCTED = 7,
  TDN_VERIFICATION_CLICKED = 8,
  TDN_HELP = 9,
  TDN_EXPANDO_BUTTON_CLICKED = 10,
} TASKDIALOG_NOTIFICATIONS, *PTASKDIALOG_NOTIFICATIONS;

