typedef enum _TRANSFER_SOURCE_FLAGS
{
  TSF_NORMAL = 0,
  TSF_FAIL_EXIST = 0,
  TSF_RENAME_EXIST = 1,
  TSF_OVERWRITE_EXIST = 2,
  TSF_ALLOW_DECRYPTION = 4,
  TSF_NO_SECURITY = 8,
  TSF_COPY_CREATION_TIME = 16,
  TSF_COPY_WRITE_TIME = 32,
  TSF_USE_FULL_ACCESS = 64,
  TSF_DELETE_RECYCLE_IF_POSSIBLE = 128,
  TSF_COPY_HARD_LINK = 256,
  TSF_COPY_LOCALIZED_NAME = 512,
  TSF_MOVE_AS_COPY_DELETE = 1024,
  TSF_SUSPEND_SHELLEVENTS = 2048,
} TRANSFER_SOURCE_FLAGS, *PTRANSFER_SOURCE_FLAGS;

