typedef enum _WINDOW_ACTION_MODIFIERS
{
  WAM_NONE = 0,
  WAM_FRAME_BOUNDS = 1,
  WAM_ACTIVATE_FOREGROUND = 2,
  WAM_ACTIVATE_INPUT = 4,
  WAM_ACTIVATE_NO_ZORDER = 8,
  WAM_INSERT_AFTER_NO_OWNER = 16,
  WAM_RESTORE_TO_NORMAL = 32,
  WAM_RESTORE_TO_MAXIMIZED = 64,
  WAM_RESTORE_TO_ARRANGED = 128,
  WAM_WORK_AREA = 256,
  WAM_DPI = 512,
  WAM_SCALED_TO_MONITOR = 1024,
} WINDOW_ACTION_MODIFIERS, *PWINDOW_ACTION_MODIFIERS;

