typedef enum _WINDOW_ACTION_KINDS
{
  WAK_NONE = 0,
  WAK_VISIBILITY = 1,
  WAK_POSITION = 2,
  WAK_SIZE = 4,
  WAK_INSERT_AFTER = 8,
  WAK_ACTIVATE = 16,
  WAK_PLACEMENT_STATE = 32,
  WAK_NORMAL_RECT = 64,
  WAK_MOVE_TO_MONITOR = 128,
  WAK_FIT_TO_MONITOR = 256,
  WAK_DISPLAY_CHANGE = 512,
  WAK_SYSTEM_OPERATION = 1024,
  WAK_COALESCEABLE = 31,
} WINDOW_ACTION_KINDS, *PWINDOW_ACTION_KINDS;

