enum CF_PLACEHOLDER_STATE
{
  CF_PLACEHOLDER_STATE_NO_STATES = 0,
  CF_PLACEHOLDER_STATE_PLACEHOLDER = 1,
  CF_PLACEHOLDER_STATE_SYNC_ROOT = 2,
  CF_PLACEHOLDER_STATE_ESSENTIAL_PROP_PRESENT = 4,
  CF_PLACEHOLDER_STATE_IN_SYNC = 8,
  CF_PLACEHOLDER_STATE_PARTIAL = 16,
  CF_PLACEHOLDER_STATE_PARTIALLY_ON_DISK = 32,
  CF_PLACEHOLDER_STATE_INVALID = -1,
};

