enum DEFAULT_FOLDER_MENU_RESTRICTIONS
{
  DFMR_DEFAULT = 0,
  DFMR_NO_STATIC_VERBS = 8,
  DFMR_STATIC_VERBS_ONLY = 16,
  DFMR_NO_RESOURCE_VERBS = 32,
  DFMR_OPTIN_HANDLERS_ONLY = 64,
  DFMR_RESOURCE_AND_FOLDER_VERBS_ONLY = 128,
  DFMR_USE_SPECIFIED_HANDLERS = 256,
  DFMR_USE_SPECIFIED_VERBS = 512,
  DFMR_NO_ASYNC_VERBS = 1024,
  DFMR_NO_NATIVECPU_VERBS = 2048,
  DFMR_NO_NONWOW_VERBS = 4096,
};

