enum DROPIMAGETYPE
{
  DROPIMAGE_INVALID = -1,
  DROPIMAGE_NONE = 0,
  DROPIMAGE_COPY = 1,
  DROPIMAGE_MOVE = 2,
  DROPIMAGE_LINK = 4,
  DROPIMAGE_LABEL = 6,
  DROPIMAGE_WARNING = 7,
  DROPIMAGE_NOIMAGE = 8,
};

