enum ELEVATION_REASON
{
  ELEVATION_REASON_APPCOMPAT_EXPLICIT = 0,
  ELEVATION_REASON_APPCOMPAT_HEURISTIC = 1,
  ELEVATION_REASON_FUSION = 2,
  ELEVATION_REASON_INSTALLER = 3,
  ELEVATION_REASON_CLSID = 4,
  ELEVATION_REASON_MSI = 5,
  ELEVATION_REASON_REQUEST = 6,
  ELEVATION_REASON_AXIS = 7,
  ELEVATION_REASON_PACKAGED_APP = 8,
  ELEVATION_REASON_ELEVATEDTOKEN_API = 9,
  ELEVATION_REASON_NUM_REASONS = 10,
};

