enum FILE_OPERATION_EXTENDED_FLAGS
{
  FOEF_NONE = 0,
  FOEF_MERGEFOLDERSONCOLLISION = 1,
  FOEF_LOCAL_COPY_DOWNLOAD = 2,
  FOEF_COPY_AS_PLACEHOLDER = 4,
  FOEF_ALWAYS_WARN_ON_DELETE = 8,
  FOEF_FORCE_MOVE = 16,
  FOEF_ABORT_ON_TRAILING_SPACE_OR_PERIOD = 32,
};

