enum IMMERSIVE_COLOR_BROADCAST_SCENARIO
{
  ICBS_UNKNOWN = 0,
  ICBS_SETTINGS = 1,
  ICBS_APPTHEMEAPI = 2,
  ICBS_IMMERSIVECOLOR_REFRESH = 3,
  ICBS_IMMERSIVECOLOR_SETCOLOR = 4,
  ICBS_THEMEAPPLY = 5,
  ICBS_FILEEXPLORER = 6,
  ICBS_TASKBAR_SETTINGS = 7,
  ICBS_TRAY_ENERGYSAVER = 8,
};

