enum INTERNET_SCHEME
{
  INTERNET_SCHEME_PARTIAL = -2,
  INTERNET_SCHEME_UNKNOWN = -1,
  INTERNET_SCHEME_DEFAULT = 0,
  INTERNET_SCHEME_FTP = 1,
  INTERNET_SCHEME_GOPHER = 2,
  INTERNET_SCHEME_HTTP = 3,
  INTERNET_SCHEME_HTTPS = 4,
  INTERNET_SCHEME_FILE = 5,
  INTERNET_SCHEME_NEWS = 6,
  INTERNET_SCHEME_MAILTO = 7,
  INTERNET_SCHEME_SOCKS = 8,
  INTERNET_SCHEME_JAVASCRIPT = 9,
  INTERNET_SCHEME_VBSCRIPT = 10,
  INTERNET_SCHEME_RES = 11,
  INTERNET_SCHEME_FIRST = 1,
  INTERNET_SCHEME_LAST = 11,
};

