enum KIND_FLAGS
{
  KF_DEFAULT = 0,
  KF_PICTURE = 1,
  KF_MUSIC = 2,
  KF_VIDEO = 4,
  KF_MOVIE = 8,
  KF_RECORDEDTV = 16,
  KF_DOCUMENT = 32,
  KF_FOLDER = 64,
  KF_MULTIMEDIA_MASK = 31,
  KF_VIDEO_MASK = 28,
};

