enum MCFFLAGS
{
  MCF_OPLOCK_NONE = 0,
  MCF_OPLOCK_REQUIRED_WHEN_AVAILABLE = 1,
  MCF_OPLOCK_BACKOFF = 16,
  MCF_READONLY_OVERRIDE = 32,
  MCF_FREEZE_MODIFIED_DATE = 64,
  MCF_OMIT_FILE_SHARE_DELETE = 128,
  MCF_STREAM_ALLOW_FILE_DELETES = 256,
  MCF_FREEZE_LASTACCESS_DATE = 512,
};

