enum tagPROPVAR_COMPARE_FLAGS
{
  PVCF_DEFAULT = 0,
  PVCF_TREATEMPTYASGREATERTHAN = 1,
  PVCF_USESTRCMP = 2,
  PVCF_USESTRCMPC = 4,
  PVCF_USESTRCMPI = 8,
  PVCF_USESTRCMPIC = 16,
  PVCF_DIGITSASNUMBERS_CASESENSITIVE = 32,
};

