enum TOUCHPAD_SENSITIVITY_LEVEL
{
  TOUCHPAD_SENSITIVITY_LEVEL_MOST_SENSITIVE = 0,
  TOUCHPAD_SENSITIVITY_LEVEL_HIGH_SENSITIVITY = 1,
  TOUCHPAD_SENSITIVITY_LEVEL_MEDIUM_SENSITIVITY = 2,
  TOUCHPAD_SENSITIVITY_LEVEL_LOW_SENSITIVITY = 3,
  TOUCHPAD_SENSITIVITY_LEVEL_LEAST_SENSITIVE = 4,
};

