typedef enum _IOMMU_DMA_LOGICAL_ALLOCATOR_CAPABILITY_EXPLICIT_ADDRESS
{
  LogicalAllocatorCapabilityExplicitNotSupported = 0,
  LogicalAllocatorCapabilityExplicitReservedOnly = 1,
  LogicalAllocatorCapabilityExplicitAnyAddress = 2,
} IOMMU_DMA_LOGICAL_ALLOCATOR_CAPABILITY_EXPLICIT_ADDRESS, *PIOMMU_DMA_LOGICAL_ALLOCATOR_CAPABILITY_EXPLICIT_ADDRESS;

typedef struct _IOMMU_DMA_LOGICAL_ALLOCATOR_CAPABILITIES
{
  /* 0x0000 */ enum _IOMMU_DMA_LOGICAL_ALLOCATOR_CAPABILITY_EXPLICIT_ADDRESS ExplicitAddressCapable;
} IOMMU_DMA_LOGICAL_ALLOCATOR_CAPABILITIES, *PIOMMU_DMA_LOGICAL_ALLOCATOR_CAPABILITIES; /* size: 0x0004 */

