typedef enum _IOP_DISPATCH_FUNCTION_TYPE
{
  IOP_DISPATCH_FUNCTION_TYPE_NORMAL = 0,
  IOP_DISPATCH_FUNCTION_TYPE_VERIFY = 1,
  IOP_DISPATCH_FUNCTION_TYPE_EXTEND = 2,
  IOP_DISPATCH_FUNCTION_TYPE_PERF = 3,
} IOP_DISPATCH_FUNCTION_TYPE, *PIOP_DISPATCH_FUNCTION_TYPE;

