typedef struct _KSHARED_READY_QUEUE_AFFINITY_STATISTICS
{
  /* 0x0000 */ unsigned __int64 AffinitySummary;
} KSHARED_READY_QUEUE_AFFINITY_STATISTICS, *PKSHARED_READY_QUEUE_AFFINITY_STATISTICS; /* size: 0x0008 */

