enum tagCallType
{
  CALLTYPE_NONE = 0,
  CALLTYPE_SYNCCALL = 1,
  CALLTYPE_SYNCENTER = 2,
  CALLTYPE_SYNCLEAVE = 3,
  CALLTYPE_SYNCRETURN = 4,
  CALLTYPE_BEGINCALL = 5,
  CALLTYPE_BEGINRETURN = 6,
  CALLTYPE_BEGINENTER = 7,
  CALLTYPE_BEGINLEAVE = 8,
  CALLTYPE_FINISHENTER = 9,
  CALLTYPE_FINISHLEAVE = 10,
  CALLTYPE_FINISHCALL = 11,
  CALLTYPE_FINISHRETURN = 12,
};

