typedef struct _KSHARED_READY_QUEUE_HETERO_STATISTICS
{
  /* 0x0000 */ unsigned __int64 ExpectedRuntimeByClass[8][2][7];
} KSHARED_READY_QUEUE_HETERO_STATISTICS, *PKSHARED_READY_QUEUE_HETERO_STATISTICS; /* size: 0x0380 */

