enum ASTA_TEST_MODE_FLAGS
{
  ASTA_TEST_MODE_NONE = 0,
  ASTA_TEST_MODE_RO_INIT_SINGLETHREADED_CREATES_ASTAS = 1,
  ASTA_TEST_MODE_GIT_LIFETIME_EXTENSION_ENABLED = 2,
  ASTA_TEST_MODE_ROINITIALIZEASTA_ALLOWED = 4,
};

