enum DELAYED_RETRIEVAL_TYPE
{
  DRT_FILEITEM = 0,
  DRT_PREFETCHEDTHUMBNAIL = 1,
  DRT_PREFETCHEDPROPERTIES = 2,
  DRT_PROPERTIES = 3,
  DRT_MUSICPROPERTIES = 4,
  DRT_IMAGEPROPERTIES = 5,
  DRT_VIDEOPROPERTIES = 6,
  DRT_DOCUMENTPROPERTIES = 7,
  DRT_BASICPROPERTIES = 8,
  DRT_REMOTEFILEITEM = 9,
};

