enum EDP_REQUEST_ACCESS_OVERRIDE
{
  EDP_REQUEST_ACCESS_OVERRIDE_NONE = 0,
  EDP_REQUEST_ACCESS_OVERRIDE_SHOW_BLOCK_DIALOG = 1,
  EDP_REQUEST_ACCESS_OVERRIDE_SHOW_OVERRIDE_DIALOG = 2,
  EDP_REQUEST_ACCESS_OVERRIDE_DISABLE_OVERRIDE_DIALOG = 3,
  EDP_REQUEST_ACCESS_OVERRIDE_NO_DIALOG = 4,
};

