enum ASSOCCLASS
{
  ASSOCCLASS_SHELL_KEY = 0,
  ASSOCCLASS_PROGID_KEY = 1,
  ASSOCCLASS_PROGID_STR = 2,
  ASSOCCLASS_CLSID_KEY = 3,
  ASSOCCLASS_CLSID_STR = 4,
  ASSOCCLASS_APP_KEY = 5,
  ASSOCCLASS_APP_STR = 6,
  ASSOCCLASS_SYSTEM_STR = 7,
  ASSOCCLASS_FOLDER = 8,
  ASSOCCLASS_STAR = 9,
  ASSOCCLASS_FIXED_PROGID_STR = 10,
  ASSOCCLASS_PROTOCOL_STR = 11,
};

struct ASSOCIATIONELEMENT
{
  /* 0x0000 */ enum ASSOCCLASS ac;
  /* 0x0004 */ struct HKEY__* hkClass;
  /* 0x0008 */ const wchar_t* pszClass;
}; /* size: 0x000c */

