enum GETPROPERTYSTOREFLAGS
{
  GPS_DEFAULT = 0,
  GPS_HANDLERPROPERTIESONLY = 1,
  GPS_READWRITE = 2,
  GPS_TEMPORARY = 4,
  GPS_FASTPROPERTIESONLY = 8,
  GPS_OPENSLOWITEM = 16,
  GPS_DELAYCREATION = 32,
  GPS_BESTEFFORT = 64,
  GPS_NO_OPLOCK = 128,
  GPS_PREFERQUERYPROPERTIES = 256,
  GPS_EXTRINSICPROPERTIES = 512,
  GPS_EXTRINSICPROPERTIESONLY = 1024,
  GPS_VOLATILEPROPERTIES = 2048,
  GPS_VOLATILEPROPERTIESONLY = 4096,
  GPS_MASK_VALID = 8191,
};

