enum PROCESS_UICONTEXT
{
  PROCESS_UICONTEXT_DESKTOP = 0,
  PROCESS_UICONTEXT_IMMERSIVE = 1,
  PROCESS_UICONTEXT_IMMERSIVE_BROKER = 2,
  PROCESS_UICONTEXT_IMMERSIVE_BROWSER = 3,
};

enum PROCESS_UI_FLAGS
{
  PROCESS_UIF_NONE = 0,
  PROCESS_UIF_AUTHORING_MODE = 1,
  PROCESS_UIF_RESTRICTIONS_DISABLED = 2,
};

struct PROCESS_UICONTEXT_INFORMATION
{
  /* 0x0000 */ enum PROCESS_UICONTEXT processUIContext;
  /* 0x0004 */ enum PROCESS_UI_FLAGS flags;
}; /* size: 0x0008 */

