typedef enum _JOBOBJECT_IO_PRIORITY_LIMIT_FLAGS
{
  JOBOBJECT_IO_PRIORITY_LIMIT_ENABLE = 1,
  JOBOBJECT_IO_PRIORITY_LIMIT_VALID_FLAGS = 1,
} JOBOBJECT_IO_PRIORITY_LIMIT_FLAGS, *PJOBOBJECT_IO_PRIORITY_LIMIT_FLAGS;

