enum NetDmaEventTypes
{
  NdisMIndicateRecvEvent = 0,
  NdisPIndicateRecvEvent = 1,
  NdisPIndicateRecvCompleteEvent = 2,
  NdisPReturnPacketsExEvent = 3,
  NdisMReturnPacketsExEvent = 4,
  NdisPReturnPacketEvent = 5,
  NdisMReturnPacketEvent = 6,
  NdisMReturnPacketInRecvEvent = 7,
  DmaCopyV2VEvent = 8,
  DmaChainV2VNoCopyEvent = 9,
  DmaChainV2VCopyEvent = 10,
  DmaCopyP2VEvent = 11,
  DmaChainP2VNoCopyEvent = 12,
  DmaChainP2VCopyEvent = 13,
  DmaCopyFlushEvent = 14,
  DmaCopyAppendEvent = 15,
  DmaChainCopyAppendEvent = 16,
  DmaCopyFlushAppendEvent = 17,
  DmaCopyCheckForCompletionEvent = 18,
  DmaCopyGetPhysicalAddressEvent = 19,
  DmaCopyNullXferEvent = 20,
  DmaCopyDummyEvent = 21,
  TotalEventTypes = 22,
};

