enum TRACE_LBR_CONFIGURATION
{
  TRACE_LBR_CONFIGURATION_NONE = 0,
  TRACE_LBR_CONFIGURATION_EXCLUDE_KERNEL = 1,
  TRACE_LBR_CONFIGURATION_EXCLUDE_USER = 2,
  TRACE_LBR_CONFIGURATION_EXCLUDE_JCC = 4,
  TRACE_LBR_CONFIGURATION_EXCLUDE_NEAR_REL_CALL = 8,
  TRACE_LBR_CONFIGURATION_EXCLUDE_NEAR_IND_CALL = 16,
  TRACE_LBR_CONFIGURATION_EXCLUDE_NEAR_RET = 32,
  TRACE_LBR_CONFIGURATION_EXCLUDE_NEAR_IND_JMP = 64,
  TRACE_LBR_CONFIGURATION_EXCLUDE_NEAR_REL_JMP = 128,
  TRACE_LBR_CONFIGURATION_EXCLUDE_FAR_BRANCH = 256,
  TRACE_LBR_CONFIGURATION_CALLSTACK_ENABLE = 512,
  TRACE_LBR_CONFIGURATION_SAMPLED = 1024,
};

