typedef enum _DISPLAYCONFIG_ADVANCED_COLOR_MODE
{
  DISPLAYCONFIG_ADVANCED_COLOR_MODE_SDR = 0,
  DISPLAYCONFIG_ADVANCED_COLOR_MODE_WCG = 1,
  DISPLAYCONFIG_ADVANCED_COLOR_MODE_HDR = 2,
} DISPLAYCONFIG_ADVANCED_COLOR_MODE, *PDISPLAYCONFIG_ADVANCED_COLOR_MODE;

