typedef enum _EXPLORERPANESTATE
{
  EPS_DONTCARE = 0,
  EPS_DEFAULT_ON = 1,
  EPS_DEFAULT_OFF = 2,
  EPS_STATEMASK = 0xffffffff,
  EPS_INITIALSTATE = 0x10000,
  EPS_FORCE = 0x20000,
} EXPLORERPANESTATE, *PEXPLORERPANESTATE;

