typedef struct _JOBOBJECT_NETWORK_ACCOUNTING_INFORMATION
{
  /* 0x0000 */ unsigned __int64 DataBytesIn;
  /* 0x0008 */ unsigned __int64 DataBytesOut;
} JOBOBJECT_NETWORK_ACCOUNTING_INFORMATION, *PJOBOBJECT_NETWORK_ACCOUNTING_INFORMATION; /* size: 0x0010 */

