typedef enum _KF_DEFINITION_FLAGS
{
  KFDF_LOCAL_REDIRECT_ONLY = 2,
  KFDF_ROAMABLE = 4,
  KFDF_PRECREATE = 8,
  KFDF_STREAM = 16,
  KFDF_PUBLISHEXPANDEDPATH = 32,
  KFDF_NO_REDIRECT_UI = 64,
} KF_DEFINITION_FLAGS, *PKF_DEFINITION_FLAGS;

