typedef struct _MEMORY_PARTITION_ATTRIBUTE_INFORMATION
{
  /* 0x0000 */ unsigned __int64 Flags;
} MEMORY_PARTITION_ATTRIBUTE_INFORMATION, *PMEMORY_PARTITION_ATTRIBUTE_INFORMATION; /* size: 0x0008 */

