typedef enum _PROPERTYUI_FORMAT_FLAGS
{
  PUIFFDF_DEFAULT = 0,
  PUIFFDF_RIGHTTOLEFT = 1,
  PUIFFDF_SHORTFORMAT = 2,
  PUIFFDF_NOTIME = 4,
  PUIFFDF_FRIENDLYDATE = 8,
} PROPERTYUI_FORMAT_FLAGS, *PPROPERTYUI_FORMAT_FLAGS;

