typedef enum _REFS_DEALLOCATE_RANGES_ALLOCATOR
{
  REFS_DEALLOCATE_RANGES_ALLOCATOR_NONE = 0,
  REFS_DEALLOCATE_RANGES_ALLOCATOR_SAA = 1,
  REFS_DEALLOCATE_RANGES_ALLOCATOR_CAA = 2,
  REFS_DEALLOCATE_RANGES_ALLOCATOR_MAA = 3,
} REFS_DEALLOCATE_RANGES_ALLOCATOR, *PREFS_DEALLOCATE_RANGES_ALLOCATOR;

