typedef struct _REFS_QUERY_VOLUME_IO_METRICS_METRICS_DATA
{
  /* 0x0000 */ unsigned __int64 PlaceHolder;
} REFS_QUERY_VOLUME_IO_METRICS_METRICS_DATA, *PREFS_QUERY_VOLUME_IO_METRICS_METRICS_DATA; /* size: 0x0008 */

