typedef enum _TASKDIALOG_COMMON_BUTTON_FLAGS
{
  TDCBF_OK_BUTTON = 1,
  TDCBF_YES_BUTTON = 2,
  TDCBF_NO_BUTTON = 4,
  TDCBF_CANCEL_BUTTON = 8,
  TDCBF_RETRY_BUTTON = 16,
  TDCBF_CLOSE_BUTTON = 32,
} TASKDIALOG_COMMON_BUTTON_FLAGS, *PTASKDIALOG_COMMON_BUTTON_FLAGS;

