enum AHTYPE
{
  AHTYPE_UNDEFINED = 0,
  AHTYPE_USER_APPLICATION = 8,
  AHTYPE_ANY_APPLICATION = 16,
  AHTYPE_MACHINEDEFAULT = 32,
  AHTYPE_PROGID = 64,
  AHTYPE_APPLICATION = 128,
  AHTYPE_CLASS_APPLICATION = 256,
  AHTYPE_ANY_PROGID = 512,
};

