enum CATEGORYINFO_FLAGS
{
  CATINFO_NORMAL = 0,
  CATINFO_COLLAPSED = 1,
  CATINFO_HIDDEN = 2,
  CATINFO_EXPANDED = 4,
  CATINFO_NOHEADER = 8,
  CATINFO_NOTCOLLAPSIBLE = 16,
  CATINFO_NOHEADERCOUNT = 32,
  CATINFO_SUBSETTED = 64,
  CATINFO_SEPARATE_IMAGES = 128,
  CATINFO_SHOWEMPTY = 256,
};

struct CATEGORY_INFO
{
  /* 0x0000 */ enum CATEGORYINFO_FLAGS cif;
  /* 0x0004 */ wchar_t wszName[260];
}; /* size: 0x020c */

