enum CF_HYDRATION_POLICY_MODIFIER
{
  CF_HYDRATION_POLICY_MODIFIER_NONE = 0,
  CF_HYDRATION_POLICY_MODIFIER_VALIDATION_REQUIRED = 1,
  CF_HYDRATION_POLICY_MODIFIER_STREAMING_ALLOWED = 2,
  CF_HYDRATION_POLICY_MODIFIER_AUTO_DEHYDRATION_ALLOWED = 4,
  CF_HYDRATION_POLICY_MODIFIER_ALLOW_FULL_RESTART_HYDRATION = 8,
};

