enum EXPLORER_BROWSER_OPTIONS
{
  EBO_NONE = 0,
  EBO_NAVIGATEONCE = 1,
  EBO_SHOWFRAMES = 2,
  EBO_ALWAYSNAVIGATE = 4,
  EBO_NOTRAVELLOG = 8,
  EBO_NOWRAPPERWINDOW = 16,
  EBO_HTMLSHAREPOINTVIEW = 32,
  EBO_NOBORDER = 64,
  EBO_NOPERSISTVIEWSTATE = 128,
};

