enum INITFILEHANDLERFLAGS
{
  IFH_DEFAULT = 0,
  IFH_NOIPERSISTSTREAM = 1,
  IFH_NOTRANSACTION = 2,
  IFH_NOIPERSISTFILE = 4,
  IFH_OPLOCKEDSTREAM = 8,
  IFH_INTERRUPTABLESTREAM = 16,
  IFH_ENABLE_SHAREDENYNONE = 32,
  IFH_ENABLE_SHAREDENYWRITE = 64,
  IFH_FREEZE_LASTACCESS = 128,
};

