enum InternetCookieState
{
  COOKIE_STATE_UNKNOWN = 0,
  COOKIE_STATE_ACCEPT = 1,
  COOKIE_STATE_PROMPT = 2,
  COOKIE_STATE_LEASH = 3,
  COOKIE_STATE_DOWNGRADE = 4,
  COOKIE_STATE_REJECT = 5,
  COOKIE_STATE_MAX = 5,
};

