enum SHELL_EXEC_CMD_LINE_OPTIONS
{
  SECL_NONE = 0,
  SECL_USEFULLPATHDIR = 1,
  SECL_NO_UI = 2,
  SECL_SEPARATE_VDM = 4,
  SECL_LOG_USAGE = 8,
  SECL_USECONTEXTMENU = 16,
  SECL_USERINPUT = 32,
  SECL_RUNASELEVATED = 64,
};

