enum tagSYNTHETIC_DEVICE_CREATION_OPTIONS
{
  SYNTHETIC_DEVICE_CREATION_OPTION_NONE = 0,
  SYNTHETIC_DEVICE_CREATION_OPTION_PHYSICAL_SIZE = 1,
  SYNTHETIC_DEVICE_CREATION_OPTION_TOUCHPAD_GESTURE_ONLY = 2,
};

