enum tagSHCOLSTATE
{
  SHCOLSTATE_DEFAULT = 0,
  SHCOLSTATE_TYPE_STR = 1,
  SHCOLSTATE_TYPE_INT = 2,
  SHCOLSTATE_TYPE_DATE = 3,
  SHCOLSTATE_TYPEMASK = 15,
  SHCOLSTATE_ONBYDEFAULT = 16,
  SHCOLSTATE_SLOW = 32,
  SHCOLSTATE_EXTENDED = 64,
  SHCOLSTATE_SECONDARYUI = 128,
  SHCOLSTATE_HIDDEN = 256,
  SHCOLSTATE_PREFER_VARCMP = 512,
  SHCOLSTATE_PREFER_FMTCMP = 1024,
  SHCOLSTATE_NOSORTBYFOLDERNESS = 2048,
  SHCOLSTATE_VIEWONLY = 0x10000,
  SHCOLSTATE_BATCHREAD = 0x20000,
  SHCOLSTATE_NO_GROUPBY = 0x40000,
  SHCOLSTATE_FIXED_WIDTH = 4096,
  SHCOLSTATE_NODPISCALE = 8192,
  SHCOLSTATE_FIXED_RATIO = 16384,
  SHCOLSTATE_DISPLAYMASK = 0xfffff000,
};

