typedef struct _IOMMU_DMA_LOGICAL_ADDRESS_TOKEN_MAPPED_SEGMENT
{
  /* 0x0000 */ struct _IOMMU_DMA_LOGICAL_ADDRESS_TOKEN* OwningToken;
  /* 0x0008 */ unsigned __int64 Offset;
  /* 0x0010 */ unsigned __int64 Size;
} IOMMU_DMA_LOGICAL_ADDRESS_TOKEN_MAPPED_SEGMENT, *PIOMMU_DMA_LOGICAL_ADDRESS_TOKEN_MAPPED_SEGMENT; /* size: 0x0018 */

