enum AppModelPolicy_Type
{
  AppModelPolicy_Type_LifecycleManager = 1,
  AppModelPolicy_Type_AppDataAccess = 2,
  AppModelPolicy_Type_WindowingModel = 3,
  AppModelPolicy_Type_DllSearchOrder = 4,
  AppModelPolicy_Type_Fusion = 5,
  AppModelPolicy_Type_NonWindowsCodeLoading = 6,
  AppModelPolicy_Type_ProcessEnd = 7,
  AppModelPolicy_Type_BeginThreadInit = 8,
  AppModelPolicy_Type_DeveloperInformation = 9,
  AppModelPolicy_Type_CreateFileAccess = 10,
  AppModelPolicy_Type_ImplicitPackageBreakaway = 11,
  AppModelPolicy_Type_ProcessActivationShim = 12,
  AppModelPolicy_Type_AppKnownToStateRepository = 13,
  AppModelPolicy_Type_AudioManagement = 14,
  AppModelPolicy_Type_PackageMayContainPublicComRegistrations = 15,
  AppModelPolicy_Type_PackageMayContainPrivateComRegistrations = 16,
  AppModelPolicy_Type_ComLaunchCreateProcessExtensions = 17,
  AppModelPolicy_Type_ClrCompat = 18,
  AppModelPolicy_Type_LoaderIgnoreAlteredSearchForRelativePath = 19,
  AppModelPolicy_Type_ImplicitlyActivateClassicAAAServersAsIU = 20,
  AppModelPolicy_Type_ComClassicCatalog = 21,
  AppModelPolicy_Type_ComUnmarshaling = 22,
  AppModelPolicy_Type_ComAppLaunchPerfEnhancements = 23,
  AppModelPolicy_Type_ComSecurityInitialization = 24,
  AppModelPolicy_Type_RoInitializeSingleThreadedBehavior = 25,
  AppModelPolicy_Type_ComDefaultExceptionHandling = 26,
  AppModelPolicy_Type_ComOopProxyAgility = 27,
  AppModelPolicy_Type_AppServiceLifetimePolicy = 28,
  AppModelPolicy_Type_WebPlatform = 29,
  AppModelPolicy_Type_WinInetStoragePartitioning = 30,
  AppModelPolicy_Type_Count = 30,
};

