enum DISPLAYSETTINGEVENTTYPE
{
  DSET_DISPLAYDATA_LOADED = 1,
  DSET_PATH_CHANGED = 2,
  DSET_VIEW_ORDER_CHANGED = 4,
  DSET_VIEW_POSITION_CHANGED = 256,
  DSET_VIEW_RESOLUTION_CHANGED = 512,
  DSET_VIEW_COLOR_CHANGED = 1024,
  DSET_VIEW_FREQ_CHANGED = 2048,
  DSET_VIEW_ROTATION_CHANGED = 4096,
  DSET_VIEW_PRIMARY_CHANGED = 8192,
  DSET_VIEW_AUTOROTATION_CHANGED = 16384,
  DSET_VIEW_STEREO_CHANGED = 0xffff8000,
  DSET_VIEW_PROPERTY_CHANGED = 0xffffff00,
};

