typedef enum __MIDL_IActivatorCustomMarshal_0001
{
  SPD_FLAG_USE_CONSOLE_SESSION = 1,
  SPD_FLAG_USE_DEFAULT_AUTHN_LVL = 2,
  SPD_FLAG_USE_SERVER_PID = 4,
  SPD_FLAG_USE_LUA_LEVEL_ADMIN = 8,
  SPD_FLAG_COAUTH_USER_IS_NULL = 16,
  SPD_FLAG_COAUTH_DOMAIN_IS_NULL = 32,
  SPD_FLAG_COAUTH_PWD_IS_NULL = 64,
  SPD_FLAG_USE_LUA_LEVEL_HIGHEST = 128,
} _MIDL_IActivatorCustomMarshal_0001, *P_MIDL_IActivatorCustomMarshal_0001;

