typedef enum __MIDL_INamespaceWalk_0001
{
  NSWF_DEFAULT = 0,
  NSWF_NONE_IMPLIES_ALL = 1,
  NSWF_ONE_IMPLIES_ALL = 2,
  NSWF_DONT_TRAVERSE_LINKS = 4,
  NSWF_DONT_ACCUMULATE_RESULT = 8,
  NSWF_TRAVERSE_STREAM_JUNCTIONS = 16,
  NSWF_FILESYSTEM_ONLY = 32,
  NSWF_SHOW_PROGRESS = 64,
  NSWF_FLAG_VIEWORDER = 128,
  NSWF_IGNORE_AUTOPLAY_HIDA = 256,
  NSWF_ASYNC = 512,
  NSWF_DONT_RESOLVE_LINKS = 1024,
  NSWF_ACCUMULATE_FOLDERS = 2048,
  NSWF_DONT_SORT = 4096,
  NSWF_USE_TRANSFER_MEDIUM = 8192,
  NSWF_DONT_TRAVERSE_STREAM_JUNCTIONS = 16384,
} _MIDL_INamespaceWalk_0001, *P_MIDL_INamespaceWalk_0001;

