typedef enum _NDR_DCOM_PIPE_STATE
{
  NDR_DCOM_NO_PIPES = 0,
  NDR_DCOM_IN_PIPE_PROCESSING = 1,
  NDR_DCOM_IN_PIPES_DRAINED = 2,
  NDR_DCOM_OUT_PIPE_PROCESSING = 3,
  NDR_DCOM_OUT_PIPES_DRAINED = 4,
  NDR_DCOM_PIPES_DONE = 5,
  NDR_DCOM_PIPE_ERROR = 6,
} NDR_DCOM_PIPE_STATE, *PNDR_DCOM_PIPE_STATE;

