enum tagINSTALLUILEVEL
{
  INSTALLUILEVEL_NOCHANGE = 0,
  INSTALLUILEVEL_DEFAULT = 1,
  INSTALLUILEVEL_NONE = 2,
  INSTALLUILEVEL_BASIC = 3,
  INSTALLUILEVEL_REDUCED = 4,
  INSTALLUILEVEL_FULL = 5,
  INSTALLUILEVEL_ENDDIALOG = 128,
  INSTALLUILEVEL_PROGRESSONLY = 64,
  INSTALLUILEVEL_HIDECANCEL = 32,
  INSTALLUILEVEL_SOURCERESONLY = 256,
  INSTALLUILEVEL_UACONLY = 512,
};

