typedef enum _NDIS_IF_REFTAG
{
  IFREF_REGISTER = 0,
  IFREF_GETII = 1,
  IFREF_TOPGETII = 2,
  IFREF_GETALL = 3,
  IFREF_TOPGETALL = 4,
  IFREF_SET = 5,
  IFREF_ENUMALL = 6,
  IFREF_TOPENUMALL = 7,
  IFREF_GETRCVADDR = 8,
  IFREF_GETALLRCVADDR = 9,
  IFREF_ASYNCCHANGE = 10,
  IFREF_CHALIAS = 11,
  IFREF_MINIPORT = 12,
  IFREF_SETDESCR = 13,
  IFREF_UPDATECHARS = 14,
  IFREF_UPDATE = 15,
  IFREF_TIMESTAMPING = 16,
  IFREF_NUMBER_OF_TAGS = 17,
} NDIS_IF_REFTAG, *PNDIS_IF_REFTAG;

