typedef enum _NDIS_LWFDRV_REFTAG
{
  LWFDRV_ATTACHING = 0,
  LWFDRV_IOWORKITEM = 1,
  LWFDRV_IOWORKITEMC = 2,
  LWFDRV_FILTERMODULE = 3,
  LWFDRV_PD_CLIENT = 4,
  LWFDRV_NUMBER_OF_TAGS = 5,
} NDIS_LWFDRV_REFTAG, *PNDIS_LWFDRV_REFTAG;

