typedef struct _IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER
{
  /* 0x0000 */ unsigned char PrologueByteCount;
} IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER, *PIMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER; /* size: 0x0001 */

