typedef enum _REFS_COMPRESSION_FORMATS
{
  REFS_COMPRESSION_FORMAT_UNCOMPRESSED = 0,
  REFS_COMPRESSION_FORMAT_LZ4 = 1,
  REFS_COMPRESSION_FORMAT_ZSTD = 2,
  REFS_COMPRESSION_FORMAT_MAX = 3,
} REFS_COMPRESSION_FORMATS, *PREFS_COMPRESSION_FORMATS;

