typedef enum _REFS_STREAM_EXTENT_PROPERTIES
{
  REFS_STREAM_EXTENT_PROPERTY_VALID = 16,
  REFS_STREAM_EXTENT_PROPERTY_STREAM_RESERVED = 32,
  REFS_STREAM_EXTENT_PROPERTY_CRC32 = 128,
  REFS_STREAM_EXTENT_PROPERTY_CRC64 = 256,
  REFS_STREAM_EXTENT_PROPERTY_GHOSTED = 512,
  REFS_STREAM_EXTENT_PROPERTY_READONLY = 1024,
  REFS_STREAM_EXTENT_PROPERTY_SPARSE = 8,
} REFS_STREAM_EXTENT_PROPERTIES, *PREFS_STREAM_EXTENT_PROPERTIES;

