typedef struct _REFS_SET_VOLUME_DEDUP_INFO_INPUT_BUFFER
{
  /* 0x0000 */ unsigned char Enable;
} REFS_SET_VOLUME_DEDUP_INFO_INPUT_BUFFER, *PREFS_SET_VOLUME_DEDUP_INFO_INPUT_BUFFER; /* size: 0x0001 */

