typedef enum _REFS_STREAM_SNAPSHOT_OPERATION
{
  REFS_STREAM_SNAPSHOT_OPERATION_INVALID = 0,
  REFS_STREAM_SNAPSHOT_OPERATION_CREATE = 1,
  REFS_STREAM_SNAPSHOT_OPERATION_LIST = 2,
  REFS_STREAM_SNAPSHOT_OPERATION_QUERY_DELTAS = 3,
  REFS_STREAM_SNAPSHOT_OPERATION_REVERT = 4,
  REFS_STREAM_SNAPSHOT_OPERATION_SET_SHADOW_BTREE = 5,
  REFS_STREAM_SNAPSHOT_OPERATION_CLEAR_SHADOW_BTREE = 6,
  REFS_STREAM_SNAPSHOT_OPERATION_MAX = 6,
} REFS_STREAM_SNAPSHOT_OPERATION, *PREFS_STREAM_SNAPSHOT_OPERATION;

