typedef struct _REFS_QUERY_VOLUME_DEDUP_INFO_OUTPUT_BUFFER
{
  /* 0x0000 */ unsigned char Enabled;
} REFS_QUERY_VOLUME_DEDUP_INFO_OUTPUT_BUFFER, *PREFS_QUERY_VOLUME_DEDUP_INFO_OUTPUT_BUFFER; /* size: 0x0001 */

