typedef enum _REFS_COMPRESSION_FORMATS
{
  REFS_COMPRESSION_FORMAT_UNCOMPRESSED = 0,
  REFS_COMPRESSION_FORMAT_LZ4 = 1,
  REFS_COMPRESSION_FORMAT_ZSTD = 2,
  REFS_COMPRESSION_FORMAT_MAX = 3,
} REFS_COMPRESSION_FORMATS, *PREFS_COMPRESSION_FORMATS;

typedef enum _REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS
{
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_COMPRESS_SYNC = 1,
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_MAX = 1,
} REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS, *PREFS_SET_VOLUME_COMPRESSION_INFO_FLAGS;

typedef struct _REFS_SET_VOLUME_COMPRESSION_INFO_INPUT_BUFFER
{
  /* 0x0000 */ enum _REFS_COMPRESSION_FORMATS CompressionFormat;
  /* 0x0004 */ short CompressionLevel;
  /* 0x0008 */ unsigned long CompressionChunkSizeBytes;
  /* 0x000c */ enum _REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS Flags;
  /* 0x0010 */ unsigned __int64 Reserved[8];
} REFS_SET_VOLUME_COMPRESSION_INFO_INPUT_BUFFER, *PREFS_SET_VOLUME_COMPRESSION_INFO_INPUT_BUFFER; /* size: 0x0050 */

