typedef enum _REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS
{
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_COMPRESS_SYNC = 1,
  REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_MAX = 1,
} REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS, *PREFS_SET_VOLUME_COMPRESSION_INFO_FLAGS;

