enum EDGEUI_COMPONENT
{
  EUICMP_UNKNOWN = -1,
  EUICMP_SWITCHER = 0,
  EUICMP_CHARMSBAR = 1,
  EUICMP_APPBAR = 2,
  EUICMP_TASKBAR = 3,
  EUICMP_TITLEBAR = 4,
  EUICMP_TABLETMODEVIEWMANAGER = 5,
  EUICMP_ACTIONCENTER = 6,
  EUICMP_DASHBOARD = 7,
  EUICMP_TOTALCOUNT = 8,
};

