enum EDP_TELEMETRY_CALLER
{
  EDP_TELEMETRY_CALLER_COPYPASTE = 0,
  EDP_TELEMETRY_CALLER_SHARE = 1,
  EDP_TELEMETRY_CALLER_OLEDRAGDROP = 2,
  EDP_TELEMETRY_CALLER_WINRTDRAGDROP = 3,
  EDP_TELEMETRY_CALLER_WINRTSTATIC = 4,
  EDP_TELEMETRY_CALLER_OTHER = 5,
};

