typedef enum __MIDL_IListControl_0001
{
  LCIS_NONE = 0,
  LCIS_SELECTED = 1,
  LCIS_FOCUSED = 2,
  LCIS_SELECTIONMARKED = 4,
  LCIS_CHECKED = 8,
  LCIS_CHECKED2 = 16,
  LCIS_KEYBOARDSELECTED = 32,
} _MIDL_IListControl_0001, *P_MIDL_IListControl_0001;

