typedef enum _SecurityOptionsDisposition
{
  ACCESS_DENIED_FOR_ACTIVATION_VIA_RESTRICTION = 1,
  ACCESS_DENIED_FOR_LAUNCH_VIA_RESTRICTION = 2,
  ACCESS_DENIED_FOR_ACTIVATION_VIA_PERMISSION = 4,
  ACCESS_DENIED_FOR_LAUNCH_VIA_PERMISSION = 8,
  ACCESS_DENIED_FOR_CALL_VIA_RESTRICTION = 16,
  ACCESS_DENIED_FOR_CALL_VIA_PERMISSION = 32,
  ACCESS_DENIED_VIA_DEFAULTPERMISSION = 64,
} SecurityOptionsDisposition, *PSecurityOptionsDisposition;

