typedef enum _MM_FIXUPRESULT_ENUM
{
  _MM_FIXUP_NO_CHANGE = 0,
  _MM_FIXUP_NEG_INF = 1,
  _MM_FIXUP_NEG_ZERO = 2,
  _MM_FIXUP_POS_ZERO = 3,
  _MM_FIXUP_POS_INF = 4,
  _MM_FIXUP_NAN = 5,
  _MM_FIXUP_MAX_FLOAT = 6,
  _MM_FIXUP_MIN_FLOAT = 7,
} MM_FIXUPRESULT_ENUM, *PMM_FIXUPRESULT_ENUM;

