enum IMAGEHLP_EXTENDED_OPTIONS
{
  SYMOPT_EX_DISABLEACCESSTIMEUPDATE = 0,
  SYMOPT_EX_LASTVALIDDEBUGDIRECTORY = 1,
  SYMOPT_EX_NOIMPLICITPATTERNSEARCH = 2,
  SYMOPT_EX_NEVERLOADSYMBOLS = 3,
  SYMOPT_EX_MAX = 4,
};

