enum tagPreferredServerBitness
{
  SERVER_BITNESS_DEFAULT = 0,
  SERVER_BITNESS_FOLLOW_CLIENT = 1,
  SERVER_BITNESS_X86 = 2,
  SERVER_BITNESS_X64 = 3,
  SERVER_BITNESS_ARM32 = 4,
  SERVER_BITNESS_ARM64 = 5,
  SERVER_BITNESS_NATIVE = -2147483648,
};

