typedef enum _NDIS_NSI_REFTAG
{
  NSIREF_IOCTL = 0,
  NSIREF_STATUS = 1,
  NSIREF_IFTOP = 2,
  NSIREF_IFSTATS = 3,
  NSIREF_IFOID = 4,
  NSIREF_NUMBER_OF_TAGS = 5,
} NDIS_NSI_REFTAG, *PNDIS_NSI_REFTAG;

