enum tagTASKTYPE
{
  NOTASKS = 0,
  SPECIALPICTURETASKS = 1,
  SPECIALMUSICTASKS = 2,
  SPECIALDOCUMENTTASKS = 3,
  SPECIALVIDEOTASKS = 4,
  SPECIALGENERICTASKS = 5,
  VIEWCONTROLTASKS = 6,
  COMMONFILEDIALOGTASKS = 7,
};

